'use strict';

module.exports = {
  darkMode: 'class',
  content: [
    './account/**/*.{html,php,js}',
    './store/**/*.{html,php,js}',
    './tools/**/*.{html,php,js}',
    './edu/**/*.{html,php,js}',
    './home/**/*.{html,php,js}',
    '!./**/vendor/**',
    '!./**/node_modules/**',
    '!./**/tests/**',
    '!./**/*.min.js',
  ],
  theme: {
    extend: {
      colors: {
        base: '#0d0d0d',
        surface: '#131313',
        'surface-dim': '#0f1117',
        'surface-bright': '#3a3939',
        'surface-elevated': '#1e1e1e',
        'surface-border': 'rgba(255,255,255,0.06)',
        'surface-border-hover': 'rgba(255,255,255,0.12)',
        'surface-container-lowest': '#0e0e0e',
        'surface-container-low': '#1a1a1a',
        'surface-container': '#201f1f',
        'surface-container-high': '#2a2a2a',
        'surface-container-highest': '#353534',
        'surface-variant': '#353534',
        'on-surface': '#e5e2e1',
        'on-surface-variant': '#bbcabf',
        outline: '#86948a',
        'outline-variant': '#3c4a42',
        primary: '#4edea3',
        'on-primary': '#003824',
        'primary-container': '#10b981',
        'on-primary-container': '#00422b',
        'primary-fixed': '#6ffbbe',
        'primary-fixed-dim': '#4edea3',
        'on-primary-fixed': '#002113',
        'on-primary-fixed-variant': '#005236',
        secondary: '#bdc7d9',
        'on-secondary': '#27313f',
        'secondary-container': '#404a59',
        'on-secondary-container': '#afb9cb',
        tertiary: '#c6c6c7',
        'on-tertiary': '#2f3131',
        'tertiary-container': '#a2a3a3',
        accent: '#10b981',
        'accent-hover': '#059669',
        'accent-glow': 'rgba(16,185,129,0.12)',
        error: '#f87171',
        'on-error': '#690005',
        'error-container': '#93000a',
        warning: '#fb923c',
        'warning-container': '#431a00',
        success: '#4ade80',
        background: '#131313',
        'on-background': '#e5e2e1',
        foreground: 'var(--color-foreground)',
        muted: 'var(--color-muted)',
        'card-bg': 'var(--color-card-bg)',
        'border-subtle': 'var(--color-border-subtle)',
        'text-primary': 'var(--color-text-primary)',
        'text-secondary': 'var(--color-text-secondary)',
        'text-muted': 'var(--color-text-muted)',
        'input-bg': 'var(--color-input-bg)',
        'glass-bg': 'var(--color-glass-bg)',
        'glass-border': 'var(--color-glass-border)',
        'glass-highlight': 'var(--color-glass-highlight)',
        'glass-glow': 'var(--color-glass-glow)',
      },
      fontFamily: {
        sora: ['Sora', 'system-ui', 'sans-serif'],
        display: ['Bricolage Grotesque', 'system-ui', 'sans-serif'],
        'mono-label': ['JetBrains Mono', 'ui-monospace', 'monospace'],
      },
      spacing: { xs: '4px', sm: '12px', base: '8px', md: '24px', lg: '48px', xl: '80px', margin: '32px', gutter: '24px' },
    },
  },
  plugins: [require('@tailwindcss/forms'), require('@tailwindcss/container-queries')],
};
