-- TypeScript kurz — Kompletní kurz (20 lekcí + závěrečný kvíz)
-- MariaDB 10.4, phpMyAdmin style, no DELIMITER
-- Apostrofy escapovány jako ''

SET @kurs_id = (SELECT id FROM courses WHERE slug = 'typescript');

-- ============================================================
-- LEKCE 1–20
-- ============================================================

INSERT INTO lessons (course_id, title, content, lesson_type, sort_order, xp_reward, duration_minutes) VALUES
(@kurs_id, 'Úvod do TypeScriptu', '<h2>Proč TypeScript?</h2><p>TypeScript (TS) je nadmnožina JavaScriptu od Microsoftu. Přidává statické typování, které odhalí chyby před spuštěním kódu. Kompiluje se do čistého JS pomocí <code>tsc</code>.</p><pre><code>// instalace\nnpm install -g typescript\n\n// ověření\ntsc --version\n\n// kompilace souboru\ntsc app.ts\n\n// přímé spuštění (ts-node)\nnpx ts-node app.ts</code></pre><h2>První TypeScript program</h2><p>Vytvoř soubor <code>app.ts</code>, napiš kód s typy a zkompiluj.</p><pre><code>interface VeVitUser {\n  id: string;\n  name: string;\n  xp: number;\n  level: number;\n}\n\nconst user: VeVitUser = {\n  id: "u1",\n  name: "Karel",\n  xp: 150,\n  level: 3\n};\n\nconsole.log(`${user.name} — level ${user.level}`);</code></pre>', 'lesson', 1, 15, 12),

(@kurs_id, 'Základní typy', '<h2>Primitivní typy</h2><p>TypeScript nabízí stejné primitivy jako JS plus <code>any</code>, <code>unknown</code>, <code>never</code>, <code>void</code>.</p><pre><code>let jmeno: string = "Karel";\nlet vek: number = 25;\nlet aktivni: boolean = true;\nlet nic: null = null;\nlet nedef: undefined = undefined;</code></pre><h2>any, unknown, never</h2><p><code>any</code> vypne typovou kontrolu. <code>unknown</code> je bezpečnější alternativa — vyžaduje ověření typu před použitím. <code>never</code> pro funkce, které nikdy nevrátí.</p><pre><code>let data: any = "cokoliv"; // pozor!\ndata = 42; // ok, ale ztrácíme typovou bezpečnost\n\nlet vstup: unknown = "hello";\nif (typeof vstup === "string") {\n  console.log(vstup.toUpperCase()); // ok\n}\n\nfunction fail(msg: string): never {\n  throw new Error(msg);\n}</code></pre><h2>Pole a tuple</h2><pre><code>let xpList: number[] = [10, 15, 20];\nlet users: VeVitUser[] = [];\n\n// tuple — pevná délka a typy\nlet pair: [string, number] = ["u1", 150];</code></pre>', 'lesson', 2, 15, 14),

(@kurs_id, 'Interfaces a Type aliases', '<h2>Interface</h2><p>Interface definuje tvar objektu. Podporuje deklarativní slučování (declaration merging).</p><pre><code>interface VeVitUser {\n  id: string;\n  name: string;\n  xp: number;\n  level: number;\n}\n\ninterface VeVitUser {\n  avatar?: string; // volitelný\n  readonly id: string; // nelze změnit\n}\n\nconst user: VeVitUser = {\n  id: "u1",\n  name: "Karel",\n  xp: 150,\n  level: 3\n};</code></pre><h2>Type alias</h2><p><code>type</code> pojmenuje libovolný typ — sjednocení, průniky, primitiva, funkce.</p><pre><code>type Difficulty = "beginner" | "intermediate" | "advanced";\ntype ID = string | number;\n\ntype Course = {\n  id: number;\n  slug: string;\n  title: string;\n  difficulty: Difficulty;\n  xpReward: number;\n  lessonCount: number;\n};</code></pre><h2>Kdy co použít</h2><p><code>interface</code> pro objekty a třídy (umožňuje extends, merging). <code>type</code> pro sjednocení, průniky, mapped types a složitější kombinace.</p>', 'lesson', 3, 15, 14),

(@kurs_id, 'Generika', '<h2>Proč generika?</h2><p>Generika umožňují psát opakovaně použitelný kód, který funguje s různými typy, ale zachovává typovou bezpečnost.</p><pre><code>function identity&lt;T&gt;(value: T): T {\n  return value;\n}\n\nconst num = identity&lt;number&gt;(42);     // typ: number\nconst str = identity&lt;string&gt;("ahoj"); // typ: string</code></pre><h2>Generické funkce — příklad s VeVit</h2><pre><code>function findUser&lt;T extends VeVitUser&gt;(\n  users: T[],\n  id: string\n): T | undefined {\n  return users.find(u => u.id === id);\n}\n\nconst result = findUser(allUsers, "u1");\n// typ: VeVitUser | undefined</code></pre><h2>Generické třídy</h2><pre><code>class Repository&lt;T extends { id: string }&gt; {\n  private items: T[] = [];\n  add(item: T): void { this.items.push(item); }\n  find(id: string): T | undefined {\n    return this.items.find(i => i.id === id);\n  }\n}\n\nconst userRepo = new Repository&lt;VeVitUser&gt;();\nuserRepo.add({ id: "u1", name: "Karel", xp: 0, level: 1 });</code></pre><h2>Constraints</h2><p><code>extends</code> omezuje, jaké typy lze použít jako parametr.</p><pre><code>function getXp&lt;T extends VeVitUser&gt;(user: T): number {\n  return user.xp;\n}</code></pre>', 'lesson', 4, 15, 16),

(@kurs_id, 'TypeScript s DOM', '<h2>querySelector s generiky</h2><p>DOM API vrací <code>Element | null</code>. S TypeScriptem použij generický parametr pro přesnější typ.</p><pre><code>const btn = document.querySelector&lt;HTMLButtonElement&gt;("#submit");\nbtn?.addEventListener("click", () => {\n  console.log("Klik!");\n});\n\nconst input = document.querySelector&lt;HTMLInputElement&gt;("#name");\nif (input) {\n  const value: string = input.value;\n}</code></pre><h2>Event typy</h2><p>Každý typ události má vlastní rozhraní: <code>MouseEvent</code>, <code>KeyboardEvent</code>, <code>SubmitEvent</code> atd.</p><pre><code>btn?.addEventListener("click", (e: MouseEvent) => {\n  console.log(e.clientX, e.clientY);\n});\n\ndocument.addEventListener("keydown", (e: KeyboardEvent) => {\n  if (e.key === "Enter") {\n    console.log("Enter stisknut");\n  }\n});</code></pre><h2>Praktický příklad s VeVit</h2><pre><code>function renderUserCard(user: VeVitUser): void {\n  const container = document.querySelector&lt;HTMLDivElement&gt;("#user-card");\n  if (!container) return;\n  container.innerHTML = `\n    &lt;h3&gt;${user.name}&lt;/h3&gt;\n    &lt;p&gt;XP: ${user.xp} | Level: ${user.level}&lt;/p&gt;\n  `;\n}</code></pre>', 'lesson', 5, 15, 14),

(@kurs_id, 'Utility Types', '<h2>Vestavěné Utility Types</h2><p>TypeScript obsahuje mnoho předpřipravených typů pro transformaci existujících typů.</p><pre><code>interface Course {\n  id: number;\n  slug: string;\n  title: string;\n  difficulty: "beginner" | "intermediate" | "advanced";\n  xpReward: number;\n  lessonCount: number;\n}\n\n// Partial — všechny vlastnosti volitelné\ntype CourseDraft = Partial&lt;Course&gt;;\n\n// Required — všechny povinné (opak Partial)\ntype StrictCourse = Required&lt;Course&gt;;\n\n// Pick — vyber konkrétní vlastnosti\ntype CoursePreview = Pick&lt;Course, "title" | "difficulty"&gt;;\n\n// Omit — vynech vlastnosti\ntype CourseMeta = Omit&lt;Course, "id" | "lessonCount"&gt;;\n\n// Record — slovník s klíči a hodnotami\ntype CourseMap = Record&lt;string, Course&gt;;\n\n// ReturnType — návratový typ funkce\ntype XpType = ReturnType&lt;typeof getXp&gt;;\n\n// Parameters — parametry funkce jako tuple\ntype XpParams = Parameters&lt;typeof getXp&gt;;</code></pre>', 'lesson', 6, 15, 15),

(@kurs_id, 'Mapped Types', '<h2>Co jsou Mapped Types?</h2><p>Mapped Types vytvoří nový typ transformací každé vlastnosti původního typu. Syntaxe: <code>[K in keyof T]</code>.</p><pre><code>type Readonly&lt;T&gt; = {\n  readonly [K in keyof T]: T[K];\n};\n\ntype Optional&lt;T&gt; = {\n  [K in keyof T]?: T[K];\n};\n\n// Použití na VeVit typy\ntype ReadonlyUser = Readonly&lt;VeVitUser&gt;;\ntype OptionalCourse = Optional&lt;Course&gt;;</code></pre><h2>Přejmenování klíčů</h2><p>Od TS 4.1 lze klíče přejmenovat pomocí <code>as</code>.</p><pre><code>type Getters&lt;T&gt; = {\n  [K in keyof T as `get${Capitalize&lt;string & K&gt;}`]: () => T[K];\n};\n\ntype UserGetters = Getters&lt;VeVitUser&gt;;\n// { getId: () => string; getName: () => string; ... }</code></pre><h2>Filtrování klíčů</h2><pre><code>type OnlyStrings&lt;T&gt; = {\n  [K in keyof T as T[K] extends string ? K : never]: T[K];\n};\n\ntype UserStrings = OnlyStrings&lt;VeVitUser&gt;;\n// { id: string; name: string }</code></pre>', 'lesson', 7, 15, 15),

(@kurs_id, 'Conditional Types', '<h2>Conditional Types</h2><p>Podmíněné typy fungují jako ternární operátor pro typy: <code>T extends U ? X : Y</code>.</p><pre><code>type IsString&lt;T&gt; = T extends string ? "yes" : "no";\n\ntype A = IsString&lt;"hello"&gt;; // "yes"\ntype B = IsString&lt;42&gt;;      // "no"</code></pre><h2>infer</h2><p>Klíčové slovo <code>infer</code> extrahuje typ z jiného typu uvnitř podmínky.</p><pre><code>type ReturnOf&lt;T&gt; = T extends (...args: any[]) => infer R ? R : never;\n\ntype R = ReturnOf&lt;typeof getXp&gt;; // number\n\n// Praktické: získej typ položky pole\ntype ElementOf&lt;T&gt; = T extends (infer E)[] ? E : never;\ntype U = ElementOf&lt;VeVitUser[]&gt;; // VeVitUser</code></pre><h2>Distributivní chování</h2><p>Conditional Types se automaticky distribuuje přes sjednocení.</p><pre><code>type ToArray&lt;T&gt; = T extends unknown ? T[] : never;\ntype Result = ToArray&lt;string | number&gt;;\n// string[] | number[]</code></pre>', 'lesson', 8, 15, 16),

(@kurs_id, 'Template Literal Types', '<h2>Template Literal Types</h2><p>Od TS 4.1 lze vytvářet typy pomocí template literálů — obdoba template stringů pro typy.</p><pre><code>type EventName = "click" | "focus" | "blur";\ntype Handler = `on${Capitalize&lt;EventName&gt;}`;\n// "onClick" | "onFocus" | "onBlur"\n\ntype CourseSlug = `course-${string}`;\nconst slug: CourseSlug = "course-typescript"; // ok\nconst bad: CourseSlug = "typescript"; // chyba!</code></pre><h2>Kombinace s Mapped a Conditional Types</h2><pre><code>type Actions = "create" | "update" | "delete";\ntype CourseAction = `${Actions}Course`;\n// "createCourse" | "updateCourse" | "deleteCourse"\n\ntype ApiEndpoint = `/api/${string}`;\n\n// Praktické — typové bezpečné event handlery\ntype VeVitEvent = `${string}:${"before" | "after"}`;\nconst ev: VeVitEvent = "lesson:before"; // ok</code></pre><h2>Intrinsic string manipulation types</h2><pre><code>type U = Uppercase&lt;"hello"&gt;;      // "HELLO"\ntype L = Lowercase&lt;"HELLO"&gt;;      // "hello"\ntype C = Capitalize&lt;"hello"&gt;;    // "Hello"\ntype Uc = Uncapitalize&lt;"Hello"&gt;; // "hello"</code></pre>', 'lesson', 9, 15, 14),

(@kurs_id, 'Třídy pokročile', '<h2>Access modifiers</h2><p><code>public</code> (výchozí), <code>private</code>, <code>protected</code> řídí viditelnost členů třídy. TypeScript také podporuje ECMAScript private fields <code>#</code>.</p><pre><code>class UserProgress {\n  public userId: string;\n  private _xpGained: number = 0;\n  protected completedAt: Date;\n  #score?: number; // ECMAScript private\n\n  constructor(userId: string) {\n    this.userId = userId;\n    this.completedAt = new Date();\n  }\n\n  get xpGained(): number {\n    return this._xpGained;\n  }\n\n  set xpGained(value: number) {\n    if (value < 0) throw new Error("XP nemuze byt zaporne");\n    this._xpGained = value;\n  }\n}</code></pre><h2>Abstract třídy</h2><p>Abstract třídy nelze instanciovat přímo. Slouží jako základ pro podtřídy.</p><pre><code>abstract class BaseService&lt;T&gt; {\n  abstract find(id: string): T | undefined;\n  abstract create(data: Omit&lt;T, "id"&gt;): T;\n\n  log(msg: string): void {\n    console.log(`[${this.constructor.name}] ${msg}`);\n  }\n}\n\nclass CourseService extends BaseService&lt;Course&gt; {\n  private courses: Course[] = [];\n  find(id: string): Course | undefined {\n    return this.courses.find(c => String(c.id) === id);\n  }\n  create(data: Omit&lt;Course, "id"&gt;): Course {\n    const course: Course = { ...data, id: this.courses.length + 1 };\n    this.courses.push(course);\n    return course;\n  }\n}</code></pre>', 'lesson', 10, 15, 16),

(@kurs_id, 'Funkcionální vzory', '<h2>Result&lt;T, E&gt; — typově bezpečné chyby</h2><p>Místo výjimek vrať objekt, který je buď úspěšný nebo chybový. Discriminated union zaručí typovou bezpečnost.</p><pre><code>type Result&lt;T, E = Error&gt; =\n  | { ok: true; value: T }\n  | { ok: false; error: E };\n\nfunction getCourse(slug: string): Result&lt;Course&gt; {\n  const course = courses.find(c => c.slug === slug);\n  if (!course) return { ok: false, error: new Error("Kurz nenalezen") };\n  return { ok: true, value: course };\n}\n\nconst res = getCourse("typescript");\nif (res.ok) {\n  console.log(res.value.title); // TypeScript\n} else {\n  console.error(res.error.message);\n}</code></pre><h2>Pipe s typy</h2><pre><code>function pipe&lt;T&gt;(...fns: Array&lt;(arg: T) => T&gt;): (init: T) => T {\n  return (init: T) => fns.reduce((acc, fn) => fn(acc), init);\n}\n\nconst levelUp = pipe&lt;VeVitUser&gt;(\n  (u) => ({ ...u, xp: u.xp + 15 }),\n  (u) => ({ ...u, level: Math.floor(u.xp / 100) + 1 })\n);\n\nconst upgraded = levelUp({ id: "u1", name: "Karel", xp: 90, level: 1 });\n// { id: "u1", name: "Karel", xp: 105, level: 2 }</code></pre>', 'lesson', 11, 15, 16),

(@kurs_id, 'Typované API volání', '<h2>Generický fetch wrapper</h2><p>Vytvoř typově bezpečnou funkci pro API volání, která zná typ odpovědi.</p><pre><code>async function api&lt;T&gt;(url: string, options?: RequestInit): Promise&lt;T&gt; {\n  const res = await fetch(url, {\n    headers: { "Content-Type": "application/json" },\n    ...options\n  });\n  if (!res.ok) throw new Error(`HTTP ${res.status}`);\n  return res.json() as Promise&lt;T&gt;;\n}\n\n// Použití\nconst courses = await api&lt;Course[]&gt;("/api/courses");\nconst user = await api&lt;VeVitUser&gt;("/api/users/u1");</code></pre><h2>Typový bezpečné mutace</h2><pre><code>async function updateProgress(\n  lessonId: number,\n  data: Partial&lt;UserProgress&gt;\n): Promise&lt;UserProgress&gt; {\n  return api&lt;UserProgress&gt;(`/api/lessons/${lessonId}/progress`, {\n    method: "PATCH",\n    body: JSON.stringify(data)\n  });\n}\n\nconst updated = await updateProgress(5, {\n  xpGained: 15,\n  completedAt: new Date()\n});</code></pre>', 'lesson', 12, 15, 15),

(@kurs_id, 'Moduly a .d.ts soubory', '<h2>Moduly v TypeScriptu</h2><p>Každý soubor s import/export je modul. TypeScript používá ES moduly stejně jako JavaScript.</p><pre><code>// types.ts — export typů\nexport interface VeVitUser {\n  id: string; name: string; xp: number; level: number;\n}\n\n// user-service.ts — import a použití\nimport type { VeVitUser } from "./types";\n\nexport function getUserName(user: VeVitUser): string {\n  return user.name;\n}</code></pre><h2>Deklarační soubory (.d.ts)</h2><p><code>.d.ts</code> soubory deklarují typy bez implementace. Slouží k popisu JS knihoven, které nemají vlastní typy.</p><pre><code>// vevit-analytics.d.ts\ndeclare module "vevit-analytics" {\n  export function trackEvent(name: string, data?: Record&lt;string, unknown&gt;): void;\n  export function identify(userId: string, traits?: Partial&lt;VeVitUser&gt;): void;\n}\n\n// nyní lze importovat s plnou typovou podporou\nimport { trackEvent, identify } from "vevit-analytics";\ntrackEvent("lesson_completed", { xp: 15 });\nidentify("u1", { name: "Karel" });</code></pre><h2>DefinitelyTyped</h2><p>Pro populární knihovny bez typů nainstaluj <code>@types/jméno</code> z DefinitelyTyped.</p><pre><code>npm install --save-dev @types/node @types/jest</code></pre>', 'lesson', 13, 15, 14),

(@kurs_id, 'tsconfig.json', '<h2>Základní tsconfig.json</h2><p>Konfigurace kompilátoru TypeScript. Každý TS projekt by měl mít <code>tsconfig.json</code>.</p><pre><code>{\n  "compilerOptions": {\n    "target": "ES2022",\n    "module": "ESNext",\n    "moduleResolution": "bundler",\n    "strict": true,\n    "esModuleInterop": true,\n    "skipLibCheck": true,\n    "forceConsistentCasingInFileNames": true,\n    "outDir": "./dist",\n    "rootDir": "./src",\n    "declaration": true,\n    "sourceMap": true\n  },\n  "include": ["src/**/*"],\n  "exclude": ["node_modules", "dist"]\n}</code></pre><h2>Důležitá nastavení</h2><p><code>strict: true</code> zapne všechny striktní kontroly. <code>target</code> určuje výstupní verzi JS. <code>paths</code> umožňuje aliasy importů.</p><pre><code>{\n  "compilerOptions": {\n    "strict": true,       // zapne strictNullChecks, noImplicitAny atd.\n    "target": "ES2022",   // moderní JS výstup\n    "noUncheckedIndexedAccess": true, // bezpečný přístup k poli/objektu\n    "paths": {\n      "@/*": ["./src/*"] // alias pro importy\n    },\n    "baseUrl": "."\n  }\n}\n\n// Import s aliasem\nimport { VeVitUser } from "@/types";\n// místo: import { VeVitUser } from "../../types";</code></pre>', 'lesson', 14, 15, 14),

(@kurs_id, 'Zod — runtime validace', '<h2>Proč Zod?</h2><p>TypeScript kontroluje typy jen při kompilaci. Zod validuje data za běhu (runtime) a zároveň generuje TS typy.</p><pre><code>import { z } from "zod";\n\n// Definice schématu\nconst VeVitUserSchema = z.object({\n  id: z.string(),\n  name: z.string().min(1),\n  xp: z.number().nonnegative(),\n  level: z.number().int().min(1)\n});\n\n// Odvození TS typu ze schématu\ntype VeVitUser = z.infer&lt;typeof VeVitUserSchema&gt;;\n\n// Validace dat\nconst result = VeVitUserSchema.safeParse({\n  id: "u1",\n  name: "Karel",\n  xp: 150,\n  level: 3\n});\n\nif (result.success) {\n  console.log(result.data.name); // Karel\n} else {\n  console.error(result.error.issues);\n}</code></pre><h2>Zod pro API validaci</h2><pre><code>const CourseSchema = z.object({\n  slug: z.string(),\n  title: z.string(),\n  difficulty: z.enum(["beginner", "intermediate", "advanced"]),\n  xpReward: z.number()\n});\n\n// Validace vstupu z API\napp.post("/api/courses", (req, res) => {\n  const parsed = CourseSchema.safeParse(req.body);\n  if (!parsed.success) {\n    return res.status(400).json(parsed.error.issues);\n  }\n  // parsed.data je typově bezpečný\n});</code></pre>', 'lesson', 15, 15, 16),

(@kurs_id, 'TypeScript s Tailwind a DOM', '<h2>Typově bezpečné DOM manipulace s Tailwind</h2><p>Kombinace TypeScript a Tailwind CSS pro tvorbu dynamických UI komponent.</p><pre><code>interface Course {\n  id: number; slug: string; title: string;\n  difficulty: "beginner" | "intermediate" | "advanced";\n  xpReward: number; lessonCount: number;\n}\n\nconst difficultyColors: Record&lt;Course["difficulty"], string&gt; = {\n  beginner: "bg-green-100 text-green-800",\n  intermediate: "bg-yellow-100 text-yellow-800",\n  advanced: "bg-red-100 text-red-800"\n};\n\nfunction renderCourseCard(course: Course): void {\n  const card = document.createElement("div");\n  card.className = `p-4 rounded-lg shadow ${difficultyColors[course.difficulty]}`;\n  card.innerHTML = `\n    &lt;h3 class="font-bold"&gt;${course.title}&lt;/h3&gt;\n    &lt;p&gt;${course.lessonCount} lekcí | ${course.xpReward} XP&lt;/p&gt;\n  `;\n  document.querySelector&lt;HTMLElement&gt;("#courses")?.appendChild(card);\n}</code></pre><h2>Typově bezpečné CSS třídy</h2><pre><code>type TailwindColor = "green" | "yellow" | "red" | "blue";\nfunction badge(color: TailwindColor, text: string): string {\n  return `&lt;span class="px-2 py-1 rounded text-${color}-700 bg-${color}-100"&gt;${text}&lt;/span&gt;`;\n}\n\nbadge("green", "Zahajeno");\nbadge("blue", "V probehu");</code></pre>', 'lesson', 16, 15, 14),

(@kurs_id, 'Error handling', '<h2>unknown typ pro chyby</h2><p>Nikdy nepoužívej <code>any</code> pro catch. Od TS 4.4 lze nastavit <code>useUnknownInCatchVariables</code>.</p><pre><code>try {\n  await api&lt;VeVitUser&gt;("/api/users/u1");\n} catch (err: unknown) {\n  if (err instanceof Error) {\n    console.error(err.message);\n  } else if (typeof err === "string") {\n    console.error(err);\n  } else {\n    console.error("Neznama chyba");\n  }\n}</code></pre><h2>Custom error třídy</h2><pre><code>class AppError extends Error {\n  constructor(\n    message: string,\n    public code: string,\n    public statusCode: number\n  ) {\n    super(message);\n    this.name = this.constructor.name;\n  }\n}\n\nclass NotFoundError extends AppError {\n  constructor(resource: string) {\n    super(`${resource} nenalezen`, "NOT_FOUND", 404);\n  }\n}\n\nclass ValidationError extends AppError {\n  constructor(field: string) {\n    super(`Neplatna hodnota: ${field}`, "VALIDATION_ERROR", 400);\n  }\n}</code></pre><h2>Discriminated union pro chyby</h2><pre><code>type ApiResponse&lt;T&gt; =\n  | { status: "success"; data: T }\n  | { status: "error"; error: { code: string; message: string } };\n\nfunction handleResponse&lt;T&gt;(res: ApiResponse&lt;T&gt;): T {\n  switch (res.status) {\n    case "success": return res.data;\n    case "error": throw new AppError(res.error.message, res.error.code, 500);\n  }\n}</code></pre>', 'lesson', 17, 15, 15),

(@kurs_id, 'Testování s Vitest', '<h2>Vitest — rychlé testování pro Vite</h2><p>Vitest je kompatibilní s Jest API, ale běží na Vite. Nativní podpora TypeScript bez dodatečné konfigurace.</p><pre><code>// vitest.config.ts\nimport { defineConfig } from "vitest/config";\nexport default defineConfig({\n  test: {\n    globals: true,\n    typecheck: true\n  }\n});</code></pre><h2>Psaní testů</h2><pre><code>import { describe, it, expect } from "vitest";\nimport { VeVitUser } from "./types";\nimport { levelUp } from "./user";\n\ndescribe("levelUp", () => {\n  it("zvysi XP a prepocita level", () => {\n    const user: VeVitUser = {\n      id: "u1", name: "Karel", xp: 90, level: 1\n    };\n    const result = levelUp(user, 15);\n    expect(result.xp).toBe(105);\n    expect(result.level).toBe(2);\n  });\n\n  it("nezvysi level pod 100 XP", () => {\n    const user: VeVitUser = {\n      id: "u1", name: "Karel", xp: 50, level: 1\n    };\n    const result = levelUp(user, 10);\n    expect(result.level).toBe(1);\n  });\n});</code></pre><h2>Testování typů</h2><pre><code>import { expectTypeOf } from "vitest";\n\nit("VeVitUser ma spravne typy", () => {\n  expectTypeOf&lt;VeVitUser&gt;().toHaveProperty("id").toBeString();\n  expectTypeOf&lt;VeVitUser&gt;().toHaveProperty("xp").toBeNumber();\n});</code></pre>', 'lesson', 18, 15, 15),

(@kurs_id, 'Migrace JS projektu na TypeScript', '<h2>Strategie migrace</h2><p>Přechod z JS na TS nemusí být najednou. Postupuj krok za krokem.</p><pre><code>// 1. Povol JS v tsconfig\n// {\n//   "compilerOptions": {\n//     "allowJs": true,\n//     "noImplicitAny": false  // na zacatku\n//   }\n// }\n\n// 2. Prejmenuj .js na .ts postupne\n// 3. Pridej typy k funkcim\n// 4. Zapni strict po otypovani</code></pre><h2>Postup krok za krokem</h2><p><strong>1.</strong> Nainstaluj TS a vytvoř <code>tsconfig.json</code> s <code>allowJs: true</code>.</p><p><strong>2.</strong> Přejmenuj jeden soubor z <code>.js</code> na <code>.ts</code> — oprav chyby.</p><p><strong>3.</strong> Přidej typy k funkcím a proměnným.</p><p><strong>4.</strong> Definuj interfaces pro datové struktury.</p><p><strong>5.</strong> Zapni <code>strict: true</code> a postupně odstraň <code>any</code>.</p><pre><code>// Pred migraci (JS)\nfunction getUser(id) {\n  return fetch("/api/users/" + id).then(r => r.json());\n}\n\n// Po migraci (TS)\nfunction getUser(id: string): Promise&lt;VeVitUser&gt; {\n  return api&lt;VeVitUser&gt;(`/api/users/${id}`);\n}</code></pre><h2>Časté problémy</h2><p>Třetí strany bez typů — nainstaluj <code>@types/</code> nebo vytvoř <code>.d.ts</code>. <code>any</code> jako dočasné řešení — označ <code>// TODO: otypovat</code>.</p>', 'lesson', 19, 15, 15),

(@kurs_id, 'Shrnutí + TypeScript roadmapa', '<h2>Co ses naučil</h2><p>V tomto kurzu jsi prošel od základních typů až po pokročilé vzory — generika, conditional types, Zod validaci, testování a migraci.</p><pre><code>// Shrnuti klicovych konceptu:\n// 1. Zakladni typy: string, number, boolean, unknown, never\n// 2. Interfaces &amp; Type aliases\n// 3. Generika pro znovupouzitelnost\n// 4. Utility &amp; Mapped &amp; Conditional Types\n// 5. Result&lt;T,E&gt; pro bezpecne chyby\n// 6. Zod pro runtime validaci\n// 7. Vitest pro testovani\n// 8. tsconfig.json a strict mode</code></pre><h2>TypeScript roadmapa — co dál?</h2><p><strong>Frameworky:</strong> React + TS, Next.js, Vue + TS, Svelte + TS.</p><p><strong>Nástroje:</strong> ESLint s TS pluginy, Prettier, tsc --watch.</p><p><strong>Pokročilé:</strong> Decorators, Type gymnastics, TS compiler API.</p><pre><code>// Dalsi kroky:\nconst roadmap = {\n  frameworks: ["React + TS", "Next.js", "Vue + TS"],\n  tools: ["ESLint @typescript-eslint", "Prettier", "tsc --watch"],\n  advanced: ["Decorators", "Compiler API", "Type challenges"],\n  practice: ["Exercism TypeScript track", "Type Challenges repo"]\n};\n\n// Zdroje:\n// www.typescriptlang.org/docs — oficialni dokumentace\n// github.com/type-challenges — typove priklady\n// totaltypescript.com — pokrocile tutorialy</code></pre>', 'lesson', 20, 15, 12);


-- ============================================================
-- ZÁVĚREČNÝ KVÍZ (sort_order 21)
-- ============================================================

INSERT INTO lessons (course_id, title, content, lesson_type, sort_order, xp_reward, duration_minutes) VALUES
(@kurs_id, 'Závěrečný kvíz — Celý TypeScript kurz', '<p>Závěrečný test pokrývající všechny lekce kurzu TypeScript.</p>', 'final_quiz', 21, 200, 30);

SET @qfin = LAST_INSERT_ID();

INSERT INTO quizzes (lesson_id, question, option_a, option_b, option_c, option_d, correct_answer, explanation, sort_order) VALUES
(@qfin, 'Jaký je rozdíl mezi any a unknown?', 'Žádný', 'any vypne kontrolu, unknown vyžaduje ověření typu', 'unknown je podtyp any', 'any je bezpečnější', 'b', 'unknown je type-safe alternativa k any — před použitím musíš ověřit typ pomocí typeof nebo instanceof.', 1),
(@qfin, 'Co dělá interface VeVitUser { avatar?: string; }?', 'Přidá povinný avatar', 'avatar je volitelný — může být undefined', 'avatar je readonly', 'avatar je vždy null', 'b', 'Otazník (?) označuje volitelnou vlastnost — hodnota může být undefined.', 2),
(@qfin, 'K čemu slouží generika v TypeScriptu?', 'K vytváření chyb', 'K psaní opakovaně použitelného kódu s různými typy', 'Ke zrychlení kompilace', 'K mazání typů', 'b', 'Generika umožňují definovat funkce a třídy, které pracují s různými typy při zachování typové bezpečnosti.', 3),
(@qfin, 'Co vypíše type Result = string extends number ? "yes" : "no"?', '"yes"', '"no"', 'Error', 'undefined', 'b', 'String nepatří do number — podmínka je false, výsledek je "no".', 4),
(@qfin, 'Co je Partial<Course>?', 'Course bez žádných vlastností', 'Course se všemi volitelnými vlastnostmi', 'Course jen s povinnými vlastnostmi', 'Course jen s readonly vlastnostmi', 'b', 'Partial<T> převede všechny vlastnosti typu T na volitelné (optional).', 5),
(@qfin, 'K čemu slouží .d.ts soubory?', 'K zápisu implementace funkcí', 'K deklaraci typů bez implementace', 'K testování', 'Ke konfiguraci kompilátoru', 'b', '.d.ts soubory deklarují typy (interfaces, funkce) bez implementace — popisují JS knihovny.', 6),
(@qfin, 'Co dělá Zod ve výrazu z.infer<typeof schema>?', 'Spustí schema', 'Odvodí TypeScript typ ze Zod schématu', 'Vytvoří nové schema', 'Validuje data', 'b', 'z.infer<typeof schema> extrahuje TypeScript typ z definice Zod schématu.', 7),
(@qfin, 'Jaký je správný typ pro catch (err: ...) v TypeScriptu?', 'any', 'Error', 'unknown', 'string', 'c', 'Od TS 4.4 je unknown doporučený typ pro chyby v catch — vyžaduje ověření typu před použitím.', 8),
(@qfin, 'Co je discriminated union v TypeScriptu?', 'Sjednocení dvou typů', 'Typ sjednocení se společnou vlastností pro rozlišení variant', 'Průnik typů', 'Mapped type', 'b', 'Discriminated union používá společnou vlastnost (např. status nebo ok) k rozlišení variant typu.', 9),
(@qfin, 'Co dělá tsc --strict?', 'Zapne pouze noImplicitAny', 'Zapne všechny striktní kontrolory typů najednou', 'Zpomalí kompilaci', 'Vypne typovou kontrolu', 'b', 'strict: true zapne strictNullChecks, noImplicitAny, noImplicitThis a další striktní kontroly.', 10);


-- ============================================================
-- Aktualizace počtu lekcí
-- ============================================================

UPDATE courses SET lesson_count = (SELECT COUNT(*) FROM lessons WHERE course_id = @kurs_id) WHERE id = @kurs_id;