-- PHP kurz — Kompletní kurz (20 lekcí + závěrečný kvíz)
-- MariaDB 10.4, phpMyAdmin style, no DELIMITER
-- Apostrofy escapovány jako ''

SET @kurs_id = (SELECT id FROM courses WHERE slug = 'php');

-- ============================================================
-- LEKCE 1–20
-- ============================================================

INSERT INTO lessons (course_id, title, content, lesson_type, sort_order, xp_reward, duration_minutes) VALUES
(@kurs_id, 'Úvod do PHP', '<h2>Co je PHP</h2><p>PHP je serverový skriptovací jazyk určený pro tvorbu dynamických webových aplikací. Běží na serveru — klient obdrží pouze výsledný HTML. Funguje na Apache i Nginx, podporuje MariaDB/MySQL nativně přes PDO.</p><pre><code>&lt;?php\necho "Ahoj, VeVit!";\n// PHP tag: &lt;?php ... ?&gt;\n// Zkrácený echo: &lt;?= $prom ?&gt;</code></pre><h2>Jak spustit PHP</h2><p>Na Wedos hostingu PHP běží automaticky — soubory s příponou <code>.php</code> zpracuje Apache. Lokálně můžeš použít vestavěný server:</p><pre><code>php -S localhost:8000</code></pre><p>Verzi ověříš příkazem <code>php -v</code>. Na Wedosu je k dispozici PHP 8.x přes .htaccess direktivy.</p>', 'lesson', 1, 15, 10),

(@kurs_id, 'Proměnné, typy, podmínky, cykly', '<h2>Proměnné a datové typy</h2><p>Proměnná začíná znakem <code>$</code>. PHP je dynamicky typované — typ se určuje za běhu. Základní typy: <code>string, int, float, bool, array, null</code>.</p><pre><code>&lt;?php\n$jmeno = "Karel";    // string\n$vek = 25;            // int\n$prumer = 4.8;        // float\n$aktivni = true;      // bool\n\necho gettype($vek);  // "integer"</code></pre><h2>Podmínky</h2><pre><code>if ($vek >= 18) {\n    echo "Dospělý";\n} elseif ($vek >= 15) {\n    echo "Střední škola";\n} else {\n    echo "Základní škola";\n}\n\n// Ternární operátor\n$status = $aktivni ? "online" : "offline";\n\n// Null coalescing\n$nick = $jmeno ?? "Anonym";</code></pre><h2>Cykly</h2><pre><code>// for\nfor ($i = 0; $i &lt; 5; $i++) {\n    echo $i;\n}\n\n// while\n$x = 0;\nwhile ($x &lt; 10) {\n    $x++;\n}\n\n// foreach — nejpoužívanější pro pole\n$barvy = ["červená", "zelená", "modrá"];\nforeach ($barvy as $barva) {\n    echo $barva;\n}\n\n// foreach s klíčem\n$osoba = ["jméno" =&gt; "Karel", "věk" =&gt; 25];\nforeach ($osoba as $k =&gt; $v) {\n    echo "$k: $v";\n}</code></pre>', 'lesson', 2, 15, 12),

(@kurs_id, 'Funkce, pole, string funkce', '<h2>Funkce</h2><p>Definice klíčovým slovem <code>function</code>. Podporuje typování parametrů a návratových hodnot (PHP 7+).</p><pre><code>&lt;?php\nfunction pozdrav(string $jmeno): string {\n    return "Ahoj, $jmeno!";\n}\n\necho pozdrav("Karel");  // Ahoj, Karel!\n\n// Výchozí hodnota\nfunction pripoj(string $host = "localhost"): void {\n    // ...\n}</code></pre><h2>Pole</h2><p>PHP pole jsou uspořádané mapy — mohou mít číselné i řetězcové klíče.</p><pre><code>// Indexované\n$ovoce = ["jablko", "banán", "hruška"];\n$ovoce[] = "švestka";  // přidá na konec\n\n// Asociativní\n$student = [\n    "jmeno" =&gt; "Karel",\n    "vek"   =&gt; 20,\n];\n\n// Užitečné funkce\ncount($ovoce);                // 4\nin_array("banán", $ovoce);    // true\narray_keys($student);         // ["jmeno", "vek"]\narray_merge($a, $b);          // sloučení\narray_unique([1,1,2,3]);     // [1,2,3]\narray_filter($pole, $callback); // filtrace</code></pre><h2>String funkce</h2><pre><code>$s = "Ahoj, VeVit!";\nstrlen($s);              // 13 (bytes)\nmb_strlen($s);            // 13 (chars, UTF-8 safe)\nstrtolower($s);           // "ahoj, vevit!"\nstrtoupper($s);           // "AHOJ, VEVIT!"\nstr_replace("VeVit", "světe", $s);\nexplode(",", $s);         // ["Ahoj", " VeVit!"]\nimplode(" - ", $arr);     // spojení\ntrim("  ahoj  ");         // "ahoj"\nhtmlspecialchars($s);      // escapování HTML\nstr_contains($s, "VeVit"); // true (PHP 8+)\nstr_starts_with($s, "Ahoj"); // true</code></pre>', 'lesson', 3, 15, 12),

(@kurs_id, 'PHP PDO — připojení k MariaDB, prepared statements', '<h2>PDO připojení</h2><p>PDO (PHP Data Objects) je abstraktní vrstva pro přístup k databázím. Vždy používej PDO místo zastaralého mysql/mysqli — PDO podporuje prepared statements a více databází.</p><pre><code>&lt;?php\ntry {\n    $pdo = new PDO(\n        "mysql:host=localhost;dbname=vevit_db;charset=utf8",\n        "uzivatel",\n        "heslo",\n        [\n            PDO::ATTR_ERRMODE            =&gt; PDO::ERRMODE_EXCEPTION,\n            PDO::ATTR_DEFAULT_FETCH_MODE =&gt; PDO::FETCH_ASSOC,\n            PDO::ATTR_EMULATE_PREPARES   =&gt; false,\n        ]\n    );\n} catch (PDOException $e) {\n    error_log("DB chyba: " . $e-&gt;getMessage());\n    die("Chyba připojení k databázi.");\n}</code></pre><h2>Prepared statements</h2><p>Nikdy nevkládej data přímo do SQL — vždy používej prepared statements proti SQL injekci.</p><pre><code>// Vložení\n$stmt = $pdo-&gt;prepare("INSERT INTO users (jmeno, email) VALUES (:jmeno, :email)");\n$stmt-&gt;execute(["jmeno" =&gt; $jmeno, "email" =&gt; $email]);\n$novyId = $pdo-&gt;lastInsertId();\n\n// Výběr\n$stmt = $pdo-&gt;prepare("SELECT * FROM users WHERE id = :id");\n$stmt-&gt;execute(["id" =&gt; $id]);\n$user = $stmt-&gt;fetch();  // asociativní pole nebo false\n\n// Výběr více řádků\n$stmt = $pdo-&gt;prepare("SELECT * FROM users WHERE aktivni = :a ORDER BY id DESC");\n$stmt-&gt;execute(["a" =&gt; 1]);\n$users = $stmt-&gt;fetchAll();\n\n// Smazání\n$stmt = $pdo-&gt;prepare("DELETE FROM users WHERE id = :id LIMIT 1");\n$stmt-&gt;execute(["id" =&gt; $id]);</code></pre>', 'lesson', 4, 15, 15),

(@kurs_id, 'PHP Sessions a VeVit cookie autentizace', '<h2>Session v PHP</h2><p>Session ukládá data na serveru, klient dostane jen ID v cookie <code>PHPSESSID</code>. Vždy spustí session na začátku skriptu.</p><pre><code>&lt;?php\nsession_start();\n\n// Zápis do session\n$_SESSION["user_id"] = 42;\n$_SESSION["jmeno"] = "Karel";\n\n// Čtení\n$uid = $_SESSION["user_id"] ?? null;\n\n// Zrušení session\nsession_unset();\nsession_destroy();</code></pre><h2>VeVit cookie autentizace</h2><p>Pro autentizaci na .vevit.fun používáme cookie <code>vevit_auth</code> s URL-encoded JSON. Cookie musí mít nastavený <code>domain=.vevit.fun</code> pro sdílení napříč subdoménami.</p><pre><code>&lt;?php\nfunction setVevitAuth(int $userId, string $role, int $days = 30): void {\n    $data = [\n        "uid"  =&gt; $userId,\n        "role" =&gt; $role,\n        "exp"  =&gt; time() + $days * 86400,\n    ];\n    $payload = base64_encode(json_encode($data));\n    $sig = hash_hmac("sha256", $payload, VEVIT_SECRET);\n    $cookie = $sig . "." . $payload;\n    setcookie(\n        "vevit_auth",\n        urlencode($cookie),\n        [\n            "expires"  =&gt; time() + $days * 86400,\n            "path"     =&gt; "/",\n            "domain"   =&gt; ".vevit.fun",\n            "secure"   =&gt; true,\n            "httponly" =&gt; true,\n            "samesite" =&gt; "Lax",\n        ]\n    );\n}\n\nfunction getVevitAuth(): ?array {\n    if (!isset($_COOKIE["vevit_auth"])) return null;\n    $raw = urldecode($_COOKIE["vevit_auth"]);\n    $parts = explode(".", $raw, 2);\n    if (count($parts) !== 2) return null;\n    [$sig, $payload] = $parts;\n    $expected = hash_hmac("sha256", $payload, VEVIT_SECRET);\n    if (!hash_equals($expected, $sig)) return null;\n    $data = json_decode(base64_decode($payload), true);\n    if (!$data || ($data["exp"] ?? 0) &lt; time()) return null;\n    return $data;\n}</code></pre>', 'lesson', 5, 15, 15),

(@kurs_id, 'OOP — třídy, konstruktory, metody, properties', '<h2>Třídy v PHP</h2><p>Třída definuje vlastnosti (properties) a metody. Konstruktor <code>__construct</code> se volá při vytvoření instance. Viditelnost: <code>public, protected, private</code>.</p><pre><code>&lt;?php\nclass User {\n    public string $jmeno;\n    protected int $vek;\n    private ?string $email = null;\n\n    public function __construct(string $jmeno, int $vek) {\n        $this-&gt;jmeno = $jmeno;\n        $this-&gt;vek = $vek;\n    }\n\n    public function predstavSe(): string {\n        return "Jsem {$this-&gt;jmeno}, věk {$this-&gt;vek}.";\n    }\n\n    public function setEmail(string $email): void {\n        if (!filter_var($email, FILTER_VALIDATE_EMAIL)) {\n            throw new InvalidArgumentException("Neplatný email");\n        }\n        $this-&gt;email = $email;\n    }\n\n    public function getEmail(): ?string {\n        return $this-&gt;email;\n    }\n}\n\n$user = new User("Karel", 25);\necho $user-&gt;predstavSe();\n$user-&gt;setEmail("karel@vevit.fun");</code></pre><h2>Typové properties (PHP 7.4+)</h2><pre><code>class Config {\n    public string $nazev = "VeVit";\n    public int $verze = 1;\n    public bool $debug = false;\n    public ?string $popis = null;  // nullable\n}</code></pre>', 'lesson', 6, 15, 15),

(@kurs_id, 'OOP — dědičnost, interfaces, abstraktní třídy', '<h2>Dědičnost</h2><p>Třída může dědit od jedné rodičovské třídy pomocí <code>extends</code>. <code>parent::</code> volá rodičovskou metodu. Přepisování metod pomocí <code>override</code> (PHP nevyžaduje klíčové slovo, ale doporučuje atribut <code>#[Override]</code> v PHP 8.3+).</p><pre><code>&lt;?php\nclass Zvire {\n    public function __construct(protected string $zvuk = "...") {}\n\n    public function udelejZvuk(): string {\n        return $this-&gt;zvuk;\n    }\n}\n\nclass Pes extends Zvire {\n    public function __construct() {\n        parent::__construct("Haf!");\n    }\n}\n\n$pes = new Pes();\necho $pes-&gt;udelejZvuk();  // Haf!</code></pre><h2>Interfaces</h2><pre><code>interface Serializovatelny {\n    public function toArray(): array;\n    public function toJson(): string;\n}\n\nclass User implements Serializovatelny {\n    public function __construct(private string $jmeno) {}\n\n    public function toArray(): array {\n        return ["jmeno" =&gt; $this-&gt;jmeno];\n    }\n\n    public function toJson(): string {\n        return json_encode($this-&gt;toArray(), JSON_UNESCAPED_UNICODE);\n    }\n}</code></pre><h2>Abstraktní třídy</h2><pre><code>abstract class Zaklad {\n    abstract public function spustit(): void;\n\n    public function log(string $msg): void {\n        error_log("[Zaklad] $msg");\n    }\n}\n\nclass Aplikace extends Zaklad {\n    public function spustit(): void {\n        $this-&gt;log("Aplikace spuštěna");\n    }\n}</code></pre>', 'lesson', 7, 15, 15),

(@kurs_id, 'PHP traits', '<h2>Co jsou traits</h2><p>Traits umožňují sdílet kód mezi třídami bez dědičnosti. Podobné mixinům — třída může použít více traits pomocí <code>use</code>.</p><pre><code>&lt;?php\ntrait Casove {\n    protected ?int $createdAt = null;\n    protected ?int $updatedAt = null;\n\n    public function nastavCas(): void {\n        $now = time();\n        if ($this-&gt;createdAt === null) {\n            $this-&gt;createdAt = $now;\n        }\n        $this-&gt;updatedAt = $now;\n    }\n\n    public function getVek(): string {\n        if ($this-&gt;createdAt === null) return "nezaloženo";\n        $dny = floor((time() - $this-&gt;createdAt) / 86400);\n        return "{$dny} dní";\n    }\n}\n\ntrait JsonVystup {\n    public function toJson(): string {\n        return json_encode(get_object_vars($this), JSON_UNESCAPED_UNICODE);\n    }\n}\n\nclass Clanek {\n    use Casove, JsonVystup;\n\n    public function __construct(public string $titulek) {\n        $this-&gt;nastavCas();\n    }\n}\n\n$c = new Clanek("PHP traits");\necho $c-&gt;toJson();\necho $c-&gt;getVek();</code></pre><h2>Konflikty traits</h2><pre><code>trait A {\n    public function run() { echo "A"; }\n}\ntrait B {\n    public function run() { echo "B"; }\n}\n\nclass App {\n    use A, B {\n        B::run insteadof A;  // priorita\n        A::run as runA;      // alias\n    }\n}</code></pre>', 'lesson', 8, 15, 13),

(@kurs_id, 'PHP namespace a autoloading (bez Composeru)', '<h2>Namespaces</h2><p>Namespace seskupuje třídy a zabranuje kolizím jmen. Deklaruje se na začátku souboru — jeden soubor = jeden namespace.</p><pre><code>&lt;?php\nnamespace Vevit\\Database;\n\nclass Spojeni {\n    public static function pripoj(): \\PDO {\n        return new \\PDO(\n            "mysql:host=localhost;dbname=vevit_db;charset=utf8",\n            "uzivatel", "heslo"\n        );\n    }\n}\n\n// Použití z jiného souboru\nuse Vevit\\Database\\Spojeni;\n$pdo = Spojeni::pripoj();</code></pre><h2>Autoloading bez Composeru</h2><p>Na Wedosu bez Composeru použijeme jednoduchý autoloader přes <code>spl_autoload_register</code>. Konvence: název třídy odpovídá cestě k souboru.</p><pre><code>&lt;?php\n// autoload.php\nspl_autoload_register(function (string $class): void {\n    // Vevit\\Database\\Spojeni -&gt; classes/Vevit/Database/Spojeni.php\n    $prefix = "Vevit\\\\";\n    $baseDir = __DIR__ . "/classes/";\n\n    if (strpos($class, $prefix) !== 0) return;\n\n    $relative = substr($class, strlen($prefix));\n    $file = $baseDir . str_replace("\\\\", "/", $relative) . ".php";\n\n    if (file_exists($file)) {\n        require_once $file;\n    }\n});\n\n// Použití — třída se načte automaticky\nrequire_once __DIR__ . "/autoload.php";\nuse Vevit\\Database\\Spojeni;\n$pdo = Spojeni::pripoj();</code></pre>', 'lesson', 9, 15, 15),

(@kurs_id, 'Výjimky a error handling — custom Exception hierarchy', '<h2>Výjimky v PHP</h2><p><code>try</code> obsahuje rizikový kód, <code>catch</code> zachytí konkrétní výjimku, <code>finally</code> se provede vždy. Vždy loguj chyby, uživateli zobraz obecnou zprávu.</p><pre><code>&lt;?php\ntry {\n    $pdo = new PDO("mysql:host=localhost;dbname=test;charset=utf8", "root", "");\n    $pdo-&gt;setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION);\n} catch (PDOException $e) {\n    error_log("DB: " . $e-&gt;getMessage());\n    die("Chyba připojení.");\n} finally {\n    // vždy se provede\n}</code></pre><h2>Vlastní Exception hierarchie</h2><pre><code>&lt;?php\nnamespace Vevit\\Exception;\n\nclass VevitException extends \\Exception {}\n\nclass NotFoundException extends VevitException {}\nclass UnauthorizedException extends VevitException {}\nclass ValidationException extends VevitException {\n    public function __construct(\n        string $message,\n        private array $errors = [],\n        int $code = 422\n    ) {\n        parent::__construct($message, $code);\n    }\n\n    public function getErrors(): array {\n        return $this-&gt;errors;\n    }\n}\n\n// Použití\ntry {\n    throw new ValidationException("Neplatná data", [\n        "email" =&gt; "Povinné pole",\n        "vek"   =&gt; "Musí být kladné číslo",\n    ]);\n} catch (ValidationException $e) {\n    http_response_code($e-&gt;getCode());\n    echo json_encode(["error" =&gt; $e-&gt;getMessage(), "details" =&gt; $e-&gt;getErrors()], JSON_UNESCAPED_UNICODE);\n}</code></pre><h2>Error reporting</h2><pre><code>// Produkce — skrýt chyby, logovat\nerror_reporting(E_ALL);\nini_set("display_errors", "0");\nini_set("log_errors", "1");\nini_set("error_log", __DIR__ . "/../logs/php_error.log");</code></pre>', 'lesson', 10, 15, 15),

(@kurs_id, 'PHP REST API — JSON responses, http_response_code, CORS', '<h2>REST API v PHP</h2><p>Bez frameworku — čistý PHP s JSON vstupy/výstupy. HTTP metody: GET, POST, PUT, DELETE. CORS hlavičky pro .vevit.fun domény.</p><pre><code>&lt;?php\nheader("Content-Type: application/json; charset=utf-8");\nheader("Access-Control-Allow-Origin: https://edu.vevit.fun");\nheader("Access-Control-Allow-Methods: GET, POST, PUT, DELETE, OPTIONS");\nheader("Access-Control-Allow-Headers: Content-Type, Authorization");\nheader("Access-Control-Allow-Credentials: true");\n\n// Preflight OPTIONS\nif ($_SERVER["REQUEST_METHOD"] === "OPTIONS") {\n    http_response_code(204);\n    exit;\n}\n\nfunction jsonResponse(array $data, int $code = 200): void {\n    http_response_code($code);\n    echo json_encode($data, JSON_UNESCAPED_UNICODE);\n    exit;\n}\n\nfunction jsonInput(): array {\n    $raw = file_get_contents("php://input");\n    $data = json_decode($raw, true);\n    return is_array($data) ? $data : [];\n}\n\n$method = $_SERVER["REQUEST_METHOD"];\n$uri = parse_url($_SERVER["REQUEST_URI"], PHP_URL_PATH);\n\n// Routing\nif ($method === "GET" &amp;&amp; $uri === "/api/users") {\n    $stmt = $pdo-&gt;query("SELECT id, jmeno FROM users ORDER BY id");\n    jsonResponse($stmt-&gt;fetchAll());\n}\n\nif ($method === "POST" &amp;&amp; $uri === "/api/users") {\n    $data = jsonInput();\n    if (empty($data["jmeno"])) {\n        jsonResponse(["error" =&gt; "Jméno je povinné"], 422);\n    }\n    $stmt = $pdo-&gt;prepare("INSERT INTO users (jmeno) VALUES (:jmeno)");\n    $stmt-&gt;execute(["jmeno" =&gt; $data["jmeno"]]);\n    jsonResponse(["id" =&gt; $pdo-&gt;lastInsertId(), "jmeno" =&gt; $data["jmeno"]], 201);\n}</code></pre>', 'lesson', 11, 15, 15),

(@kurs_id, 'Validace vstupu — filter_var, preg_match, vlastní validátor', '<h2>filter_var</h2><p>Vestavěné filtry pro běžné typy. Vždy validuj vstup od uživatele před zpracováním.</p><pre><code>&lt;?php\n// Email\nif (!filter_var($email, FILTER_VALIDATE_EMAIL)) {\n    $chyby[] = "Neplatný email";\n}\n\n// URL\n$url = filter_var($input, FILTER_VALIDATE_URL);\n\n// Celé číslo\n$int = filter_var($input, FILTER_VALIDATE_INT, [\n    "options" =&gt; ["min_range" =&gt; 1, "max_range" =&gt; 9999]\n]);\n\n// Sanitizace\n$clean = filter_var($input, FILTER_SANITIZE_SPECIAL_CHARS);\n$clean = filter_var($input, FILTER_SANITIZE_EMAIL);</code></pre><h2>preg_match — regulární výrazy</h2><pre><code>// Uživatelské jméno — 3-20 alfanumerických znaků\nif (!preg_match("/^[a-zA-Z0-9_]{3,20}$/", $jmeno)) {\n    $chyby[] = "Jméno: 3-20 znaků, písmena, číslice, podtržítko";\n}\n\n// Heslo — min 8 znaků, velké, malé, číslice\nif (!preg_match("/^(?=.*[a-z])(?=.*[A-Z])(?=.*\\d).{8,}$/", $heslo)) {\n    $chyby[] = "Heslo: min 8 znaků, velké i malé písmeno, číslice";\n}\n\n// České telefonní číslo\nif (!preg_match("/^(\\+420)?\\s?\\d{3}\\s?\\d{3}\\s?\\d{3}$/", $tel)) {\n    $chyby[] = "Neplatné telefonní číslo";\n}</code></pre><h2>Vlastní validátor</h2><pre><code>class Validator {\n    private array $errors = [];\n\n    public function required(string $field, mixed $value): self {\n        if (empty($value) &amp;&amp; $value !== "0" &amp;&amp; $value !== 0) {\n            $this-&gt;errors[] = "$field je povinné";\n        }\n        return $this;\n    }\n\n    public function minLength(string $field, string $val, int $min): self {\n        if (mb_strlen($val) &lt; $min) {\n            $this-&gt;errors[] = "$field musí mít min $min znaků";\n        }\n        return $this;\n    }\n\n    public function isValid(): bool {\n        return empty($this-&gt;errors);\n    }\n\n    public function getErrors(): array {\n        return $this-&gt;errors;\n    }\n}\n\n// Použití\n$v = new Validator();\n$v-&gt;required("email", $email)\n   -&gt;minLength("heslo", $heslo, 8);\nif (!$v-&gt;isValid()) {\n    jsonResponse(["errors" =&gt; $v-&gt;getErrors()], 422);\n}</code></pre>', 'lesson', 12, 15, 15),

(@kurs_id, 'Soubory — čtení, zápis, bezpečný upload', '<h2>Čtení a zápis souborů</h2><p><code>file_get_contents</code> čte, <code>file_put_contents</code> zapisuje. Pro bezpečnost vždy kontroluj cesty a oprávnění.</p><pre><code>&lt;?php\n// Čtení\n$obsah = file_get_contents("/path/to/file.txt");\n\n// Zápis\nfile_put_contents("/path/to/out.txt", $data, LOCK_EX);\n\n// Připojení na konec\nfile_put_contents("/path/to/log.txt", $line . "\\n", FILE_APPEND | LOCK_EX);\n\n// Kontrola existence\nif (file_exists($path)) { /* ... */ }\n\n// Adresáře\nif (!is_dir($dir)) {\n    mkdir($dir, 0755, true);  // recursive\n}</code></pre><h2>Bezpečný upload souborů</h2><pre><code>&lt;?php\nfunction bezpecnyUpload(array $file, string $destDir): ?string {\n    $povolene = ["image/jpeg", "image/png", "image/gif", "application/pdf"];\n    $maxVelikost = 5 * 1024 * 1024;  // 5 MB\n\n    if ($file["error"] !== UPLOAD_ERR_OK) return null;\n    if ($file["size"] &gt; $maxVelikost) return null;\n\n    // Ověření MIME typu — NEDŮVĚŘUJ $_FILES["type"]!\n    $finfo = finfo_open(FILEINFO_MIME_TYPE);\n    $mime = finfo_file($finfo, $file["tmp_name"]);\n    finfo_close($finfo);\n\n    if (!in_array($mime, $povolene, true)) return null;\n\n    // Bezpečné jméno souboru\n    $ext = pathinfo($file["name"], PATHINFO_EXTENSION);\n    $nazev = bin2hex(random_bytes(16)) . "." . $ext;\n    $cesta = rtrim($destDir, "/") . "/" . $nazev;\n\n    if (move_uploaded_file($file["tmp_name"], $cesta)) {\n        return $nazev;\n    }\n    return null;\n}\n\n// Použití\n$nazev = bezpecnyUpload($_FILES["avatar"], __DIR__ . "/../uploads");\nif ($nazev === null) {\n    jsonResponse(["error" =&gt; "Neplatný soubor"], 422);\n}</code></pre>', 'lesson', 13, 15, 15),

(@kurs_id, 'PHP email — mail(), reset hesla token', '<h2>Odeslání emailu</h2><p>Funkce <code>mail()</code> funguje na Wedosu bez problémů. Pro produkci doporučujeme nastavit správné hlavičky s kódováním UTF-8.</p><pre><code>&lt;?php\nfunction posliEmail(string $komu, string $predmet, string $telo): bool {\n    $hlavicky  = "From: noreply@vevit.fun\\r\\n";\n    $hlavicky .= "Reply-To: podpora@vevit.fun\\r\\n";\n    $hlavicky .= "MIME-Version: 1.0\\r\\n";\n    $hlavicky .= "Content-Type: text/plain; charset=utf-8\\r\\n";\n    return mail($komu, $predmet, $telo, $hlavicky);\n}</code></pre><h2>Reset hesla s tokenem</h2><pre><code>&lt;?php\nfunction vytvorResetToken(PDO $pdo, int $userId): string {\n    $token = bin2hex(random_bytes(32));\n    $hash = hash("sha256", $token);\n    $exp = date("Y-m-d H:i:s", time() + 3600);  // 1 hodina\n\n    $stmt = $pdo-&gt;prepare(\n        "INSERT INTO password_resets (user_id, token_hash, expires_at)\\n         VALUES (:uid, :hash, :exp)"\n    );\n    $stmt-&gt;execute(["uid" =&gt; $userId, "hash" =&gt; $hash, "exp" =&gt; $exp]);\n    return $token;\n}\n\nfunction odesliResetEmail(string $email, string $token): bool {\n    $url = "https://edu.vevit.fun/reset?token=" . urlencode($token);\n    $telo = "Dobrý den,\\n\\nPro reset hesla klikněte na:\\n$url\\n\\nPlatnost: 1 hodina.";\n    return posliEmail($email, "VeVit — Reset hesla", $telo);\n}\n\n// Verifikace tokenu\nfunction overResetToken(PDO $pdo, string $token): ?int {\n    $hash = hash("sha256", $token);\n    $stmt = $pdo-&gt;prepare(\n        "SELECT user_id FROM password_resets\\n         WHERE token_hash = :hash AND expires_at &gt; NOW() AND used = 0"  \n    );\n    $stmt-&gt;execute(["hash" =&gt; $hash]);\n    $row = $stmt-&gt;fetch();\n    return $row ? (int) $row["user_id"] : null;\n}</code></pre>', 'lesson', 14, 15, 15),

(@kurs_id, 'Autentizační guard — vyzadujPrihlaseni(), vyzadujRoli()', '<h2>Autentizační guard</h2><p>Guard funkce chrání stránky a API endpointy. Pokud uživatel není přihlášen nebo nemá požadovanou roli, přesměruj nebo vrať 401/403.</p><pre><code>&lt;?php\nrequire_once __DIR__ . "/auth.php";  // getVevitAuth()\n\nfunction vyzadujPrihlaseni(): array {\n    $auth = getVevitAuth();\n    if ($auth === null) {\n        // Pro API\n        if (str_starts_with($_SERVER["REQUEST_URI"], "/api/")) {\n            http_response_code(401);\n            header("Content-Type: application/json");\n            echo json_encode(["error" =&gt; "Přihlášení vyžadováno"]);\n            exit;\n        }\n        // Pro web\n        header("Location: /login?redirect=" . urlencode($_SERVER["REQUEST_URI"]));\n        exit;\n    }\n    // Ověření expirace z cookie\n    if (($auth["exp"] ?? 0) &lt; time()) {\n        setcookie("vevit_auth", "", time() - 3600, "/", ".vevit.fun", true, true);\n        header("Location: /login");\n        exit;\n    }\n    return $auth;\n}\n\nfunction vyzadujRoli(string $role): array {\n    $auth = vyzadujPrihlaseni();\n    if (($auth["role"] ?? "") !== $role) {\n        if (str_starts_with($_SERVER["REQUEST_URI"], "/api/")) {\n            http_response_code(403);\n            header("Content-Type: application/json");\n            echo json_encode(["error" =&gt; "Nedostatečná oprávnění"]);\n            exit;\n        }\n        http_response_code(403);\n        include __DIR__ . "/../views/403.php";\n        exit;\n    }\n    return $auth;\n}\n\n// Použití na začátku chráněné stránky\n$auth = vyzadujPrihlaseni();\n$userId = $auth["uid"];\n\n// Pouze pro admina\n$admin = vyzadujRoli("admin");</code></pre>', 'lesson', 15, 15, 15),

(@kurs_id, 'VeVit XP systém v PHP — pridejXP() s transakcí', '<h2>Přidávání XP s transakcí</h2><p>XP musí být přidáno atomicky — transakce zaručí konzistenci. Po transakci aktualizuj i cache.</p><pre><code>&lt;?php\nnamespace Vevit\\Xp;\n\nuse PDO;\n\nclass XpManager {\n    public function __construct(private PDO $pdo) {}\n\n    public function pridejXP(int $userId, int $amount, string $reason): bool {\n        if ($amount &lt;= 0) return false;\n\n        try {\n            $this-&gt;pdo-&gt;beginTransaction();\n\n            // Přidat XP uživateli\n            $stmt = $this-&gt;pdo-&gt;prepare(\n                "UPDATE users SET xp = xp + :amount WHERE id = :uid"\n            );\n            $stmt-&gt;execute(["amount" =&gt; $amount, "uid" =&gt; $userId]);\n\n            // Záznam do historie\n            $stmt = $this-&gt;pdo-&gt;prepare(\n                "INSERT INTO xp_log (user_id, amount, reason, created_at)\\n                 VALUES (:uid, :amount, :reason, NOW())"\n            );\n            $stmt-&gt;execute([\n                "uid"    =&gt; $userId,\n                "amount" =&gt; $amount,\n                "reason" =&gt; $reason,\n            ]);\n\n            // Kontrola level-upu\n            $stmt = $this-&gt;pdo-&gt;prepare("SELECT xp FROM users WHERE id = :uid");\n            $stmt-&gt;execute(["uid" =&gt; $userId]);\n            $newXp = (int) $stmt-&gt;fetchColumn();\n\n            $this-&gt;pdo-&gt;commit();\n\n            // Level-up kontrola po commitu\n            $this-&gt;checkLevelUp($userId, $newXp);\n\n            return true;\n        } catch (\\PDOException $e) {\n            $this-&gt;pdo-&gt;rollBack();\n            error_log("XP chyba: " . $e-&gt;getMessage());\n            return false;\n        }\n    }\n\n    private function checkLevelUp(int $uid, int $xp): void {\n        $newLevel = (int) floor($xp / 100) + 1;  // 100 XP = 1 level\n        $stmt = $this-&gt;pdo-&gt;prepare(\n            "UPDATE users SET level = :lvl WHERE id = :uid AND level &lt; :lvl"\n        );\n        $stmt-&gt;execute(["lvl" =&gt; $newLevel, "uid" =&gt; $uid]);\n    }\n}</code></pre>', 'lesson', 16, 15, 15),

(@kurs_id, 'Caching — file cache bez externích knihoven', '<h2>Jednoduchá file cache</h2><p>Na Wedosu bez Redis/Memcached použijeme souborovou cache. Každý záznam = jeden soubor s TTL metadaty.</p><pre><code>&lt;?php\nclass FileCache {\n    private string $dir;\n\n    public function __construct(string $dir, private int $defaultTtl = 3600) {\n        $this-&gt;dir = rtrim($dir, "/");\n        if (!is_dir($this-&gt;dir)) {\n            mkdir($this-&gt;dir, 0755, true);\n        }\n    }\n\n    public function get(string $key): mixed {\n        $file = $this-&gt;path($key);\n        if (!file_exists($file)) return null;\n\n        $data = unserialize(file_get_contents($file));\n        if ($data === false || !is_array($data)) return null;\n\n        if ($data["expires"] &lt; time()) {\n            @unlink($file);\n            return null;\n        }\n        return $data["value"];\n    }\n\n    public function set(string $key, mixed $value, ?int $ttl = null): void {\n        $ttl ??= $this-&gt;defaultTtl;\n        $data = [\n            "value"   =&gt; $value,\n            "expires" =&gt; time() + $ttl,\n        ];\n        file_put_contents($this-&gt;path($key), serialize($data), LOCK_EX);\n    }\n\n    public function delete(string $key): void {\n        $file = $this-&gt;path($key);\n        if (file_exists($file)) @unlink($file);\n    }\n\n    public function clear(): void {\n        foreach (glob($this-&gt;dir . "/*.cache") as $f) {\n            @unlink($f);\n        }\n    }\n\n    private function path(string $key): string {\n        // Bezpečný název souboru\n        $safe = preg_replace("/[^a-zA-Z0-9_\\-]/", "_", $key);\n        return $this-&gt;dir . "/" . $safe . ".cache";\n    }\n}\n\n// Použití\n$cache = new FileCache(__DIR__ . "/../cache", 600);\n\n$users = $cache-&gt;get("users_all");\nif ($users === null) {\n    $users = $pdo-&gt;query("SELECT * FROM users")-&gt;fetchAll();\n    $cache-&gt;set("users_all", $users, 300);\n}</code></pre>', 'lesson', 17, 15, 15),

(@kurs_id, 'PHP CLI skripty', '<h2>PHP z příkazové řádky</h2><p>PHP lze spouštět i jako CLI skript — ideální pro cron úlohy, migrace, importy dat. Na Wedosu můžeš spustit PHP cron přes admin panel.</p><pre><code>&lt;?php\n// Skript: scripts/cleanup.php\n// Spuštění: php scripts/cleanup.php\n\nif (php_sapi_name() !== "cli") {\n    die("Tento skript lze spustit pouze z CLI.");\n}\n\n// Argumenty příkazové řádky\n$opts = getopt("", ["days::", "dry-run"]);\n$days = (int) ($opts["days"] ?? 30);\n$dryRun = isset($opts["dry-run"]);\n\necho "Mazání záznamů starších než $days dní" . PHP_EOL;\n\n$stmt = $pdo-&gt;prepare("DELETE FROM sessions WHERE last_activity &lt; DATE_SUB(NOW(), INTERVAL :days DAY)");\n\nif ($dryRun) {\n    $count = $pdo-&gt;prepare("SELECT COUNT(*) FROM sessions WHERE last_activity &lt; DATE_SUB(NOW(), INTERVAL :days DAY)");\n    $count-&gt;execute(["days" =&gt; $days]);\n    echo "[DRY-RUN] Smazáno by: " . $count-&gt;fetchColumn() . PHP_EOL;\n} else {\n    $stmt-&gt;execute(["days" =&gt; $days]);\n    echo "Smazáno: " . $stmt-&gt;rowCount() . " záznamů." . PHP_EOL;\n}</code></pre><h2>Cron na Wedosu</h2><pre><code># Wedos cron (přes admin panel)\n# Každý den v 3:00\n0 3 * * * /usr/bin/php8.2 /home/www/vevit.fun/scripts/cleanup.php --days=30\n\n# Každou hodinu — XP recalculate\n0 * * * * /usr/bin/php8.2 /home/www/vevit.fun/scripts/xp_recalc.php</code></pre>', 'lesson', 18, 15, 13),

(@kurs_id, 'Bezpečnost — XSS, CSRF tokeny, hlavičky, CORS', '<h2>XSS ochrana — htmlspecialchars</h2><p>Nikdy nevypisuj uživatelský vstup bez escapování. <code>htmlspecialchars</code> převodí nebezpečné znaky na entity.</p><pre><code>&lt;?php\n// VŽDY escapuj výstup\necho htmlspecialchars($userInput, ENT_QUOTES, "UTF-8");\n\n// Nikdy ne:\necho $userInput;  // XSS zranitelnost!\n\n// Pomocná funkce\nfunction e(string $s): string {\n    return htmlspecialchars($s, ENT_QUOTES | ENT_HTML5, "UTF-8");\n}\n\n// Použití v šabloně\n?&gt;&lt;h1&gt;&lt;?= e($clanek["titulek"]) ?&gt;&lt;/h1&gt;\n&lt;p&gt;&lt;?= e($clanek["obsah"]) ?&gt;&lt;/p&gt;</code></pre><h2>CSRF tokeny</h2><pre><code>&lt;?php\nfunction csrfToken(): string {\n    if (empty($_SESSION["csrf_token"])) {\n        $_SESSION["csrf_token"] = bin2hex(random_bytes(32));\n    }\n    return $_SESSION["csrf_token"];\n}\n\nfunction overCsrf(): bool {\n    $token = $_POST["csrf_token"] ?? $_SERVER["HTTP_X_CSRF_TOKEN"] ?? "";\n    return hash_equals($_SESSION["csrf_token"] ?? "", $token);\n}\n\n// Ve formuláři\n// &lt;input type="hidden" name="csrf_token" value="&lt;?= csrfToken() ?&gt;"&gt;\n\n// V API handleru\nif (!overCsrf()) {\n    jsonResponse(["error" =&gt; "Neplatný CSRF token"], 403);\n}</code></pre><h2>Bezpečnostní hlavičky pro .vevit.fun</h2><pre><code>&lt;?php\n// Bezpečnostní hlavičky — vložit do každého response\nheader("X-Content-Type-Options: nosniff");\nheader("X-Frame-Options: SAMEORIGIN");\nheader("X-XSS-Protection: 1; mode=block");\nheader("Referrer-Policy: strict-origin-when-cross-origin");\nheader("Permissions-Policy: camera=(), microphone=(), geolocation=()");\nheader("Content-Security-Policy: default-src ''self''; script-src ''self'' https://edu.vevit.fun; style-src ''self'' ''unsafe-inline''; img-src ''self'' data: https:; font-src ''self''; connect-src ''self'' https://*.vevit.fun; frame-ancestors ''none''");\nheader("Strict-Transport-Security: max-age=31536000; includeSubDomains");\n\n// CORS pro *.vevit.fun\n$origin = $_SERVER["HTTP_ORIGIN"] ?? "";\nif (preg_match("/^https:\\/\\/[a-z0-9-]+\\.vevit\\.fun$/", $origin)) {\n    header("Access-Control-Allow-Origin: $origin");\n    header("Access-Control-Allow-Credentials: true");\n    header("Access-Control-Allow-Methods: GET, POST, PUT, DELETE, OPTIONS");\n    header("Access-Control-Allow-Headers: Content-Type, Authorization, X-CSRF-Token");\n}</code></pre>', 'lesson', 19, 15, 15),

(@kurs_id, '.htaccess pro VeVit — SPA fallback, ochrana souborů, API routing', '<h2>SPA fallback</h2><p>Single Page Application potřebuje přesměrovat všechny neexistující cesty na <code>index.html</code>, kromě reálných souborů a API endpointů.</p><pre><code># .htaccess — Wedos Apache 2.4\nRewriteEngine On\n\n# HTTPS vynucení\nRewriteCond %{HTTPS} off\nRewriteRule ^(.*)$ https://%{HTTP_HOST}/$1 [R=301,L]\n\n# SPA fallback — existující soubory a adresáře ignoruj\nRewriteCond %{REQUEST_FILENAME} !-f\nRewriteCond %{REQUEST_FILENAME} !-d\n# API pošli na PHP backend\nRewriteRule ^api/(.*)$ api/index.php [QSA,L]\n# Vše ostatní na SPA\nRewriteRule ^(.*)$ index.html [QSA,L]</code></pre><h2>Ochrana souborů</h2><pre><code># Zákaz přístupu k citlivým souborům\n&lt;FilesMatch "\\.(env|sql|log|yml|yaml|json|lock|md|sh|bak|orig)$"&gt;\n    Require all denied\n&lt;/FilesMatch&gt;\n\n# Zákaz přístupu ke skrytým adresářům\nRedirectMatch 404 /\\.\n\n# Ochrana uploads — pouze pro čtení, žádné PHP\n&lt;Directory "*/uploads/*"&gt;\n    php_flag engine off\n    &lt;FilesMatch "\\.(php|phtml|php\\d)$"&gt;\n        Require all denied\n    &lt;/FilesMatch&gt;\n&lt;/Directory&gt;\n\n# Zákaz directory listing\nOptions -Indexes</code></pre><h2>API routing a PHP verze</h2><pre><code># Nastavení PHP verze na Wedosu\nAddHandler application/x-httpd-php82 .php\n\n# Bezpečnostní hlavičky\n&lt;IfModule mod_headers.c&gt;\n    Header always set X-Content-Type-Options "nosniff"\n    Header always set X-Frame-Options "SAMEORIGIN"\n    Header always set X-XSS-Protection "1; mode=block"\n    Header always set Referrer-Policy "strict-origin-when-cross-origin"\n    Header always set Strict-Transport-Security "max-age=31536000; includeSubDomains"\n&lt;/IfModule&gt;\n\n# Gzip komprese\n&lt;IfModule mod_deflate.c&gt;\n    AddOutputFilterByType DEFLATE text/html text/plain text/css application/javascript application/json\n&lt;/IfModule&gt;\n\n# Browser cache pro statické soubory\n&lt;IfModule mod_expires.c&gt;\n    ExpiresActive On\n    ExpiresByType text/css "access plus 1 month"\n    ExpiresByType application/javascript "access plus 1 month"\n    ExpiresByType image/jpeg "access plus 1 year"\n    ExpiresByType image/png "access plus 1 year"\n    ExpiresByType image/svg+xml "access plus 1 year"\n&lt;/IfModule&gt;</code></pre>', 'lesson', 20, 15, 15);


-- ============================================================
-- ZÁVĚREČNÝ KVÍZ (sort_order 21)
-- ============================================================

INSERT INTO lessons (course_id, title, content, lesson_type, sort_order, xp_reward, duration_minutes) VALUES
(@kurs_id, 'Závěrečný kvíz — Celý PHP kurz', '<p>Závěrečný test pokrývající všechny sekce kurzu PHP — od základů přes PDO, OOP, bezpečnost až po .htaccess.</p>', 'final_quiz', 21, 200, 30);

SET @qfin = LAST_INSERT_ID();

INSERT INTO quizzes (lesson_id, question, option_a, option_b, option_c, option_d, correct_answer, explanation, sort_order) VALUES
(@qfin, 'Jaký je správný způsob připojení k MariaDB v PHP?', 'mysql_connect()', 'new PDO("mysql:host=...;dbname=...;charset=utf8", ...)', 'new mysqli(...)', 'pg_connect()', 'b', 'PDO je doporučená abstraktní vrstva — podporuje prepared statements a více databází.', 1),
(@qfin, 'K čemu slouží PDO prepared statements?', 'Zrychlují dotazy', 'Zabraňují SQL injekci', 'Komprimují data', 'Ukládají výsledky do cache', 'b', 'Prepared statements oddělují SQL kód od dat — zabraňují SQL injekci.', 2),
(@qfin, 'Jak správně escapovat výstup proti XSS?', 'addslashes()', 'strip_tags()', 'htmlspecialchars($s, ENT_QUOTES, "UTF-8")', 'urlencode()', 'c', 'htmlspecialchars s ENT_QUOTES a UTF-8 převodí nebezpečné znaky na HTML entity.', 3),
(@qfin, 'Jaká cookie domain umožňí sdílení napříč subdoménami .vevit.fun?', 'domain=edu.vevit.fun', 'domain=.vevit.fun', 'domain=vevit.fun', 'domain=*.vevit.fun', 'b', 'Tečka před doménou (.vevit.fun) umožňuje sdílet cookie napříč všemi subdoménami.', 4),
(@qfin, 'Co dělá PHP trait?', 'Definuje konstantu', 'Umožňuje sdílet kód mezi třídami bez dědičnosti', 'Vytváří novou instanci', 'Importuje Composer balíček', 'b', 'Trait je mechanismus pro sdílení metod mezi třídami — alternativa k vícenásobné dědičnosti.', 5),
(@qfin, 'Jak vytvoříš bezpečný token pro reset hesla?', 'md5(time())', 'rand(0, 999999)', 'bin2hex(random_bytes(32))', 'sha1($userId)', 'c', 'bin2hex(random_bytes(32)) generuje kryptograficky bezpečný náhodný token.', 6),
(@qfin, 'Jak ověříš MIME typ nahraného souboru?', '$_FILES["file"]["type"]', 'pathinfo($name, PATHINFO_EXTENSION)', 'finfo_file(finfo_open(FILEINFO_MIME_TYPE), $tmp)', 'getimagesize()', 'c', 'finfo_file ověřuje skutečný MIME typ souboru — $_FILES["type"] pochází od klienta a je nespolehlivý.', 7),
(@qfin, 'Co znamená PDO::ATTR_EMULATE_PREPARES => false?', 'Emuluje prepared statements', 'Vypíná emulaci — native prepared statements na serveru', 'Povoluje SQL injekci', 'Zrychluje dotazy', 'b', 'Vypnutí emulace zaručí, že prepared statements běží nativně na databázovém serveru.', 8),
(@qfin, 'Jaký .htaccess RewriteRule přesměruje API na PHP backend?', 'RewriteRule ^api/(.*)$ index.php', 'RewriteRule ^api/(.*)$ api/index.php [QSA,L]', 'RewriteRule /api api.php', 'Redirect /api index.php', 'b', 'RewriteRule s QSA (předá query string) a L (poslední pravidlo) přesměruje API požadavky na PHP entry point.', 9),
(@qfin, 'K čemu slouží PHP spl_autoload_register?', 'Registruje Composer balíčky', 'Zaregistruje funkci, která automaticky načte třídu při prvním použití', 'Vytváří nové třídy', 'Přepíše existující třídu', 'b', 'spl_autoload_register umožňuje vlastní autoloading — třída se načte automaticky, když je poprvé použita.', 10);


-- ============================================================
-- Aktualizace počtu lekcí
-- ============================================================

UPDATE courses SET lesson_count = (SELECT COUNT(*) FROM lessons WHERE course_id = @kurs_id) WHERE id = @kurs_id;