-- Java kurz — Kompletní kurz (20 lekcí + závěrečný kvíz)
-- MariaDB 10.4, phpMyAdmin style, no DELIMITER
-- Apostrofy escapovány jako ''

SET @kurs_id = (SELECT id FROM courses WHERE slug = 'java');

-- ============================================================
-- SEKCE 1: Základy Javy (sort_order 1-4)
-- ============================================================

INSERT INTO lessons (course_id, title, content, lesson_type, sort_order, xp_reward, duration_minutes) VALUES
(@kurs_id, 'Úvod do Javy', '<h2>Co je Java</h2><p>Java je objektově orientovaný jazyk běžící na JVM (Java Virtual Machine). Zapis jednou, spouštěj všude — díky bytecode se Java programy spustí na jakékoliv platformě s JVM. K vývoji potřebuješ JDK (Java Development Kit), který obsahuje kompilátor <code>javac</code> a runtime <code>java</code>.</p><pre><code>public class HelloWorld {\n    public static void main(String[] args) {\n        System.out.println("Ahoj, VeVit!");\n    }\n}</code></pre><p>Kompilace a spuštění:</p><pre><code>javac HelloWorld.java\njava HelloWorld</code></pre><p>Soubor musí mít stejný název jako veřejná třída. Metoda <code>main</code> je vstupní bod programu.</p>', 'lesson', 1, 15, 12),

(@kurs_id, 'Typy, proměnné, operátory', '<h2>Primitivní typy</h2><p>Java je staticky typovaná — typ proměnné se určuje při deklaraci. Primitivní typy: <code>int</code>, <code>long</code>, <code>double</code>, <code>float</code>, <code>boolean</code>, <code>char</code>, <code>byte</code>, <code>short</code>. Referenční typy: <code>String</code>, pole, objekty.</p><pre><code>int vek = 25;\ndouble prumer = 4.8;\nboolean aktivni = true;\nchar znamka = ''A'';\nString jmeno = "Karel";\nfinal double PI = 3.14159;</code></pre><h2>Operátory</h2><p>Aritmetické: <code>+ - * / %</code>. Porovnávací: <code>== != &lt; &gt; &lt;= &gt;=</code>. Logické: <code>&amp;&amp; || !</code>. Bitové: <code>&amp; | ^ ~</code>. Ternární: <code>podm ? a : b</code>.</p><pre><code>int a = 10, b = 3;\nSystem.out.println(a / b);      // 3\nSystem.out.println(a % b);      // 1\nSystem.out.println(a > b ? "ano" : "ne"); // ano</code></pre>', 'lesson', 2, 15, 12),

(@kurs_id, 'Podmínky, cykly, switch expression', '<h2>Podmínky</h2><p><code>if/else if/else</code> pro větvení kódu. Java 14+ přináší switch expression s <code>-&gt;</code> syntaxí a možností vracet hodnotu.</p><pre><code>int vek = 18;\nif (vek >= 18) {\n    System.out.println("Dospely");\n} else if (vek >= 15) {\n    System.out.println("Stredni skola");\n} else {\n    System.out.println("Zakladni skola");\n}</code></pre><h2>Cykly</h2><p><code>for</code>, <code>while</code>, <code>do-while</code>. <code>break</code> ukončí cyklus, <code>continue</code> přeskočí iteraci. Enhanced for: <code>for (T x : kolekce)</code>.</p><pre><code>for (int i = 0; i < 5; i++) {\n    System.out.println(i);\n}\nfor (String s : List.of("a", "b", "c")) {\n    System.out.println(s);\n}</code></pre><h2>Switch expression (Java 14+)</h2><pre><code>String den = switch (vek) {\n    case 0 -> "Pondeli";\n    case 1 -> "Utery";\n    default -> "Jiny";\n};</code></pre>', 'lesson', 3, 15, 14),

(@kurs_id, 'Funkce a metody — overloading, varargs', '<h2>Metody v Javě</h2><p>Vše v Javě je uvnitř tříd — funkce se nazývají metody. Návratový typ, název, parametry. <code>void</code> pokud metoda nic nevrací.</p><pre><code>public class Kalkulacka {\n    public static int soucet(int a, int b) {\n        return a + b;\n    }\n\n    public static void main(String[] args) {\n        System.out.println(soucet(3, 4)); // 7\n    }\n}</code></pre><h2>Overloading</h2><p>Stejný název metody, různé parametry (typ nebo počet). Kompilátor vybere správnou variantu.</p><pre><code>public static int soucet(int a, int b) { return a + b; }\npublic static double soucet(double a, double b) { return a + b; }\npublic static int soucet(int a, int b, int c) { return a + b + c; }</code></pre><h2>Varargs</h2><p><code>Typ... nazev</code> přijme libovolný počet argumentů jako pole.</p><pre><code>public static int soucet(int... cisla) {\n    int sum = 0;\n    for (int c : cisla) sum += c;\n    return sum;\n}\nsoucet(1, 2, 3, 4); // 10</code></pre>', 'lesson', 4, 15, 13);


-- ============================================================
-- SEKCE 2: OOP (sort_order 5-6)
-- ============================================================

INSERT INTO lessons (course_id, title, content, lesson_type, sort_order, xp_reward, duration_minutes) VALUES
(@kurs_id, 'OOP — třídy, konstruktory, encapsulation', '<h2>Třídy a objekty</h2><p>Třída je předloha, objekt je instance. Konstruktor má stejný název jako třída a nemá návratový typ. <code>this</code> odkazuje na aktuální instanci.</p><pre><code>public class Zvire {\n    private String jmeno;\n    private int vek;\n\n    public Zvire(String jmeno, int vek) {\n        this.jmeno = jmeno;\n        this.vek = vek;\n    }\n\n    public String getJmeno() { return jmeno; }\n    public void setJmeno(String jmeno) { this.jmeno = jmeno; }\n\n    @Override\n    public String toString() {\n        return jmeno + " (" + vek + ")";\n    }\n}</code></pre><h2>Encapsulation</h2><p>Atributy <code>private</code>, přístup přes gettery a settery. Modifikátory: <code>private</code> (třída), <code>(default)</code> (balíček), <code>protected</code> (balíček + podtřídy), <code>public</code> (všude).</p>', 'lesson', 5, 15, 15),

(@kurs_id, 'Dědičnost, interfaces, abstraktní třídy', '<h2>Dědičnost</h2><p><code>extends</code> pro dědičnost — třída dědí atributy a metody rodiče. Java podporuje jen jednoduchou dědičnost. <code>super</code> volá konstruktor nebo metodu rodiče.</p><pre><code>public class Pes extends Zvire {\n    private String plemeno;\n\n    public Pes(String jmeno, int vek, String plemeno) {\n        super(jmeno, vek);\n        this.plemeno = plemeno;\n    }\n\n    @Override\n    public String toString() {\n        return super.toString() + " - " + plemeno;\n    }\n}</code></pre><h2>Interfaces</h2><p><code>interface</code> definuje kontrakt — metody bez implementace (od Java 8 i <code>default</code> a <code>static</code> metody). Třída může implementovat více interfaců.</p><pre><code>public interface Zvukovy {\n    String zvuk();\n    default void popis() { System.out.println("Vydava zvuk"); }\n}\n\npublic class Pes extends Zvire implements Zvukovy {\n    @Override\n    public String zvuk() { return "Haf!"; }\n}</code></pre><h2>Abstraktní třídy</h2><p><code>abstract</code> — nelze instanciovat. Může obsahovat abstraktní i konkrétní metody.</p><pre><code>public abstract class Tvar {\n    public abstract double obsah();\n    public void popis() { System.out.println("Obsah: " + obsah()); }\n}</code></pre>', 'lesson', 6, 15, 16);


-- ============================================================
-- SEKCE 3: Kolekce a generika (sort_order 7-8)
-- ============================================================

INSERT INTO lessons (course_id, title, content, lesson_type, sort_order, xp_reward, duration_minutes) VALUES
(@kurs_id, 'Collections — ArrayList, HashMap, HashSet, LinkedList', '<h2>Collections Framework</h2><p>Java nabízí bohatou hierarchii kolekcí v <code>java.util</code>. Všechny kolekce pracují s objekty — primitivní typy musíš zabalit (autoboxing).</p><h2>ArrayList</h2><p>Dynamické pole — automaticky se zvětšuje. Rychlý náhodný přístup O(1), pomalejší vkládání/mazání uprostřed.</p><pre><code>List&lt;String&gt; list = new ArrayList&lt;&gt;();\nlist.add("jablko");\nlist.add("banan");\nlist.set(0, "hruska");\nSystem.out.println(list.get(1)); // banan\nlist.removeIf(s -> s.startsWith("b"));</code></pre><h2>HashMap</h2><p>Klíč–hodnota, null klíč i hodnota povolena. Neseřazená. Přístup O(1).</p><pre><code>Map&lt;String, Integer&gt; mapa = new HashMap&lt;&gt;();\nmapa.put("Karel", 25);\nmapa.put("Jana", 22);\nSystem.out.println(mapa.getOrDefault("Petr", -1));</code></pre><h2>HashSet</h2><p>Unikátní prvky, neseřazený. Operace add/contains O(1).</p><pre><code>Set&lt;Integer&gt; set = new HashSet&lt;&gt;();\nset.add(1); set.add(2); set.add(1);\nSystem.out.println(set.size()); // 2</code></pre><h2>LinkedList</h2><p>Dvojitě spojový seznam — rychlé vkládání/mazání na koncích. Implementuje List i Deque.</p><pre><code>LinkedList&lt;String&gt; ll = new LinkedList&lt;&gt;();\nll.addFirst("prvni");\nll.addLast("posledni");\nSystem.out.println(ll.peekFirst());</code></pre>', 'lesson', 7, 15, 16),

(@kurs_id, 'Generika — bounded wildcards, generic metody', '<h2>Generika</h2><p>Generika umožňují psát kód nezávislý na typu. <code>List&lt;T&gt;</code> — T je typový parametr. Kompilátor kontroluje typovou bezpečnost.</p><pre><code>public class Krabice&lt;T&gt; {\n    private T obsah;\n    public void vloz(T obsah) { this.obsah = obsah; }\n    public T vyber() { return obsah; }\n}\n\nKrabice&lt;String&gt; k = new Krabice&lt;&gt;();\nk.vloz("Ahoj");\nString s = k.vyber();</code></pre><h2>Bounded type parameters</h2><p>Omezení typu: <code>T extends Number</code> — T musí být Number nebo jeho podtřída.</p><pre><code>public static &lt;T extends Number&gt; double soucet(List&lt;T&gt; cisla) {\n    double sum = 0;\n    for (T c : cisla) sum += c.doubleValue();\n    return sum;\n}</code></pre><h2>Wildcards</h2><p><code>&lt;? extends T&gt;</code> — upper bounded (čtení). <code>&lt;? super T&gt;</code> — lower bounded (zápis). <code>&lt;?&gt;</code> — unbounded wildcard.</p><pre><code>// Cteni cehokoliv co je Number nebo podtrida\nvoid vypis(List&lt;? extends Number&gt; list) {\n    for (Number n : list) System.out.println(n);\n}\n// Zapis - super\nvoid pridat(List&lt;? super Integer&gt; list) {\n    list.add(42);\n}</code></pre>', 'lesson', 8, 15, 15);


-- ============================================================
-- SEKCE 4: Funkcionální a moderní Java (sort_order 9-11)
-- ============================================================

INSERT INTO lessons (course_id, title, content, lesson_type, sort_order, xp_reward, duration_minutes) VALUES
(@kurs_id, 'Java Streams API — filter/map/reduce/collect', '<h2>Streams API</h2><p>Streams (Java 8+) poskytují funkcionální způsob zpracování kolekcí. Stream je sekvence prvků podporující agregované operace. Není to datová struktura — nepřehrává prvky.</p><pre><code>List&lt;String&gt; jmena = List.of("Karel", "Jana", "Petr", "Eva");\n\njmena.stream()\n    .filter(j -> j.length() > 3)\n    .map(String::toUpperCase)\n    .forEach(System.out::println);\n// KAREL, JANA</code></pre><h2>reduce a collect</h2><p><code>reduce</code> sloučí stream do jedné hodnoty. <code>collect</code> převede stream do kolekce.</p><pre><code>int soucet = List.of(1, 2, 3, 4).stream()\n    .reduce(0, Integer::sum);\n\nList&lt;Integer&gt; suda = List.of(1, 2, 3, 4, 5, 6).stream()\n    .filter(x -> x % 2 == 0)\n    .collect(Collectors.toList());\n\nMap&lt;Boolean, List&lt;Integer&gt;&gt; rozdeleno = List.of(1,2,3,4,5).stream()\n    .collect(Collectors.partitioningBy(x -> x % 2 == 0));</code></pre><h2>Primitivní streamy</h2><p><code>IntStream</code>, <code>LongStream</code>, <code>DoubleStream</code> — bez autoboxingu.</p><pre><code>IntStream.rangeClosed(1, 5).sum(); // 15\nIntStream.of(3, 1, 4).average().ifPresent(System.out::println);</code></pre>', 'lesson', 9, 15, 16),

(@kurs_id, 'Optional — null safety', '<h2>Optional</h2><p><code>Optional&lt;T&gt;</code> (Java 8+) obaluje hodnotu, která může nebo nemusí existovat. Nahrazuje <code>null</code> kontroly a zabraňuje <code>NullPointerException</code>.</p><pre><code>Optional&lt;String&gt; jmeno = Optional.of("Karel");\nOptional&lt;String&gt; prazdne = Optional.empty();\n\n// Bezpecne ziskani hodnoty\njmeno.ifPresent(s -> System.out.println(s));\nSystem.out.println(jeme.orElse("Nezname"));\nSystem.out.println(jeme.orElseGet(() -> "Vypocteno"));</code></pre><h2>Řetězení operací</h2><p><code>map</code>, <code>flatMap</code>, <code>filter</code> na Optional umožňují řetězit transformace bez null kontrol.</p><pre><code>Optional&lt;String&gt; jmeno = Optional.of("  Karel  ");\nString vysledek = jmeno\n    .map(String::trim)\n    .filter(s -> !s.isEmpty())\n    .orElse("prazdne");\n// "Karel"\n\n// flatMap pro vnororene Optional\nOptional&lt;String&gt; mesto = uzivatel.flatMap(Uzivatel::getMesto);</code></pre><h2>Kdy NEPOUŽÍVAT Optional</h2><p>Nikdy jako pole objektu, parametr metody nebo pro kolekce. Optional je pro návratové hodnoty.</p>', 'lesson', 10, 15, 14),

(@kurs_id, 'Records (Java 16+) a Sealed Classes (Java 17+)', '<h2>Records</h2><p><code>record</code> (Java 16+) je neměnná datová třída. Automaticky generuje konstruktor, gettery, <code>equals()</code>, <code>hashCode()</code> a <code>toString()</code>.</p><pre><code>public record Bod(int x, int y) {\n    // Kompaktni konstruktor pro validaci\n    public Bod {\n        if (x < 0 || y < 0) throw new IllegalArgumentException();\n    }\n}\n\nBod b = new Bod(3, 4);\nSystem.out.println(b.x()); // 3\nSystem.out.println(b);       // Bod[x=3, y=4]</code></pre><h2>Sealed Classes</h2><p><code>sealed</code> (Java 17+) omezuje, které třídy mohou dědit. <code>permits</code> uvádí povolené podtřídy. Podtřídy jsou <code>final</code>, <code>sealed</code> nebo <code>non-sealed</code>.</p><pre><code>public sealed class Tvar permits Kruh, Ctverec {}\n\npublic final class Kruh extends Tvar {\n    private final double r;\n    public Kruh(double r) { this.r = r; }\n    public double obsah() { return Math.PI * r * r; }\n}\n\npublic final class Ctverec extends Tvar {\n    private final double a;\n    public Ctverec(double a) { this.a = a; }\n    public double obsah() { return a * a; }\n}</code></pre><p>Pattern matching se sealed classes umožňuje úplné pokrytí v switch bez <code>default</code>.</p>', 'lesson', 11, 15, 15);


-- ============================================================
-- SEKCE 5: I/O, HTTP a Concurrency (sort_order 12-14)
-- ============================================================

INSERT INTO lessons (course_id, title, content, lesson_type, sort_order, xp_reward, duration_minutes) VALUES
(@kurs_id, 'Java I/O — java.nio.file (Files, Path)', '<h2>java.nio.file</h2><p>Moderní API pro práci se soubory — <code>Path</code> reprezentuje cestu, <code>Files</code> poskytuje statické metody. Nahrazuje staré <code>java.io.File</code>.</p><pre><code>import java.nio.file.*;\n\nPath p = Path.of("data.txt");\n\n// Cteni\nString obsah = Files.readString(p);\nList&lt;String&gt; radky = Files.readAllLines(p);\n\n// Zapis\nFiles.writeString(p, "Ahoj, VeVit!", StandardOpenOption.CREATE);\n\n// Kopirovani, presun, mazani\nFiles.copy(Path.of("a.txt"), Path.of("b.txt"));\nFiles.move(Path.of("old.txt"), Path.of("new.txt"));\nFiles.deleteIfExists(Path.of("tmp.txt"));</code></pre><h2>Adresáře</h2><pre><code>// Prochazeni adresare\ntry (var stream = Files.list(Path.of("."))) {\n    stream.filter(f -> f.toString().endsWith(".java"))\n          .forEach(System.out::println);\n}\n\n// Rekurzivni prochazeni\nFiles.walk(Path.of(".")).filter(Files::isRegularFile).forEach(System.out::println);\n\n// Vytvoreni adresare\nFiles.createDirectories(Path.of("output/data"));</code></pre>', 'lesson', 12, 15, 14),

(@kurs_id, 'HTTP Client (Java 11+) — sync a async', '<h2>HttpClient</h2><p>Moderní HTTP klient (Java 11+) nahrazuje <code>HttpURLConnection</code>. Podporuje HTTP/2, sync i async požadavky.</p><pre><code>import java.net.URI;\nimport java.net.http.*;\n\nHttpClient client = HttpClient.newHttpClient();\nHttpRequest request = HttpRequest.newBuilder()\n    .uri(URI.create("https://api.example.com/data"))\n    .header("Accept", "application/json")\n    .GET()\n    .build();\n\n// Sync volani\nHttpResponse&lt;String&gt; response = client.send(request,\n    HttpResponse.BodyHandlers.ofString());\nSystem.out.println(response.statusCode());\nSystem.out.println(response.body());</code></pre><h2>Asynchronní volání</h2><pre><code>// Async s CompletableFuture\nclient.sendAsync(request, HttpResponse.BodyHandlers.ofString())\n    .thenApply(HttpResponse::body)\n    .thenAccept(System.out::println)\n    .join();</code></pre><h2>POST požadavek</h2><pre><code>HttpRequest post = HttpRequest.newBuilder()\n    .uri(URI.create("https://api.example.com/add"))\n    .header("Content-Type", "application/json")\n    .POST(HttpRequest.BodyPublishers.ofString("{\"name\":\"Karel\"}"))\n    .build();\n\nHttpResponse&lt;String&gt; r = client.send(post, HttpResponse.BodyHandlers.ofString());</code></pre>', 'lesson', 13, 15, 15),

(@kurs_id, 'Concurrency — ExecutorService, CompletableFuture, Virtual Threads', '<h2>ExecutorService</h2><p>Nahrazuje přímé vytváření vláken. Thread pool spravuje vlákna a úkoly. Vždy volej <code>shutdown()</code>.</p><pre><code>ExecutorService executor = Executors.newFixedThreadPool(4);\n\nFuture&lt;String&gt; future = executor.submit(() -> {\n    Thread.sleep(1000);\n    return "hotovo";\n});\n\nString vysledek = future.get(); // blokuje\nexecutor.shutdown();</code></pre><h2>CompletableFuture</h2><p>Asynchronní pipeline — <code>thenApply</code>, <code>thenAccept</code>, <code>thenCompose</code>. Můžete řetězit a kombinovat.</p><pre><code>CompletableFuture&lt;String&gt; cf = CompletableFuture\n    .supplyAsync(() -> "data")\n    .thenApply(String::toUpperCase)\n    .thenAccept(System.out::println);\n\n// Kombinovani vice future\nCompletableFuture.allOf(cf1, cf2).join();</code></pre><h2>Virtual Threads (Java 21)</h2><p>Lehká vlákna spravovaná JVM — miliony vláken bez režie OS. Ideální pro I/O-bound operace.</p><pre><code>try (var executor = Executors.newVirtualThreadPerTaskExecutor()) {\n    IntStream.range(0, 100_000).forEach(i -> {\n        executor.submit(() -> {\n            Thread.sleep(Duration.ofSeconds(1));\n            return i;\n        });\n    });\n}</code></pre>', 'lesson', 14, 15, 18);


-- ============================================================
-- SEKCE 6: Výjimky, lambdy a vzory (sort_order 15-17)
-- ============================================================

INSERT INTO lessons (course_id, title, content, lesson_type, sort_order, xp_reward, duration_minutes) VALUES
(@kurs_id, 'Výjimky — checked vs unchecked, try-with-resources', '<h2>Výjimky v Javě</h2><p><code>Exception</code> — checked (musí se zachytit nebo deklarovat). <code>RuntimeException</code> — unchecked (nepovinné zachycení). <code>Error</code> — závažné chyby JVM.</p><pre><code>try {\n    int x = Integer.parseInt("abc");\n} catch (NumberFormatException e) {\n    System.out.println("Neplatny vstup: " + e.getMessage());\n} finally {\n    System.out.println("Vzdy se provede");\n}</code></pre><h2>Multi-catch</h2><pre><code>try {\n    // rizikovy kod\n} catch (IOException | SQLException e) {\n    System.out.println("Chyba: " + e.getMessage());\n}</code></pre><h2>try-with-resources</h2><p>Automaticky zavře resource implementující <code>AutoCloseable</code>. Žádný finally blok pro cleanup.</p><pre><code>try (var reader = Files.newBufferedReader(Path.of("data.txt"));\n     var writer = Files.newBufferedWriter(Path.of("out.txt"))) {\n    String line = reader.readLine();\n    writer.write(line);\n} // automaticky zavreno\n\n// Vlastni AutoCloseable\npublic class MujResource implements AutoCloseable {\n    @Override\n    public void close() { System.out.println("zavreno"); }\n}</code></pre>', 'lesson', 15, 15, 15),

(@kurs_id, 'Lambda výrazy a Method References — Function, Predicate, Consumer, Supplier', '<h2>Lambda výrazy</h2><p>Anonymní funkce: <code>(parametry) -&gt; vyraz</code>. Implementují functional interface (rozhraní s jednou abstraktní metodou).</p><pre><code>// Pred lambda\nRunnable r = new Runnable() {\n    @Override public void run() { System.out.println("Ahoj"); }\n};\n\n// S lambda\nRunnable r = () -> System.out.println("Ahoj");\n\nComparator&lt;String&gt; comp = (a, b) -> a.length() - b.length();\n\nList&lt;String&gt; list = List.of("bb", "aaa", "c");\nlist.stream().sorted((a, b) -> a.length() - b.length())\n    .forEach(System.out::println);</code></pre><h2>Method References</h2><p>Zkratka za lambda volající jednu metodu: <code>Trida::metoda</code>. Čtyři typy: statická, instance, konstruktor, typ metoda.</p><pre><code>Function&lt;String, Integer&gt; f = String::length;\nConsumer&lt;String&gt; c = System.out::println;\nSupplier&lt;List&gt; s = ArrayList::new;\nBiPredicate&lt;String, String&gt; bp = String::equalsIgnoreCase;</code></pre><h2>Funkcionální rozhraní java.util.function</h2><pre><code>Function&lt;T,R&gt;    — R apply(T t)\nPredicate&lt;T&gt;    — boolean test(T t)\nConsumer&lt;T&gt;     — void accept(T t)\nSupplier&lt;T&gt;     — T get()\nBiFunction&lt;T,U,R&gt; — R apply(T t, U u)\nUnaryOperator&lt;T&gt; — T apply(T t)</code></pre>', 'lesson', 16, 15, 16),

(@kurs_id, 'Design Patterns — Builder, Singleton, Factory, Observer', '<h2>Builder</h2><p>Graduálně konstruuje komplexní objekt. Odděluje reprezentaci od konstrukce.</p><pre><code>public class Uzivatel {\n    private final String jmeno;\n    private final String email;\n    private final int vek;\n\n    private Uzivatel(Builder b) {\n        this.jmeno = b.jmeno; this.email = b.email; this.vek = b.vek;\n    }\n\n    public static class Builder {\n        private String jmeno, email; private int vek;\n        public Builder jmeno(String j) { this.jmeno = j; return this; }\n        public Builder email(String e) { this.email = e; return this; }\n        public Builder vek(int v) { this.vek = v; return this; }\n        public Uzivatel build() { return new Uzivatel(this); }\n    }\n}\n\nUzivatel u = new Uzivatel.Builder()\n    .jmeno("Karel").email("k@k.cz").vek(25).build();</code></pre><h2>Singleton</h2><pre><code>public class Databaze {\n    private static volatile Databaze instance;\n    private Databaze() {}\n    public static Databaze getInstance() {\n        if (instance == null) {\n            synchronized (Databaze.class) {\n                if (instance == null) instance = new Databaze();\n            }\n        }\n        return instance;\n    }\n}</code></pre><h2>Factory Method</h2><pre><code>public interface Zvire { String zvuk(); }\npublic class Pes implements Zvire { public String zvuk() { return "Haf!"; } }\npublic class Kocka implements Zvire { public String zvuk() { return "Mnau!"; } }\n\npublic class ZvireFactory {\n    public static Zvire vytvor(String typ) {\n        return switch (typ) {\n            case "pes" -> new Pes();\n            case "kocka" -> new Kocka();\n            default -> throw new IllegalArgumentException(typ);\n        };\n    }\n}</code></pre><h2>Observer</h2><pre><code>public interface Observer { void update(String zprava); }\npublic class EventManager {\n    private List&lt;Observer&gt; listeners = new ArrayList&lt;&gt;();\n    public void add(Observer o) { listeners.add(o); }\n    public void notify(String msg) { listeners.forEach(o -> o.update(msg)); }\n}</code></pre>', 'lesson', 17, 15, 18);


-- ============================================================
-- SEKCE 7: Databáze, Spring Boot a testování (sort_order 18-20)
-- ============================================================

INSERT INTO lessons (course_id, title, content, lesson_type, sort_order, xp_reward, duration_minutes) VALUES
(@kurs_id, 'JDBC a databáze — připojení, prepared statements', '<h2>JDBC</h2><p>Java Database Connectivity — standardní API pro přístup k relačním databázím. <code>DriverManager</code> vytvoří spojení, <code>PreparedStatement</code> pro bezpečné dotazy.</p><pre><code>import java.sql.*;\n\nString url = "jdbc:mysql://localhost:3306/appdb";\n\ntry (Connection conn = DriverManager.getConnection(url, "user", "pass")) {\n    // Vytvoreni tabulky\n    try (Statement stmt = conn.createStatement()) {\n        stmt.execute("CREATE TABLE IF NOT EXISTS users "\n            + "(id INT PRIMARY KEY AUTO_INCREMENT, name VARCHAR(100))");\n    }\n\n    // Bezpecny insert s PreparedStatement\n    try (PreparedStatement ps = conn.prepareStatement(\n            "INSERT INTO users (name) VALUES (?)")) {\n        ps.setString(1, "Karel");\n        ps.executeUpdate();\n    }\n\n    // Cteni\n    try (PreparedStatement ps = conn.prepareStatement(\n            "SELECT * FROM users WHERE id = ?")) {\n        ps.setInt(1, 1);\n        ResultSet rs = ps.executeQuery();\n        if (rs.next()) {\n            System.out.println(rs.getString("name"));\n        }\n    }\n}</code></pre><p>Vždy používej <code>PreparedStatement</code> — chrání před SQL injekcí. Vždy zavírej <code>Connection</code> pomocí try-with-resources.</p>', 'lesson', 18, 15, 16),

(@kurs_id, 'Spring Boot intro — REST API, @RestController, DI', '<h2>Spring Boot</h2><p>Rámec pro rychlou tvorbu Java aplikací. Automatická konfigurace, vestavěný server, minimalizace boilerplate. Start na <a href="https://start.spring.io">start.spring.io</a>.</p><pre><code>@SpringBootApplication\npublic class App {\n    public static void main(String[] args) {\n        SpringApplication.run(App.class, args);\n    }\n}</code></pre><h2>REST Controller</h2><pre><code>@RestController\n@RequestMapping("/api/users")\npublic class UserController {\n\n    private final UserService userService;\n\n    // Dependency Injection pres konstruktor\n    public UserController(UserService userService) {\n        this.userService = userService;\n    }\n\n    @GetMapping\n    public List&lt;User&gt; all() {\n        return userService.findAll();\n    }\n\n    @GetMapping("/{id}")\n    public User one(@PathVariable Long id) {\n        return userService.findById(id);\n    }\n\n    @PostMapping\n    @ResponseStatus(HttpStatus.CREATED)\n    public User create(@RequestBody User user) {\n        return userService.save(user);\n    }\n\n    @DeleteMapping("/{id}")\n    public void delete(@PathVariable Long id) {\n        userService.deleteById(id);\n    }\n}</code></pre><h2>Dependency Injection</h2><p><code>@Service</code>, <code>@Repository</code>, <code>@Component</code> — Spring automaticky spravuje instance (beany). Injektuje přes konstruktor — doporučený způsob.</p><pre><code>@Service\npublic class UserService {\n    private final UserRepository repo;\n    public UserService(UserRepository repo) { this.repo = repo; }\n    public List&lt;User&gt; findAll() { return repo.findAll(); }\n}</code></pre>', 'lesson', 19, 15, 18),

(@kurs_id, 'Testování — JUnit 5, Mockito, parametrické testy', '<h2>JUnit 5</h2><p>Standardní testovací rámec pro Javu. Anotace: <code>@Test</code>, <code>@BeforeEach</code>, <code>@DisplayName</code>. Asserce: <code>assertEquals</code>, <code>assertTrue</code>, <code>assertThrows</code>.</p><pre><code>import org.junit.jupiter.api.*;\nimport static org.junit.jupiter.api.Assertions.*;\n\nclass KalkulackaTest {\n    private Kalkulacka k;\n\n    @BeforeEach\n    void setUp() { k = new Kalkulacka(); }\n\n    @Test\n    @DisplayName("Soucet dvou cisel")\n    void soucet() {\n        assertEquals(5, k.soucet(2, 3));\n    }\n\n    @Test\n    void deleniNulou() {\n        assertThrows(ArithmeticException.class,\n            () -> k.deleni(10, 0));\n    }\n}</code></pre><h2>Mockito</h2><p>Mockování závislostí — izoluje testovanou třídu od externích služeb.</p><pre><code>@ExtendWith(MockitoExtension.class)\nclass UserServiceTest {\n    @Mock UserRepository repo;\n    @InjectMocks UserService service;\n\n    @Test\n    void findById() {\n        when(repo.findById(1L))\n            .thenReturn(Optional.of(new User("Karel")));\n        User u = service.findById(1L);\n        assertEquals("Karel", u.getJmeno());\n        verify(repo).findById(1L);\n    }\n}</code></pre><h2>Parametrické testy</h2><pre><code>@ParameterizedTest\n@CsvSource({"1,1,2", "2,3,5", "10,-5,5"})\nvoid soucet(int a, int b, int expected) {\n    assertEquals(expected, new Kalkulacka().soucet(a, b));\n}</code></pre>', 'lesson', 20, 15, 16);


-- ============================================================
-- ZÁVĚREČNÝ KVÍZ (sort_order 21)
-- ============================================================

INSERT INTO lessons (course_id, title, content, lesson_type, sort_order, xp_reward, duration_minutes) VALUES
(@kurs_id, 'Závěrečný kvíz — Celý Java kurz', '<p>Závěrečný test pokrývající všechny sekce kurzu Java.</p>', 'final_quiz', 21, 200, 30);

SET @qfin = LAST_INSERT_ID();

INSERT INTO quizzes (lesson_id, question, option_a, option_b, option_c, option_d, correct_answer, explanation, sort_order) VALUES
(@qfin, 'Co je JVM?', 'Java Virtual Machine — spouští bytecode na jakékoliv platformě', 'Java Visual Manager', 'Java Variable Module', 'Java Version Manager', 'a', 'JVM (Java Virtual Machine) je virtuální stroj, který spouští Java bytecode nezávisle na platformě.', 1),
(@qfin, 'Jaký je rozdíl mezi == a .equals() u řetězců?', 'Žádný rozdíl', '== porovnává reference, .equals() obsah', '.equals() je rychlejší', '== porovnává obsah, .equals() referenci', 'b', '== porovnává reference (identitu objektu), .equals() porovnává logickou rovnost obsahu řetězce.', 2),
(@qfin, 'Co dělá switch expression v Javě 14+?', 'Je to stará syntaxe switch', 'Vrací hodnotu a používá -> místo case:', 'Nemůže mít default', 'Vždy vyžaduje break', 'b', 'Switch expression vrací hodnotu, používá šipkovou syntaxi -> a nepotřebuje break.', 3),
(@qfin, 'Co je varargs v Javě?', 'Proměnná deklarovaná klíčovým slovem var', 'Metoda přijímající proměnlivý počet argumentů jako pole', 'Dynamický typ', 'Výchozí hodnota parametru', 'b', 'Varargs (Typ... nazev) umožňuje metodě přijmout libovolný počet argumentů stejného typu jako pole.', 4),
(@qfin, 'Jaký je rozdíl mezi ArrayList a LinkedList?', 'ArrayList je synchronizovaný', 'ArrayList má rychlý náhodný přístup, LinkedList rychlé vkládání/mazání', 'LinkedList neumožňuje null', 'Žádný rozdíl', 'b', 'ArrayList je založen na poli (rychlý get/set), LinkedList na spojovém seznamu (rychlé add/remove na koncích).', 5),
(@qfin, 'Co dělá Optional.ofNullable(x)?', 'Vytvoří Optional, které je vždy prázdné', 'Vytvoří Optional z x, nebo empty pokud x je null', 'Vyvolá výjimku pokud x je null', 'Převede Optional na stream', 'b', 'Optional.ofNullable() vytvoří Optional s hodnotou x, nebo prázdné Optional pokud x je null.', 6),
(@qfin, 'Co je sealed class v Javě 17+?', 'Třída, kterou nelze instanciovat', 'Třída s omezenou dědičností — uvádí povolené podtřídy', 'Třída bez metod', 'Třída s privátním konstruktorem', 'b', 'Sealed class omezuje, které třídy mohou dědit — pomocí permits uvádí povolené podtřídy.', 7),
(@qfin, 'Co dělá try-with-resources?', 'Zachytí všechny výjimky', 'Automaticky zavře resource implementující AutoCloseable', 'Vytvoří nové vlákno', 'Otevře soubor pro čtení', 'b', 'try-with-resources automaticky zavře všechny resource implementující AutoCloseable na konci bloku.', 8),
(@qfin, 'Co je CompletableFuture v Javě?', 'Futures, které nelze zrušit', 'Asynchronní výpočet s možností řetězení operací', 'Synchronní HTTP klient', 'Druh kolekce', 'b', 'CompletableFuture umožňuje asynchronní výpočet s řetězením operací thenApply, thenAccept, thenCompose.', 9),
(@qfin, 'K čemu slouží @RestController v Spring Boot?', 'Definuje HTML šablonu', 'Označuje třídu, která obsluhuje HTTP požadavky a vrací JSON/data', 'Vytvoří databázovou tabulku', 'Spustí aplikaci', 'b', '@RestController kombinuje @Controller a @ResponseBody — metody vrací data (JSON) místo názvů šablon.', 10);


-- ============================================================
-- Aktualizace počtu lekcí
-- ============================================================

UPDATE courses SET lesson_count = (SELECT COUNT(*) FROM lessons WHERE course_id = @kurs_id) WHERE id = @kurs_id;