-- C# kurz — Kompletní kurz (20 lekcí + závěrečný kvíz)
-- MariaDB 10.4, phpMyAdmin style, no DELIMITER
-- Apostrofy escapovány jako ''

SET @kurs_id = (SELECT id FROM courses WHERE slug = 'csharp');

-- ============================================================
-- LEKCE 1–20
-- ============================================================

INSERT INTO lessons (course_id, title, content, lesson_type, sort_order, xp_reward, duration_minutes) VALUES
(@kurs_id, 'Úvod do C#', '<h2>Co je C# a .NET</h2><p>C# je moderní objektově orientovaný jazyk od Microsoftu, běžící na platformě .NET. Vývojové prostředí: Visual Studio, VS Code + C# Dev Kit, Rider. Od C# 9 podporuje <strong>top-level statements</strong> — minimální boilerplate.</p><pre><code>// Program.cs — top-level statements (C# 9+)// Hello World na jednom řádkuConsole.WriteLine("Ahoj, VeVit!");// Typická struktura pro starší verze// using System;// namespace App {//   class Program {//     static void Main() {//       Console.WriteLine("Ahoj!");//     }//   }// }</code></pre><p>Instalace: stáhni <strong>.NET SDK</strong> z dotnet.microsoft.com. Ověř příkazem <code>dotnet --version</code>. Vytvoř projekt: <code>dotnet new console -n MujProjekt</code>, spusť: <code>dotnet run</code>.</p>', 'lesson', 1, 15, 12),

(@kurs_id, 'Typy, proměnné, var, string interpolace', '<h2>Typy a proměnné</h2><p>C# je staticky typovaný jazyk. Základní typy: <code>int</code>, <code>double</code>, <code>bool</code>, <code>char</code>, <code>string</code>. Klíčové slovo <code>var</code> umožňuje odvození typu překladačem. String interpolace: <code>$"{promenna}"</code>.</p><pre><code>int vek = 25;double prumer = 4.8;bool aktivni = true;char pismeno = ''A'';string jmeno = "Karel";// var — typ se odvodívar skore = 100;        // intvar pi = 3.14;         // doublevar zprava = "Ahoj!";  // string// String interpolaceConsole.WriteLine($"{jmeno} je {vek} let stary");Console.WriteLine($"Pi = {pi:F2}");  // Pi = 3,14// Verbatim string — @var cesta = @"C:\Users\Karel\Docs";// Raw string literal — """ (C# 11)var json = """        {"name": "Karel"}        """;</code></pre>', 'lesson', 2, 15, 12),

(@kurs_id, 'Podmínky, switch expression, pattern matching základy', '<h2>Podmínky if/else</h2><p>Standardní <code>if/else if/else</code>. Ternární operátor: <code>podm ? a : b</code>. Od C# 8: <strong>switch expression</strong> — stručná syntaxe. Základy pattern matchingu s <code>is</code> a <code>when</code>.</p><pre><code>int vek = 18;// if / else if / elseif (vek >= 18)    Console.WriteLine("Dospely");else if (vek >= 15)    Console.WriteLine("Stredni skola");else    Console.WriteLine("Zakladni skola");// Ternarni operátorvar status = vek >= 18 ? "dospely" : "mladistvy";// Switch expression (C# 8+)var kategorie = vek switch{    >= 18 => "dospely",    >= 15 => "mladistvy",    _     => "dite"  // _ = default};// Pattern matching zakladyobject obj = "Ahoj";if (obj is string s)    Console.WriteLine(s.Length);  // 4// when klauzule ve switchswitch (vek){    case int n when n >= 18:        Console.WriteLine("Dospely");        break;    default:        Console.WriteLine("Jiny");        break;}</code></pre>', 'lesson', 3, 15, 14),

(@kurs_id, 'OOP — třídy, properties, init-only setters', '<h2>Třídy a objekty</h2><p>Třída je šablona pro objekt. Konstruktor inicializuje data. <strong>Properties</strong> nahrazují get/set metody. <strong>Init-only setters</strong> (C# 9) umožňují nastavení pouze při konstrukci — immutable po vytvoření.</p><pre><code>class Student{    // Auto-property    public string Jmeno { get; set; }    // Init-only setter (C# 9)    public int Vek { get; init; } = 0;    // Computed property    public bool Dospely => Vek >= 18;    // Konstruktor    public Student(string jmeno, int vek)    {        Jmeno = jmeno;        Vek = vek;    }}// Object initializer (diky init-only)var s = new Student("Karel", 25){    Jmeno = "Karel N."  // set funguje};// s.Vek = 30;  // Chyba! init-only nelze menit po konstrukciConsole.WriteLine(s.Dospely);  // True</code></pre>', 'lesson', 4, 15, 15),

(@kurs_id, 'Interfaces a abstraktní třídy', '<h2>Interfaces</h2><p><code>interface</code> definuje kontrakt — metody a properties bez implementace. Třída může implementovat více rozhraní. Od C# 8: <strong>default interface methods</strong>. <code>abstract</code> třída může mít implementaci i abstraktní členy.</p><pre><code>interface IZvire{    string Jmeno { get; }    void Zvuk();    // Default interface method (C# 8)    void Info() => Console.WriteLine($"{Jmeno}");}interface IPohyblivy{    void Pohyb();}// Abstract třída — muze mit implementaciabstract class ZvireBase : IZvire{    public abstract string Jmeno { get; }    public abstract void Zvuk();        public void Jez() => Console.WriteLine("Jim");}// Konkretní třídaclass Pes : ZvireBase, IPohyblivy{    public override string Jmeno => "Pes";    public override void Zvuk() => Console.WriteLine("Haf!");    public void Pohyb() => Console.WriteLine("Bezim!");}// Vyuzitivar z = new Pes();z.Zvuk();   // Haf!z.Pohyb();  // Bezim!z.Jez();    // Jim</code></pre>', 'lesson', 5, 15, 15),

(@kurs_id, 'Generika — constraints, variance (in/out)', '<h2>Generika</h2><p>Generika umožňují psát kód nezávislý na typu: <code>T</code>. <strong>Constraints</strong> omezí typ parametru. <strong>Kovariance</strong> (<code>out</code>) a <strong>kontravariance</strong> (<code>in</code>) pro delegáty a interface.</p><pre><code>// Generická třídaclass Repository<T> where T : class, new(){    private readonly List<T> _items = new();    public void Add(T item) => _items.Add(item);    public T Create() => new T();}// Constraint: kde T : struct (hodnotový typ)//            kde T : class (referenční typ)//            kde T : new() (musí mít bezparam. konstruktor)//            kde T : ISomeInterface// Kovariance — out (C# 4)interface IReader<out T>{    T Read();}// Kontravariance — ininterface IWriter<in T>{    void Write(T item);}// Pouzitirepository = new Repository<Student>();repo.Add(new Student("Karel", 25));</code></pre>', 'lesson', 6, 15, 16),

(@kurs_id, 'LINQ — Where, Select, GroupBy, Aggregate, Zip', '<h2>LINQ (Language Integrated Query)</h2><p>LINQ je vestavěný dotazovací jazyk nad kolekcemi. Metody: <code>Where</code> (filtrování), <code>Select</code> (projekce), <code>GroupBy</code> (seskupení), <code>Aggregate</code> (akumulace), <code>Zip</code> (spojení dvou sekvencí).</p><pre><code>var cisla = new List<int> { 1, 2, 3, 4, 5, 6, 7, 8, 9, 10 };// Where — filtrovanívar suda = cisla.Where(x => x % 2 == 0).ToList();// [2, 4, 6, 8, 10]// Select — projekcevar ctverce = cisla.Select(x => x * x).ToList();// [1, 4, 9, 16, 25, 36, 49, 64, 81, 100]// GroupBy — seskupenívar skupiny = cisla.GroupBy(x => x % 2 == 0 ? "suda" : "licha");foreach (var g in skupiny)    Console.WriteLine($"{g.Key}: {string.Join(",", g)}");// Aggregate — akumulacevar soucin = cisla.Aggregate(1, (acc, x) => acc * x);// Zip — spojeni dvou sekvencívar jmena = new[] { "Karel", "Jana", "Petr" };var veky = new[] { 25, 30, 22 };var osoby = jmena.Zip(veky, (j, v) => $"{j} ({v})");// ["Karel (25)", "Jana (30)", "Petr (22)"]// Query syntaxevar dotaz = from x in cisla             where x > 5             select x * x;</code></pre>', 'lesson', 7, 15, 15),

(@kurs_id, 'Records a Sealed Classes', '<h2>Records (C# 9)</h2><p><code>record</code> je referenční typ s value-semantics: automaticky generuje <code>Equals</code>, <code>GetHashCode</code>, <code>ToString</code>, <code>with</code> expression. <strong>Sealed class</strong> zabraňuje dědičnosti.</p><pre><code>// Positional recordpublic record Bod(double X, double Y);var b1 = new Bod(1, 2);var b2 = new Bod(1, 2);Console.WriteLine(b1 == b2);  // True — value equality// with — non-destructive mutationvar b3 = b1 with { X = 5 };// Bod { X = 5, Y = 2 }// Record struct (C# 10)public record struct Bod3D(double X, double Y, double Z);// Sealed class — nelze děditpublic sealed class Konfigurace{    public string Nazev { get; init; }    private Konfigurace() { }        public static Konfigurace Default => new() { Nazev = "default" };}// Nelze: class MojeKonfig : Konfigurace { }</code></pre><p>Record je ideální pro DTO, immutable data modely. Sealed zabraňuje nežádoucí specializaci a umožňuje kompilátoru optimalizace.</p>', 'lesson', 8, 15, 14),

(@kurs_id, 'async/await a Task — paralelní volání (WhenAll/WhenAny)', '<h2>async/await</h2><p>Asynchronní programování s <code>async</code> a <code>await</code>. <code>Task</code> reprezentuje asynchronní operaci. <code>Task.WhenAll</code> čeká na všechny, <code>Task.WhenAny</code> na první dokončenou. Nikdy nevolej <code>.Result</code> ani <code>.Wait()</code> — hrozí deadlock.</p><pre><code>using System;using System.Net.Http;using System.Threading.Tasks;using System.Collections.Generic;var client = new HttpClient();// Async metodaasync Task<string> FetchAsync(string url){    var response = await client.GetStringAsync(url);    return response;}// WhenAll — paralelní volánívar urls = new[] {    "https://api.example.com/a",    "https://api.example.com/b",    "https://api.example.com/c"};var tasks = urls.Select(url => FetchAsync(url));var results = await Task.WhenAll(tasks);// WhenAny — první dokončenávar first = await Task.WhenAny(tasks);Console.WriteLine(await first);// Task.Run — CPU-bound práce na thread pooluvar vypocet = await Task.Run(() =>{    return Enumerable.Range(1, 1000).Sum();});// CancellationTokenasync Task PraceAsync(CancellationToken ct){    for (int i = 0; i < 100; i++)    {        ct.ThrowIfCancellationRequested();        await Task.Delay(100, ct);    }}</code></pre>', 'lesson', 9, 15, 16),

(@kurs_id, 'Pattern matching pokročile — switch patterns, property patterns, tuple patterns', '<h2>Pokročilý pattern matching</h2><p>C# 7–12 postupně přidává pattern matching: <strong>switch patterns</strong>, <strong>property patterns</strong>, <strong>tuple patterns</strong>, <strong>list patterns</strong> (C# 11). Umožňují deklarativní větvení logiky.</p><pre><code>// Property patternvar bod = (X: 5, Y: 0);var popis = bod switch{    (0, 0) => "Pocatek",    (0, _) => "Osa Y",    (_, 0) => "Osa X",    (> 0, > 0) => "Kvadrant I",    _ => "Jinde"};// Property pattern s objektemclass Objednavka { public string Status { get; set; } public decimal Castka { get; set; } }var o = new Objednavka { Status = "zaplaceno", Castka = 500 };var zprava = o switch{    { Status: "nova" } => "Nova objednavka",    { Status: "zaplaceno", Castka: > 1000 } => "Velka platba",    { Status: "zaplaceno" } => "Platba prijata",    _ => "Neznama"};// List pattern (C# 11)int[] cisla = { 1, 2, 3 };var tip = cisla switch{    [] => "Prazdna",    [var jediny] => $"Jedno: {jediny}",    [var a, var b] => $"Dve: {a}, {b}",    [var prvni, .., var posledni] => $"Prvni {prvni}, posledni {posledni}"};// Nested property patternif (o is { Status: "zaplaceno", Castka: > 0 })    Console.WriteLine("Vse v poradku");</code></pre>', 'lesson', 10, 15, 16),

(@kurs_id, 'Dependency Injection v .NET — AddScoped/Singleton/Transient', '<h2>Dependency Injection (DI)</h2><p>Vestavěný DI kontejner v .NET. Tři životnosti: <code>Transient</code> (nová instance pokaždé), <code>Scoped</code> (jedna instance per request), <code>Singleton</code> (jedna instance celou aplikaci). Konstruktorová injekce je výchozí.</p><pre><code>// Interface a implementacepublic interface IRepo<T>{    Task<T?> GetByIdAsync(int id);    Task AddAsync(T item);    // ...}public class InMemoryRepo<T> : IRepo<T> where T : class{    private readonly List<T> _items = new();    public Task<T?> GetByIdAsync(int id) => Task.FromResult(_items.ElementAtOrDefault(id));    public Task AddAsync(T item) { _items.Add(item); return Task.CompletedTask; }}// Registrace v Program.csvar builder = WebApplication.CreateBuilder(args);builder.Services.AddTransient<IRepo<Student>, InMemoryRepo<Student>>();builder.Services.AddScoped<IEmailService, SmtpEmailService>();builder.Services.AddSingleton<ICache, MemoryCache>();// Konstruktorova injekcepublic class StudentService{    private readonly IRepo<Student> _repo;    private readonly IEmailService _email;    public StudentService(IRepo<Student> repo, IEmailService email)    {        _repo = repo;        _email = email;    }    public async Task RegisterAsync(Student s)    {        await _repo.AddAsync(s);        await _email.SendAsync(s.Email, "Vitej!");    }}</code></pre>', 'lesson', 11, 15, 15),

(@kurs_id, 'Entity Framework Core — DbContext, LINQ dotazy, migrace', '<h2>Entity Framework Core</h2><p>ORM pro .NET — mapuje C# třídy na databázové tabulky. <code>DbContext</code> je centrální třída. LINQ dotazy se překládají do SQL. Migrace udržují schéma databáze.</p><pre><code>using Microsoft.EntityFrameworkCore;// Entitapublic class Student{    public int Id { get; set; }    public string Jmeno { get; set; } = "";    public int Rocnik { get; set; }}// DbContextpublic class AppDbContext : DbContext{    public DbSet<Student> Students => Set<Student>();    public AppDbContext(DbContextOptions<AppDbContext> options)        : base(options) { }    protected override void OnModelCreating(ModelBuilder mb)    {        mb.Entity<Student>().HasIndex(s => s.Jmeno);    }}// Registrace v Program.csbuilder.Services.AddDbContext<AppDbContext>(o =>    o.UseSqlServer(builder.Configuration.GetConnectionString("Default")));// LINQ dotazyawait using var db = new AppDbContext(options);var studenti = await db.Students    .Where(s => s.Rocnik > 1)    .OrderBy(s => s.Jmeno)    .ToListAsync();// Insertdb.Students.Add(new Student { Jmeno = "Karel", Rocnik = 2 });await db.SaveChangesAsync();// Migrace (CLI)// dotnet ef migrations add InitCreate// dotnet ef database update</code></pre>', 'lesson', 12, 15, 16),

(@kurs_id, 'Testování — xUnit, Moq, FluentAssertions', '<h2>xUnit</h2><p>Nejrozšířenější testovací framework pro .NET. <code>[Fact]</code> pro jeden test, <code>[Theory]</code> + <code>[InlineData]</code> pro parametrizované. <strong>Moq</strong> vytváří mock objekty, <strong>FluentAssertions</strong> zlepšuje čitelnost assertů.</p><pre><code>using Xunit;using Moq;using FluentAssertions;// Třída k testovánípublic class Kalkulacka{    public int Secti(int a, int b) => a + b;    public int Vydel(int a, int b)    {        if (b == 0) throw new DivideByZeroException();        return a / b;    }}// Testovací třídapublic class KalkulackaTests{    [Fact]    public void Secti_2Plus3_Vraci5()    {        var k = new Kalkulacka();        var vysledek = k.Secti(2, 3);        vysledek.Should().Be(5);    }    [Theory]    [InlineData(1, 2, 3)]    [InlineData(0, 0, 0)]    [InlineData(-1, 1, 0)]    public void Secti_Parametry(int a, int b, int ocekavano)    {        var k = new Kalkulacka();        k.Secti(a, b).Should().Be(ocekavano);    }    [Fact]    public void Vydel_Nulou_Vyjimka()    {        var k = new Kalkulacka();        var act = () => k.Vydel(10, 0);        act.Should().Throw<DivideByZeroException>();    }    [Fact]    public void Mock_Repository()    {        var mock = new Mock<IRepo<Student>>();        mock.Setup(r => r.GetByIdAsync(1))            .ReturnsAsync(new Student { Jmeno = "Karel" });        var service = new StudentService(mock.Object);        var result = service.GetById(1);        result.Jmeno.Should().Be("Karel");        mock.Verify(r => r.GetByIdAsync(1), Times.Once);    }}</code></pre>', 'lesson', 13, 15, 16),

(@kurs_id, 'ASP.NET Core Minimal API — MapGet/MapPost', '<h2>Minimal API</h2><p>Od .NET 6: Minimal API — definuj endpointy přímo v <code>Program.cs</code> bez controllerů. <code>MapGet</code>, <code>MapPost</code>, <code>MapPut</code>, <code>MapDelete</code>. Typované parametry, validace, DI.</p><pre><code>var builder = WebApplication.CreateBuilder(args);builder.Services.AddEndpointsApiExplorer();builder.Services.AddSwaggerGen();builder.Services.AddSingleton<IRepo<Student>, InMemoryRepo<Student>>();var app = builder.Build();app.UseSwagger();app.UseSwaggerUI();// GET — seznamapp.MapGet("/api/students", async (IRepo<Student> repo) =>    await repo.GetAllAsync());// GET — dle IDapp.MapGet("/api/students/{id:int}", async (int id, IRepo<Student> repo) =>{    var s = await repo.GetByIdAsync(id);    return s is null ? Results.NotFound() : Results.Ok(s);});// POST — vytvořeníapp.MapPost("/api/students", async (Student student, IRepo<Student> repo) =>{    await repo.AddAsync(student);    return Results.Created($"/api/students/{student.Id}", student);});// DELETEapp.MapDelete("/api/students/{id:int}", async (int id, IRepo<Student> repo) =>{    await repo.DeleteAsync(id);    return Results.NoContent();});app.Run();</code></pre>', 'lesson', 14, 15, 16),

(@kurs_id, 'Middleware a pipeline', '<h2>Middleware pipeline</h2><p>Každý request prochází řetězcem middleware komponent. <code>app.Use()</code> přidá vlastní middleware. Pořadí záleží! Vestavěné: <code>UseAuthentication</code>, <code>UseAuthorization</code>, <code>UseCors</code>, <code>UseExceptionHandler</code>.</p><pre><code>var builder = WebApplication.CreateBuilder(args);var app = builder.Build();// Vlastní middleware — logování časuapp.Use(async (context, next) =>{    var sw = System.Diagnostics.Stopwatch.StartNew();    Console.WriteLine($"--> {context.Request.Method} {context.Request.Path}");    await next();  // předat dalšímu middleware    sw.Stop();    Console.WriteLine($"<-- {sw.ElapsedMilliseconds}ms {context.Response.StatusCode}");});// Vlastní middleware — třídaapp.UseMiddleware<ErrorHandlingMiddleware>();// Vestavěné middleware (pořadí je důležité!)app.UseExceptionHandler();app.UseCors("AllowAll");app.UseAuthentication();app.UseAuthorization();app.MapGet("/", () => "Ahoj!");app.Run();// Třída middlewarepublic class ErrorHandlingMiddleware{    private readonly RequestDelegate _next;    public ErrorHandlingMiddleware(RequestDelegate next) => _next = next;    public async Task InvokeAsync(HttpContext ctx)    {        try { await _next(ctx); }        catch (Exception ex)        {            ctx.Response.StatusCode = 500;            await ctx.Response.WriteAsJsonAsync(                new { error = ex.Message });        }    }}</code></pre>', 'lesson', 15, 15, 15),

(@kurs_id, 'Options pattern — typovaná konfigurace z appsettings.json', '<h2>Options pattern</h2><p>Typovaná konfigurace z <code>appsettings.json</code> přes třídy. <code>IOptions<T></code> pro neměnné hodnoty, <code>IOptionsMonitor<T></code> pro reload, <code>IOptionsSnapshot<T></code> per-request scoped.</p><pre><code>// appsettings.json// {//   "EmailNastaveni": {//     "SmtpServer": "smtp.example.com",//     "Port": 587,//     "Odesilatel": "noreply@example.com"//   }// }// Konfigurační třídapublic class EmailNastaveni{    public string SmtpServer { get; set; } = "";    public int Port { get; set; }    public string Odesilatel { get; set; } = "";}// Registrace v Program.csbuilder.Services.Configure<EmailNastaveni>(    builder.Configuration.GetSection("EmailNastaveni"));// Použití přes injekcipublic class EmailService{    private readonly EmailNastaveni _cfg;    public EmailService(IOptions<EmailNastaveni> options)    {        _cfg = options.Value;    }    public void Odeslat(string komu, string predmet)    {        Console.WriteLine($"Odesilam z {_cfg.Odesilatel} " +            $"na {komu} pres {_cfg.SmtpServer}:{_cfg.Port}");    }}// IOptionsMonitor — reload bez restartuvar hodnota = monitor.CurrentValue;// IOptionsSnapshot — ruzne hodnoty per request</code></pre>', 'lesson', 16, 15, 14),

(@kurs_id, 'Blazor intro — komponenty, @code, data binding', '<h2>Blazor</h2><p>Framework pro interaktivní web UI v C# místo JavaScriptu. Dva modely: <strong>Blazor Server</strong> (SignalR) a <strong>Blazor WebAssembly</strong> (běží v prohlížeči). Komponenty jsou <code>.razor</code> soubory s C# a HTML.</p><pre><code><!-- Komponenta: Counter.razor --><h3>Pocitadlo</h3><p>Aktualni pocet: @pocet</p><button @onclick="Zvysit">Zvysit</button>@code {    private int pocet;    private void Zvysit() => pocet++;}<!-- Data binding --><input @bind="jmeno" @bind:event="oninput" /><p>Ahoj, @jmeno!</p>@code {    private string jmeno = "";}<!-- Parametry komponenty --><!-- Child.razor --><div class="card">@ChildContent</div>@code {    [Parameter] public RenderFragment ChildContent { get; set; }}<!-- Pouziti komponenty --><Child>    <p>Toto je obsah uvnitr</p></Child><!-- EventCallback --><button @onclick="OnClick">Klik</button>@code {    [Parameter] public EventCallback OnClick { get; set; }}</code></pre>', 'lesson', 17, 15, 15),

(@kurs_id, 'Span<T> a performance — zero-allocation', '<h2>Span<T></h2><p><code>Span<T></code> je struktura pro práci s kontinuální pamětí bez alokace. Umožňuje slicing polí, stringů a nativní paměti. <code>ReadOnlySpan<T></code> pro čtení. <code>Memory<T></code> pro async kontexty. Ideální pro high-performance scénáře.</p><pre><code>using System;// Span z poleint[] pole = { 1, 2, 3, 4, 5, 6, 7, 8, 9, 10 };Span<int> span = pole.AsSpan();// Slice — pohled na cast pole bez kopieSpan<int> slice = span[3..7];  // { 4, 5, 6, 7 }slice[0] = 99;  // Modifikuje originalni pole!// Span ze stringu — ReadOnlySpanReadOnlySpan<char> text = "Ahoj, VeVit!".AsSpan();ReadOnlySpan<char> pozdrav = text[..4];  // "Ahoj"// Stackalloc — pamet na stacku (bez GC)Span<int> buffer = stackalloc int[256];// Zero-allocation parsingstring vstup = "42";int cislo = int.Parse(vstup);          // alokuje// Bez alokace:if (int.TryParse(vstup, out int vysledek))    Console.WriteLine(vysledek);  // 42// Memory<T> — pro async operaceMemory<int> memory = pole.AsMemory(2, 4);async Task ZpracujAsync(Memory<int> mem){    await Task.Delay(10);    var span = mem.Span;  // ziskani Span z Memory}</code></pre>', 'lesson', 18, 15, 16),

(@kurs_id, 'Source Generators a primary constructors (C# 12)', '<h2>Source Generators</h2><p>Kód, který generuje kód při kompilaci. Implementuje <code>IIncrementalSourceGenerator</code>. Využívá se pro: serializaci (System.Text.Json), DI registrace, logging. <strong>Primary constructors</strong> (C# 12) zkracují definici tříd.</p><pre><code>// Source Generator — zakladyusing Microsoft.CodeAnalysis;using Microsoft.CodeAnalysis.Text;using System.Text;[Generator]public class HelloGenerator : IIncrementalSourceGenerator{    public void Initialize(IncrementalGeneratorInitializationContext ctx)    {        ctx.RegisterPostInitializationOutput(spc =>        {            spc.AddSource("Hello.g.cs", SourceText.From("""                namespace Generated                {                    public static class Hello                    {                        public static string Greet() => "Ahoj z generatoru!";                    }                }                """, Encoding.UTF8));        });    }}// Primary constructors (C# 12) — zkraceny zapis// Pred C# 12:// class Student// {//     private readonly string _jmeno;//     public Student(string jmeno) => _jmeno = jmeno;// }// C# 12 primary constructorclass Student(string jmeno, int vek){    public string Jmeno => jmeno;    public int Vek => vek;    public void Pozdrav() => Console.WriteLine($"{jmeno}, {vek} let");}// Record s primary constructorem (C# 12 zkratka)public record Bod(double X, double Y){    public double Vzdalenost => Math.Sqrt(X * X + Y * Y);}// Primary constructor s DIclass MyController(ILogger<MyController> logger){    [HttpGet]    public string Ping()    {        logger.LogInformation("Ping");        return "Pong";    }}</code></pre>', 'lesson', 19, 15, 16),

(@kurs_id, 'Docker deployment + GitHub Actions CI/CD', '<h2>Docker</h2><p>Zabal .NET aplikaci do Docker kontejneru. Multi-stage build minimalizuje velikost image. <strong>GitHub Actions</strong> automatizuje build, test a deploy (CI/CD pipeline).</p><pre><code>// Dockerfile — multi-stage buildFROM mcr.microsoft.com/dotnet/sdk:8.0 AS buildWORKDIR /srcCOPY *.csproj ./RUN dotnet restoreCOPY . .RUN dotnet publish -c Release -o /appFROM mcr.microsoft.com/dotnet/aspnet:8.0WORKDIR /appCOPY --from=build /app .EXPOSE 8080ENTRYPOINT ["dotnet", "MujProjekt.dll"]// .github/workflows/ci.ymlname: CI/CDon:  push:    branches: [main]  pull_request:    branches: [main]jobs:  build:    runs-on: ubuntu-latest    steps:      - uses: actions/checkout@v4      - uses: actions/setup-dotnet@v4        with:          dotnet-version: ''8.0.x''      - run: dotnet restore      - run: dotnet build --no-restore      - run: dotnet test --no-build --verbosity normal  deploy:    needs: build    runs-on: ubuntu-latest    if: github.ref == ''refs/heads/main''    steps:      - uses: actions/checkout@v4      - name: Build & push Docker        run: |          docker build -t myapp:latest .          docker tag myapp:latest registry.example.com/myapp:latest          docker push registry.example.com/myapp:latest</code></pre><p>Příkazy: <code>docker build -t myapp .</code>, <code>docker run -p 8080:8080 myapp</code>.</p>', 'lesson', 20, 15, 16);


-- ============================================================
-- ZÁVĚREČNÝ KVÍZ (sort_order 21)
-- ============================================================

INSERT INTO lessons (course_id, title, content, lesson_type, sort_order, xp_reward, duration_minutes) VALUES
(@kurs_id, 'Závěrečný kvíz — Celý C# kurz', '<p>Závěrečný test pokrývající všechny lekce kurzu C#.</p>', 'final_quiz', 21, 200, 30);

SET @qfin = LAST_INSERT_ID();

INSERT INTO quizzes (lesson_id, question, option_a, option_b, option_c, option_d, correct_answer, explanation, sort_order) VALUES
(@qfin, 'Co jsou top-level statements v C#?', 'Celočíselné příkazy', 'Zápis kódu bez namespace/class/Main boilerplate', 'Příkazy na nejvyšší úrovni přístupu', 'Linq dotazy', 'b', 'Top-level statements (C# 9+) umožňují psát kód přímo bez obalování do třídy a Main metody.', 1),
(@qfin, 'Co dělá klíčové slovo var v C#?', 'Deklaruje proměnnou typu Variant', 'Odvozuje typ proměnné překladačem', 'Vytváří globální proměnnou', 'Definuje dynamický typ', 'b', 'var umožňuje překladači odvodit typ z pravé strany přiřazení — jde o statický typ.', 2),
(@qfin, 'Co je switch expression v C#?', 'Příkaz switch s break', 'Stručná syntaxe switch vracející hodnotu', 'Výraz pro regex', 'Lambda funkce', 'b', 'Switch expression (C# 8+) je stručná syntaxe s pattern matchingem vracející hodnotu: var x = value switch { ... };', 3),
(@qfin, 'Co znamená init-only setter (C# 9)?', 'Property nelze číst', 'Property lze nastavit pouze při konstrukci objektu', 'Property je vždy null', 'Property je statická', 'b', 'Init-only setter { get; init; } umožňuje přiřazení jen v objektovém inicializéru — po vytvoření je immutable.', 4),
(@qfin, 'Jaký je rozdíl mezi interface a abstract class?', 'Žádný', 'Interface nemůže mít implementaci (kromě default methods), abstract class ano', 'Abstract class nemůže mít konstruktor', 'Interface podporuje dědičnost', 'b', 'Abstract třída může mít implementaci i konstruktor. Interface od C# 8 podporuje default metody, ale ne konstruktor.', 5),
(@qfin, 'Co je LINQ v C#?', 'Linkovací knihovna', 'Vestavěný dotazovací jazyk nad kolekcemi', 'Typ databáze', 'Parser pro XML', 'b', 'LINQ (Language Integrated Query) umožňuje dotazovat kolekce, databáze a XML přímo v C# syntaxi.', 6),
(@qfin, 'Co dělá record s with expression?', 'Smaže záznam', 'Vytvoří kopii záznamu se změněnými hodnotami', 'Změní původní záznam', 'Seřadí záznamy', 'b', 'With expression vytvoří novou kopii recordu s vybranými změněnými vlastnostmi — non-destructive mutation.', 7),
(@qfin, 'Co dělá Task.WhenAll?', 'Čeká na první dokončený task', 'Čeká paralelně na všechny tasks', 'Zruší všechny tasks', 'Vytvoří nový task', 'b', 'Task.WhenAll čeká na dokončení všech tasků paralelně — vrací pole výsledků.', 8),
(@qfin, 'Co je property pattern matching v C#?', 'Porovnání vlastností třídy', 'Větvení logiky dekompozicí vlastností objektu', 'Generování properties', 'Reflexe vlastností', 'b', 'Property pattern umožňuje testovat a dekomponovat vlastnosti objektu: obj is { Status: "ok", Count: > 0 }.', 9),
(@qfin, 'Jaký je rozdíl mezi AddTransient a AddSingleton v DI?', 'Transient je pomalejší', 'Transient vytváří novou instanci pokaždé, Singleton jednu pro celou aplikaci', 'Singleton je thread-unsafe', 'Transient se nepoužívá', 'b', 'Transient = nová instance při každém requestu. Singleton = jedna instance sdílená celou aplikací.', 10);


-- ============================================================
-- Aktualizace počtu lekcí
-- ============================================================

UPDATE courses SET lesson_count = (SELECT COUNT(*) FROM lessons WHERE course_id = @kurs_id) WHERE id = @kurs_id;