-- Go kurz — Kompletní kurz (20 lekcí + závěrečný kvíz)
-- MariaDB 10.4, phpMyAdmin style, no DELIMITER
-- Apostrofy escapovány jako ''

SET @kurs_id = (SELECT id FROM courses WHERE slug = 'golang');

-- ============================================================
-- LEKCE 1–20 (sort_order 1–20)
-- ============================================================

INSERT INTO lessons (course_id, title, content, lesson_type, sort_order, xp_reward, duration_minutes) VALUES
(@kurs_id, 'Úvod do Go', '<h2>Co je Go?</h2><p>Go (Golang) je kompilovaný, staticky typovaný jazyk vytvořený v Google. Vyniká jednoduchostí, rychlostí kompilace a nativní podporou concurrency.</p><h2>Instalace a go mod</h2><p>Stáhni Go z golang.org. Inicializuj projekt příkazem <code>go mod init</code>, který vytvoří soubor <code>go.mod</code> se závislostmi.</p><pre><code>mkdir myapp && cd myapp\ngo mod init github.com/uzivatel/myapp</code></pre><h2>Hello World</h2><p>Každý Go program začíná balíčkem <code>main</code> a funkcí <code>main</code>. Spustíš příkazem <code>go run main.go</code>.</p><pre><code>package main\n\nimport "fmt"\n\nfunc main() {\n    fmt.Println("Ahoj, VeVit!")\n}</code></pre><h2>Základní typy</h2><p>Go má typy: <code>int</code>, <code>float64</code>, <code>string</code>, <code>bool</code>. Proměnné deklaruješ klíčovým slovem <code>var</code> nebo operátorem <code>:=</code>.</p><pre><code>var jmeno string = "Karel"\nvek := 25\nprumer := 4.8\naktivni := true\nfmt.Printf("%s, %d let, aktivni: %t\\n", jmeno, vek, aktivni)</code></pre>', 'lesson', 1, 15, 15),

(@kurs_id, 'Funkce', '<h2>Funkce v Go</h2><p>Funkce deklaruješ klíčovým slovem <code>func</code>. Go podporuje více návratových hodnot, pojmenované návraty a variadic parametry.</p><h2>Více návratových hodnot</h2><p>Go funkce mohou vracet více hodnot najednou — běžně se používá pro návrat hodnoty + chyby.</p><pre><code>func deleni(a, b float64) (float64, error) {\n    if b == 0 {\n        return 0, fmt.Errorf("deleni nulou")\n    }\n    return a / b, nil\n}\n\nvysledek, err := deleni(10, 3)\nif err != nil {\n    log.Fatal(err)\n}</code></pre><h2>Named returns</h2><p>Pojmenované návratové hodnoty se inicializují nulovou hodnotou a vracejí se automaticky pomocí <code>return</code> bez argumentů.</p><pre><code>func souradnice() (x, y int) {\n    x = 10\n    y = 20\n    return\n}\n</code></pre><h2>Variadic funkce</h2><p>Poslední parametr může přijmout libovolný počet argumentů pomocí <code>...T</code>.</p><pre><code>func soucet(cisla ...int) int {\n    total := 0\n    for _, c := range cisla {\n        total += c\n    }\n    return total\n}\nfmt.Println(soucet(1, 2, 3))  // 6</code></pre>', 'lesson', 2, 15, 15),

(@kurs_id, 'Structs a interfaces', '<h2>Structs</h2><p>Struct je kolekce pojmenovaných polí — Go alternativa k třídám bez dědičnosti. Vytvoříš klíčovým slovem <code>type</code>.</p><pre><code>type Uzivatel struct {\n    Jmeno string\n    Vek   int\n}\n\nu := Uzivatel{Jmeno: "Karel", Vek: 25}\nfmt.Println(u.Jmeno)</code></pre><h2>Metody</h2><p>Metoda je funkce s receiverem. Pointer receiver umožňuje modifikovat struct.</p><pre><code>func (u *Uzivatel) Narozeniny() {\n    u.Vek++\n}\nu.Narozeniny()\nfmt.Println(u.Vek)  // 26</code></pre><h2>Interfaces a duck typing</h2><p>Interface definuje sadu metod. Typ implementuje interface implicitně — žádné <code>implements</code>.</p><pre><code>type Psac interface {\n    Pis(text string) string\n}\n\ntypewriter struct{}\nfunc (t typewriter) Pis(text string) string {\n    return text\n}\n// typewriter automaticky implementuje Psac</code></pre><h2>Embedding</h2><p>Struct může vložit jiný struct — získá jeho pole a metody.</p><pre><code>type Zamestnanec struct {\n    Uzivatel  // embedding\n    Pozice string\n}\n\nz := Zamestnanec{Uzivatel: Uzivatel{Jmeno: "Karel"}, Pozice: "dev"}\nfmt.Println(z.Jmeno)  // Karel</code></pre>', 'lesson', 3, 15, 15),

(@kurs_id, 'Error handling', '<h2>Error handling v Go</h2><p>Go nemá výjimky. Chyby jsou hodnoty typu <code>error</code> vracené jako poslední návratová hodnota. Vždy kontroluj <code>err != nil</code>.</p><h2>Základní pattern</h2><pre><code>f, err := os.Open("data.txt")\nif err != nil {\n    return fmt.Errorf("otevreni souboru: %w", err)\n}\ndefer f.Close()</code></pre><h2>Custom errors</h2><p>Vytvoř vlastní typ chyby implementací interface <code>error</code>.</p><pre><code>type ChybaValidace struct {\n    Pole   string\n    Hodnota string\n}\n\nfunc (e ChybaValidace) Error() string {\n    return fmt.Sprintf("validace selhala: pole %s = %s", e.Pole, e.Hodnota)\n}</code></pre><h2>errors.As a errors.Is</h2><p><code>errors.Is</code> porovnává chybu s konkrétní hodnotou. <code>errors.As</code> extrahuje typ chyby.</p><pre><code>var ErrNenalezen = errors.New("nenalezen")\n\nerr := najdi(42)\nif errors.Is(err, ErrNenalezen) {\n    fmt.Println("Zaznam neexistuje")\n}\n\nvar valErr ChybaValidace\nif errors.As(err, &valErr) {\n    fmt.Println(valErr.Pole)\n}</code></pre><h2>fmt.Errorf %w</h2><p>Formátovací příkaz <code>%w</code> zabalí chybu a umožní její rozbalení pomocí <code>errors.Is/As</code>.</p><pre><code>func nacti(path string) ([]byte, error) {\n    data, err := os.ReadFile(path)\n    if err != nil {\n        return nil, fmt.Errorf("nacteni %s: %w", path, err)\n    }\n    return data, nil\n}</code></pre>', 'lesson', 4, 15, 15),

(@kurs_id, 'Goroutines', '<h2>Goroutines</h2><p>Goroutine je lehké vlákno spravované Go runtime. Spustíš ji klíčovým slovem <code>go</code> před voláním funkce.</p><pre><code>func pozdrav(jmeno string) {\n    fmt.Printf("Ahoj, %s!\\n", jmeno)\n}\n\ngo pozdrav("Karel")\ngo func() {\n    fmt.Println("Anonymni goroutine")\n}()</code></pre><h2>WaitGroup</h2><p><code>sync.WaitGroup</code> čeká na dokončení skupiny goroutin. <code>Add</code> přidá čítač, <code>Done</code> sníží, <code>Wait</code> blokuje.</p><pre><code>var wg sync.WaitGroup\n\nfor i := 0; i < 5; i++ {\n    wg.Add(1)\n    go func(id int) {\n        defer wg.Done()\n        fmt.Printf("Goroutine %d\\n", id)\n    }(i)\n}\nwg.Wait()\nfmt.Println("Vse dokonceno")</code></pre><h2>Důležité pravidlo</h2><p>Nikdy nečti proměnnou z closure v goroutině bez předání parametrem — jinak získáš poslední hodnotu smyčky.</p><pre><code>// SPATNE:\nfor i := 0; i < 3; i++ {\n    go func() { fmt.Println(i) }()  // i se zmeni!\n}\n// SPRAVNE:\nfor i := 0; i < 3; i++ {\n    go func(n int) { fmt.Println(n) }(i)\n}</code></pre>', 'lesson', 5, 15, 15),

(@kurs_id, 'Channels', '<h2>Channels</h2><p>Channel je typovaný kanál pro komunikaci mezi goroutinami. Vytvoříš pomocí <code>make(chan T)</code>.</p><h2>Unbuffered channels</h2><p>Unbuffered channel blokuje dokud druhá strana neprovede odeslání/přijetí.</p><pre><code>ch := make(chan string)\n\ngo func() {\n    ch <- "zprava"  // odeslani (blokuje dokud nekdo neprecte)\n}()\n\nmsg := <-ch  // prijeti (blokuje dokud neci neprijde)\nfmt.Println(msg)</code></pre><h2>Buffered channels</h2><p>Buffered channel má kapacitu — neblokuje dokud není plný.</p><pre><code>ch := make(chan int, 3)\nch <- 1\nch <- 2\nch <- 3\n// ch <- 4 by blokoval\nfmt.Println(len(ch), cap(ch))  // 3 3</code></pre><h2>select</h2><p><code>select</code> čeká na více kanálů najednou — vybere první připravený operaci.</p><pre><code>select {\ncase msg := <-ch1:\n    fmt.Println("ch1:", msg)\ncase msg := <-ch2:\n    fmt.Println("ch2:", msg)\ncase <-time.After(time.Second):\n    fmt.Println("Timeout!")\n}</code></pre><h2>Context cancellation</h2><p><code>context.WithCancel</code> umožňuje zrušit goroutinu signálem.</p><pre><code>ctx, cancel := context.WithCancel(context.Background())\ndefer cancel()\n\ngo func(ctx context.Context) {\n    for {\n        select {\n        case <-ctx.Done():\n            fmt.Println("Koncim")\n            return\n        default:\n            time.Sleep(100 * time.Millisecond)\n        }\n    }\n}(ctx)\n\ntime.Sleep(300 * time.Millisecond)\ncancel()</code></pre>', 'lesson', 6, 15, 15),

(@kurs_id, 'HTTP server', '<h2>HTTP server v Go</h2><p>Balíček <code>net/http</code> poskytuje plnohodnotný HTTP server bez jakéhokoliv frameworku. Registrace handleru přes <code>http.HandleFunc</code>.</p><pre><code>package main\n\nimport (\n    "fmt"\n    "net/http"\n)\n\nfunc main() {\n    http.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {\n        fmt.Fprintf(w, "Ahoj, VeVit!")\n    })\n\n    http.HandleFunc("/api/status", func(w http.ResponseWriter, r *http.Request) {\n        w.Header().Set("Content-Type", "application/json")\n        fmt.Fprintf(w, `{"status": "ok"}`)\n    })\n\n    fmt.Println("Server bezi na :8080")\n    log.Fatal(http.ListenAndServe(":8080", nil))\n}</code></pre><h2>http.Handler interface</h2><p>Pokud potřebuješ stav, implementuj interface <code>http.Handler</code> s metodou <code>ServeHTTP</code>.</p><pre><code>type Server struct {\n    Addr string\n}\n\nfunc (s *Server) ServeHTTP(w http.ResponseWriter, r *http.Request) {\n    fmt.Fprintf(w, "Server na %s", s.Addr)\n}\n\nhttp.Handle("/", &Server{Addr: ":8080"})</code></pre><h2>Obsluha metod</h2><p>Rozliš HTTP metody pro RESTful API.</p><pre><code>func handler(w http.ResponseWriter, r *http.Request) {\n    switch r.Method {\n    case http.MethodGet:\n        fmt.Fprintf(w, "GET pozadavek")\n    case http.MethodPost:\n        body, _ := io.ReadAll(r.Body)\n        fmt.Fprintf(w, "POST: %s", body)\n    default:\n        w.WriteHeader(http.StatusMethodNotAllowed)\n    }\n}</code></pre>', 'lesson', 7, 15, 15),

(@kurs_id, 'Gin framework', '<h2>Gin framework</h2><p>Gin je nejpopulárnější Go webový framework. Nabízí rychlý routing, binding, validaci a middleware.</p><h2>Základní routing</h2><pre><code>package main\n\nimport "github.com/gin-gonic/gin"\n\nfunc main() {\n    r := gin.Default()\n\n    r.GET("/", func(c *gin.Context) {\n        c.JSON(200, gin.H{"zprava": "Ahoj"})\n    })\n\n    r.GET("/uzivatele/:id", func(c *gin.Context) {\n        id := c.Param("id")\n        c.JSON(200, gin.H{"id": id})\n    })\n\n    r.Run(":8080")\n}</code></pre><h2>Binding</h2><p>Gin automaticky naparsuje a zvaliduje JSON vstup pomocí tagů.</p><pre><code>type Login struct {\n    Email    string `json:"email" binding:"required,email"`\n    Heslo    string `json:"heslo" binding:"required,min=6"`\n}\n\nr.POST("/login", func(c *gin.Context) {\n    var req Login\n    if err := c.ShouldBindJSON(&req); err != nil {\n        c.JSON(400, gin.H{"error": err.Error()})\n        return\n    }\n    c.JSON(200, gin.H{"email": req.Email})\n})</code></pre><h2>Middleware</h2><p>Middleware se provede před nebo po handleru. Použij <code>r.Use()</code> pro globální, nebo <code>r.Group()</code> pro skupinu.</p><pre><code>func Logger() gin.HandlerFunc {\n    return func(c *gin.Context) {\n        start := time.Now()\n        c.Next()  // pokracuj k handleru\n        fmt.Printf("%s %s %v\\n", c.Request.Method, c.Request.URL, time.Since(start))\n    }\n}\n\nr.Use(Logger())\napi := r.Group("/api", Logger())\napi.GET("/data", handler)</code></pre>', 'lesson', 8, 15, 15),

(@kurs_id, 'Databáze', '<h2>database/sql</h2><p>Balíček <code>database/sql</code> poskytuje abstraktní rozhraní pro SQL databáze. Kombinuj s driverem (např. <code>github.com/lib/pq</code> pro PostgreSQL).</p><pre><code>import (\n    "database/sql"\n    _ "github.com/lib/pq"\n)\n\ndb, err := sql.Open("postgres", "postgres://user:pass@localhost/db?sslmode=disable")\nif err != nil {\n    log.Fatal(err)\n}\ndefer db.Close()</code></pre><h2>sqlx</h2><p>Knihovna <code>sqlx</code> rozšiřuje <code>database/sql</code> o snadné mapování řádků na structy.</p><pre><code>import "github.com/jmoiron/sqlx"\n\ntype Uzivatel struct {\n    ID    int    `db:"id"`\n    Jmeno string `db:"jmeno"`\n}\n\ndb, _ := sqlx.Connect("postgres", dsn)\n\nvar uzivatele []Uzivatel\ndb.Select(&uzivatele, "SELECT id, jmeno FROM uzivatele WHERE vek > $1", 18)\n\nvar u Uzivatel\ndb.Get(&u, "SELECT * FROM uzivatele WHERE id = $1", 1)</code></pre><h2>Transakce</h2><p>Transakce zaručují atomicitu — buď se provedou všechny operace, nebo žádná.</p><pre><code>tx, err := db.Begin()\nif err != nil {\n    return err\n}\n\n_, err = tx.Exec("INSERT INTO objednavky (user_id) VALUES ($1)", userID)\nif err != nil {\n    tx.Rollback()\n    return err\n}\n\n_, err = tx.Exec("UPDATE uzivatele SET objednavky = objednavky + 1 WHERE id = $1", userID)\nif err != nil {\n    tx.Rollback()\n    return err\n}\n\nreturn tx.Commit()</code></pre>', 'lesson', 9, 15, 15),

(@kurs_id, 'Testování', '<h2>Testování v Go</h2><p>Go má vestavěný testovací framework. Testy jsou v souborech s příponou <code>_test.go</code>, funkce začínají prefixem <code>Test</code>.</p><h2>Základní test</h2><pre><code>// math_test.go\npackage math\n\nimport "testing"\n\nfunc TestSoucet(t *testing.T) {\n    vysledek := Soucet(2, 3)\n    if vysledek != 5 {\n        t.Errorf("Soucet(2,3) = %d, chceme 5", vysledek)\n    }\n}</code></pre><h2>Table-driven testy</h2><p>Nejlepší pattern pro Go testy — data v slice struct, iterace přes případy.</p><pre><code>func TestDeleni(t *testing.T) {\n    tests := []struct {\n        a, b, want int\n    }{\n        {10, 2, 5},\n        {9, 3, 3},\n        {0, 1, 0},\n    }\n    for _, tt := range tests {\n        if got := Deleni(tt.a, tt.b); got != tt.want {\n            t.Errorf("Deleni(%d,%d) = %d, chceme %d", tt.a, tt.b, got, tt.want)\n        }\n    }\n}</code></pre><h2>testify</h2><p>Knihovna <code>testify</code> nabízí asserty a mocky s lepší čitelností.</p><pre><code>import "github.com/stretchr/testify/assert"\n\nfunc TestSoucet(t *testing.T) {\n    assert.Equal(t, 5, Soucet(2, 3))\n    assert.NoError(t, nil)\n}</code></pre><h2>Benchmarks</h2><p>Benchmarky měří výkon. Spustíš příkazem <code>go test -bench=. -benchmem</code>.</p><pre><code>func BenchmarkFibonacci(b *testing.B) {\n    for i := 0; i < b.N; i++ {\n        Fibonacci(20)\n    }\n}</code></pre>', 'lesson', 10, 15, 15),

(@kurs_id, 'Generika (Go 1.18+)', '<h2>Generika v Go</h2><p>Od verze Go 1.18 podporuje generika — parametry typů pro funkce a typy. Umožňují psát obecný kód bez <code>interface{}</code>.</p><h2>Constraints</h2><p>Constraint omezuje, které typy jsou povoleny. Vestavěné: <code>any</code>, <code>comparable</code>. Vlastní s <code>interface</code>.</p><pre><code>type Number interface {\n    int | int64 | float64\n}\n\nfunc Soucet[T Number](cisla []T) T {\n    var total T\n    for _, c := range cisla {\n        total += c\n    }\n    return total\n}\n\nfmt.Println(Soucet([]int{1, 2, 3}))        // 6\nfmt.Println(Soucet([]float64{1.5, 2.5}))  // 4</code></pre><h2>Generic funkce</h2><p>Funkce s typovým parametrem <code>[T constraint]</code> za názvem.</p><pre><code>func Obsahuje[T comparable](slice []T, hodnota T) bool {\n    for _, v := range slice {\n        if v == hodnota {\n            return true\n        }\n    }\n    return false\n}\n\nfmt.Println(Obsahuje([]string{"a","b"}, "b"))  // true\nfmt.Println(Obsahuje([]int{1,2,3}, 5))         // false</code></pre><h2>Generic struktury</h2><pre><code>type Par[K comparable, V any] struct {\n    Klic   K\n    Hodnota V\n}\n\np := Par[string, int]{Klic: "vek", Hodnota: 25}\nfmt.Println(p.Klic, p.Hodnota)</code></pre>', 'lesson', 11, 15, 15),

(@kurs_id, 'JSON a HTTP klient', '<h2>encoding/json</h2><p>Balíček <code>encoding/json</code> převádí Go hodnoty na JSON a zpět. Použij struct tagy <code>json:"nazev"</code>.</p><h2>Marshaling a Unmarshaling</h2><pre><code>type Uzivatel struct {\n    Jmeno string `json:"jmeno"`\n    Vek   int    `json:"vek"`\n}\n\nu := Uzivatel{Jmeno: "Karel", Vek: 25}\ndata, _ := json.Marshal(u)\nfmt.Println(string(data))  // {"jmeno":"Karel","vek":25}\n\nvar u2 Uzivatel\njson.Unmarshal(data, &u2)\nfmt.Println(u2.Jmeno)  // Karel</code></pre><h2>http.Client</h2><p>Balíček <code>net/http</code> poskytuje HTTP klienta. Vždy nastav <code>Timeout</code> a použij <code>defer resp.Body.Close()</code>.</p><pre><code>client := &http.Client{Timeout: 10 * time.Second}\n\nresp, err := client.Get("https://api.example.com/data")\nif err != nil {\n    log.Fatal(err)\n}\ndefer resp.Body.Close()\n\nbody, _ := io.ReadAll(resp.Body)\nfmt.Println(string(body))</code></pre><h2>POST s JSON</h2><pre><code>data, _ := json.Marshal(map[string]string{"jmeno": "Karel"})\nresp, err := client.Post(\n    "https://api.example.com/users",\n    "application/json",\n    bytes.NewBuffer(data),\n)\ndefer resp.Body.Close()</code></pre>', 'lesson', 12, 15, 15),

(@kurs_id, 'Context', '<h2>Context v Go</h2><p>Balíček <code>context</code> slouží k předávání deadline, zrušení a hodnot přes API hranice. První parametr funkcí: <code>ctx context.Context</code>.</p><h2>WithTimeout</h2><p>Nastaví časový limit — po vypršení se ctx.Done() zavře.</p><pre><code>ctx, cancel := context.WithTimeout(context.Background(), 3*time.Second)\ndefer cancel()\n\nresult, err := fetchWithCtx(ctx, "https://api.example.com")\nif err != nil {\n    if ctx.Err() == context.DeadlineExceeded {\n        fmt.Println("Timeout!")\n    }\n}</code></pre><h2>WithCancel</h2><p>Ruší všechny goroutiny sdílející context.</p><pre><code>ctx, cancel := context.WithCancel(context.Background())\n\ngo func(ctx context.Context) {\n    for {\n        select {\n        case <-ctx.Done():\n            fmt.Println("Goroutine ukoncena")\n            return\n        default:\n            pracuj()\n        }\n    }\n}(ctx)\n\ntime.Sleep(1 * time.Second)\ncancel()  // ukonci goroutine</code></pre><h2>Propagace přes goroutines</h2><p>Context se předává jako parametr — potomci dědí zrušení.</p><pre><code>func fetchWithCtx(ctx context.Context, url string) ([]byte, error) {\n    req, _ := http.NewRequestWithContext(ctx, "GET", url, nil)\n    resp, err := http.DefaultClient.Do(req)\n    if err != nil {\n        return nil, err\n    }\n    defer resp.Body.Close()\n    return io.ReadAll(resp.Body)\n}</code></pre>', 'lesson', 13, 15, 15),

(@kurs_id, 'Middleware pattern', '<h2>Middleware pattern v Go</h2><p>Middleware je funkce, která obaluje handler — provede logiku před a/nebo po hlavním zpracování.</p><h2>func(Handler) Handler</h2><p>Standardní Go pattern: middleware přijme <code>http.Handler</code> a vrátí nový <code>http.Handler</code>.</p><pre><code>func Logging(next http.Handler) http.Handler {\n    return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {\n        start := time.Now()\n        next.ServeHTTP(w, r)\n        log.Printf("%s %s %v", r.Method, r.URL.Path, time.Since(start))\n    })\n}\n\nhandler := Logging(http.HandlerFunc(homeHandler))\nhttp.Handle("/", handler)</code></pre><h2>Řetězení middleware</h2><p>Více middleware zřetězíš do pořadí zvenku dovnitř.</p><pre><code>func Chain(h http.Handler, mws ...func(http.Handler) http.Handler) http.Handler {\n    for i := len(mws) - 1; i >= 0; i-- {\n        h = mws[i](h)\n    }\n    return h\n}\n\nhandler := Chain(\n    http.HandlerFunc(homeHandler),\n    Logging,\n    Auth,\n    Recovery,\n)</code></pre><h2>Gin middleware</h2><p>V Ginu použij <code>c.Next()</code> pro předání dalšímu handleru.</p><pre><code>func AuthMiddleware() gin.HandlerFunc {\n    return func(c *gin.Context) {\n        token := c.GetHeader("Authorization")\n        if token == "" {\n            c.AbortWithStatusJSON(401, gin.H{"error": "Neautorizovano"})\n            return\n        }\n        c.Next()\n    }\n}</code></pre>', 'lesson', 14, 15, 15),

(@kurs_id, 'Go embed', '<h2>Go embed</h2><p>Od Go 1.16 můžeš vkládat statické soubory přímo do binárky pomocí <code>//go:embed</code>. Ideální pro single-binary nasazení.</p><h2>Vložení souboru</h2><pre><code>package main\n\nimport (\n    "embed"\n    "fmt"\n)\n\n//go:embed hello.txt\nvar pozdrav string\n\nfunc main() {\n    fmt.Println(pozdrav)\n}</code></pre><h2>Vložení adresáře</h2><p><code>embed.FS</code> umožňuje vložit celý adresář a přistupovat k souborům jako k filesystému.</p><pre><code>//go:embed static/*\nvar staticFiles embed.FS\n\nfunc main() {\n    data, _ := staticFiles.ReadFile("static/index.html")\n    fmt.Println(string(data))\n}</code></pre><h2>HTTP server s embed</h2><p>Obsluhuj statické soubory bez externího filesystému.</p><pre><code>//go:embed dist/*\nvar distFS embed.FS\n\nfunc main() {\n    mux := http.NewServeMux()\n    mux.Handle("/", http.FileServer(http.FS(distFS)))\n    http.ListenAndServe(":8080", mux)\n}</code></pre>', 'lesson', 15, 15, 15),

(@kurs_id, 'Generics pokročile', '<h2>Pokročilé generika v Go</h2><p>Nad rámec základních generik — implementuj obecné datové struktury a funkce vyššího řádu.</p><h2>Stack[T]</h2><pre><code>type Stack[T any] struct {\n    items []T\n}\n\nfunc (s *Stack[T]) Push(v T) {\n    s.items = append(s.items, v)\n}\n\nfunc (s *Stack[T]) Pop() (T, bool) {\n    if len(s.items) == 0 {\n        var zero T\n        return zero, false\n    }\n    idx := len(s.items) - 1\n    v := s.items[idx]\n    s.items = s.items[:idx]\n    return v, true\n}\n\ns := Stack[int]{}\ns.Push(10)\ns.Push(20)\nv, ok := s.Pop()  // 20, true</code></pre><h2>Filter[T]</h2><pre><code>func Filter[T any](slice []T, pred func(T) bool) []T {\n    var result []T\n    for _, v := range slice {\n        if pred(v) {\n            result = append(result, v)\n        }\n    }\n    return result\n}\n\nsuda := Filter([]int{1,2,3,4,5,6}, func(n int) bool {\n    return n%2 == 0\n})\n// [2, 4, 6]</code></pre><h2>Map[T]</h2><pre><code>func Map[T any, U any](slice []T, fn func(T) U) []U {\n    result := make([]U, len(slice))\n    for i, v := range slice {\n        result[i] = fn(v)\n    }\n    return result\n}\n\nctverce := Map([]int{1,2,3}, func(n int) int {\n    return n * n\n})\n// [1, 4, 9]</code></pre>', 'lesson', 16, 15, 15),

(@kurs_id, 'gRPC', '<h2>gRPC v Go</h2><p>gRPC je vysoce výkonný RPC framework od Google. Používá Protocol Buffers pro serializaci a HTTP/2 pro transport.</p><h2>Protobuf definice</h2><pre><code>// users.proto\nsyntax = "proto3";\npackage users;\n\nservice Users {\n    rpc GetUser(GetUserReq) returns (User);\n    rpc ListUsers(ListReq) returns (stream User);\n}\n\nmessage User {\n    int32 id = 1;\n    string jmeno = 2;\n    string email = 3;\n}\n\nmessage GetUserReq {\n    int32 id = 1;\n}\n\nmessage ListReq {}</code></pre><h2>Generování kódu</h2><pre><code>protoc --go_out=. --go-grpc_out=. users.proto</code></pre><h2>Server implementace</h2><pre><code>type Server struct {\n    pb.UnimplementedUsersServer\n}\n\nfunc (s *Server) GetUser(ctx context.Context, req *pb.GetUserReq) (*pb.User, error) {\n    return &pb.User{Id: req.Id, Jmeno: "Karel"}, nil\n}\n\nfunc main() {\n    lis, _ := net.Listen("tcp", ":50051")\n    s := grpc.NewServer()\n    pb.RegisterUsersServer(s, &Server{})\n    log.Fatal(s.Serve(lis))\n}</code></pre><h2>Klient implementace</h2><pre><code>conn, _ := grpc.Dial("localhost:50051", grpc.WithInsecure())\ndefer conn.Close()\nclient := pb.NewUsersClient(conn)\n\nuser, _ := client.GetUser(context.Background(), &pb.GetUserReq{Id: 1})\nfmt.Println(user.Jmeno)</code></pre>', 'lesson', 17, 15, 15),

(@kurs_id, 'Profiling', '<h2>Profiling v Go</h2><p>Go má vestavěný nástroj <code>pprof</code> pro analýzu výkonu — CPU, heap, goroutines, block.</p><h2>Základní CPU profil</h2><pre><code>import "runtime/pprof"\n\nf, _ := os.Create("cpu.prof")\npprof.StartCPUProfile(f)\ndefer pprof.StopCPUProfile()\n\n// tvuj kod zde\nfor i := 0; i < 1000000; i++ {\n    fibonacci(20)\n}</code></pre><h2>Heap profil</h2><pre><code>f, _ := os.Create("heap.prof")\ndefer f.Close()\n\nruntime.GC()  // vynuti GC\npprof.WriteHeapProfile(f)</code></pre><h2>HTTP endpoint</h2><p>Pro běžící server přidej pprof endpoint pro živou analýzu.</p><pre><code>import _ "net/http/pprof"\n\ngo func() {\n    log.Println(http.ListenAndServe("localhost:6060", nil))\n}()\n\n// Pak analyzuj:\n// go tool pprof http://localhost:6060/debug/pprof/profile\n// go tool pprof http://localhost:6060/debug/pprof/heap</code></pre><h2>Analýza</h2><pre><code>go tool pprof cpu.prof\n\n# Interaktivni prikazy:\n# top20      — top 20 funkcic\n# list func  — zdrojak s annotaci\n# web        — graf v prohlizeci</code></pre>', 'lesson', 18, 15, 15),

(@kurs_id, 'Docker multi-stage', '<h2>Docker multi-stage build</h2><p>Go se skvěle hodí pro Docker — kompiluje se do statické binárky. Multi-stage build vytvoří minimální image.</p><h2>Dockerfile</h2><pre><code># Stage 1: Build\nFROM golang:1.21-alpine AS builder\nWORKDIR /app\ncopy go.mod go.sum ./\ngo mod download\nCOPY . .\nRUN CGO_ENABLED=0 GOOS=linux go build -o /server ./cmd/server\n\n# Stage 2: Runtime (scratch)\nFROM scratch\nCOPY --from=builder /server /server\nCOPY --from=builder /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/\nEXPOSE 8080\nENTRYPOINT ["/server"]</code></pre><h2>Proč scratch?</h2><p>Scratch image neobsahuje nic — ani shell. Go binárka je staticky linkovaná, tak nepotřebuje glibc. Výsledek: image o velikosti pár MB.</p><pre><code># Build a push\ndocker build -t myapp:latest .\ndocker images myapp\n# REPOSITORY  TAG     SIZE\n# myapp       latest  5MB</code></pre><h2>Alpine alternativa</h2><p>Pokud potřebuješ shell nebo CA certifikáty, použij alpine.</p><pre><code>FROM alpine:3.19\nRUN apk --no-cache add ca-certificates\nCOPY --from=builder /server /server\nENTRYPOINT ["/server"]</code></pre>', 'lesson', 19, 15, 15),

(@kurs_id, 'Projekt — kompletní microservice', '<h2>Kompletní microservice</h2><p>Vytvoř produkční microservice s graceful shutdown, health checkem a strukturovaným logováním.</p><h2>Hlavní struktura</h2><pre><code>package main\n\nimport (\n    "context"\n    "log"\n    "net/http"\n    "os"\n    "os/signal"\n    "syscall"\n    "time"\n)\n\ntype App struct {\n    server *http.Server\n}\n\nfunc main() {\n    app := &App{\n        server: &http.Server{Addr: ":8080"},\n    }\n    app.routes()\n    app.run()\n}</code></pre><h2>Graceful shutdown</h2><pre><code>func (a *App) run() {\n    go func() {\n        if err := a.server.ListenAndServe(); err != http.ErrServerClosed {\n            log.Fatalf("Server chyba: %v", err)\n        }\n    }()\n\n    quit := make(chan os.Signal, 1)\n    signal.Notify(quit, syscall.SIGINT, syscall.SIGTERM)\n    <-quit\n    log.Println("Vypinam server...")\n\n    ctx, cancel := context.WithTimeout(context.Background(), 10*time.Second)\n    defer cancel()\n\n    if err := a.server.Shutdown(ctx); err != nil {\n        log.Fatalf("Shutdown chyba: %v", err)\n    }\n    log.Println("Server vypnuty")\n}</code></pre><h2>Health check</h2><pre><code>func (a *App) routes() {\n    mux := http.NewServeMux()\n    mux.HandleFunc("/health", func(w http.ResponseWriter, r *http.Request) {\n        w.WriteHeader(http.StatusOK)\n        fmt.Fprintf(w, "OK")\n    })\n    mux.HandleFunc("/api/data", a.handleData)\n    a.server.Handler = mux\n}</code></pre>', 'lesson', 20, 15, 15);


-- ============================================================
-- ZÁVĚREČNÝ KVÍZ (sort_order 21)
-- ============================================================

INSERT INTO lessons (course_id, title, content, lesson_type, sort_order, xp_reward, duration_minutes) VALUES
(@kurs_id, 'Závěrečný kvíz — Celý Go kurz', '<p>Závěrečný test pokrývající všechny sekce kurzu Go.</p>', 'final_quiz', 21, 200, 30);

SET @qfin = LAST_INSERT_ID();

INSERT INTO quizzes (lesson_id, question, option_a, option_b, option_c, option_d, correct_answer, explanation, sort_order) VALUES
(@qfin, 'Jak inicializuješ nový Go modul?', 'go init', 'go mod init', 'go create', 'npm init', 'b', 'Příkaz go mod init vytvoří soubor go.mod se závislostmi projektu.', 1),
(@qfin, 'Co vrací Go funkce s více návratovými hodnotami?', 'Pole', 'Tuple hodnot', 'Mapu', 'Jen jednu hodnotu', 'b', 'Go funkce mohou vracet více hodnot — běžně (hodnota, error).', 2),
(@qfin, 'Jak Go implementuje interface?', 'Klíčovým slovem implements', 'Implicitně — typ implementuje interface automaticky pokud má metody', 'Pomocí extends', 'Pomocí inheritance', 'b', 'Go používá duck typing — typ implementuje interface implicitně, bez klíčového slova implements.', 3),
(@qfin, 'Co dělá fmt.Errorf("chyba: %w", err)?', 'Zaloguje chybu', 'Zabalí chybu pro errors.Is/As', 'Vyhodí panic', 'Ignoruje chybu', 'b', '%w zabalí původní chybu a umožní její rozbalení pomocí errors.Is a errors.As.', 4),
(@qfin, 'Jak spustíš goroutine?', 'async func()', 'go func()', 'thread func()', 'spawn func()', 'b', 'Klíčové slovo go spustí funkci jako lehké vlákno — goroutine.', 5),
(@qfin, 'Co dělá select v Go?', 'Vybere z více case větví', 'Čeká na více kanálů najednou a vybere první připravený', 'Filtruje slice', 'Vybírá z mapy', 'b', 'select čeká na více channel operací a provede první, která je připravena.', 6),
(@qfin, 'Který balíček použiješ pro HTTP server bez frameworku?', 'github.com/gin-gonic/gin', 'net/http', 'net/tcp', 'http/server', 'b', 'Balíček net/http je vestavěný a poskytuje plnohodnotný HTTP server.', 7),
(@qfin, 'Co dělá c.Next() v Gin middleware?', 'Ukončí požadavek', 'Předá řízení dalšímu middleware/handleru', 'Vrátí JSON', 'Zaloguje požadavek', 'b', 'c.Next() předá řízení dalšímu handleru v řetězci middleware.', 8),
(@qfin, 'Jak provedeš transakci s database/sql?', 'db.Transaction()', 'tx, _ := db.Begin() + tx.Commit()/tx.Rollback()', 'db.BeginTx()', 'db.Exec("BEGIN")', 'b', 'Transakce se zahájí db.Begin(), potvrdí tx.Commit() nebo zruší tx.Rollback().', 9),
(@qfin, 'Co je table-driven test v Go?', 'Test s databázovou tabulkou', 'Test s daty ve slice struct a iterací přes případy', 'Test běžící v goroutine', 'Test měřící výkon', 'b', 'Table-driven test ukládá testovací případy do slice struktur a iteruje přes ně.', 10);


-- ============================================================
-- Aktualizace počtu lekcí
-- ============================================================

UPDATE courses SET lesson_count = (SELECT COUNT(*) FROM lessons WHERE course_id = @kurs_id) WHERE id = @kurs_id;