-- Swift kurz — Kompletní kurz (20 lekcí + závěrečný kvíz)
-- MariaDB 10.4, phpMyAdmin style, no DELIMITER
-- Apostrofy escapovány jako ''

SET @kurs_id = (SELECT id FROM courses WHERE slug = 'swift');

-- ============================================================
-- LEKCE 1–20 + ZÁVĚREČNÝ KVÍZ
-- ============================================================

INSERT INTO lessons (course_id, title, content, lesson_type, sort_order, xp_reward, duration_minutes) VALUES
(@kurs_id, 'Úvod do Swiftu', '<h2>Co je Swift?</h2><p>Swift je moderní programovací jazyk od Apple, navržený pro bezpečnost, výkon a čitelnost. Vytvoříš v něm aplikace pro iOS, macOS, watchOS a tvOS. Instaluj <strong>Xcode</strong> z Mac App Store — obsahuje kompilátor, debugger i <strong>Playground</strong> pro okamžité testování kódu.</p><h2>Playground</h2><p>Otevři Xcode → File → New → Playground → Blank. Playground zobrazuje výsledky každého řádku v reálném čase.</p><h2>Základní typy</h2><p>Swift je staticky typovaný jazyk s typovou inferencí. Nemusíš typ psát, pokud ho překladač dokáže odvodit.</p><pre><code>// Základní typy\nlet jmeno: String = "Karel"\nvar vek: Int = 25\nlet prumer: Double = 4.8\nlet aktivni: Bool = true\n\n// Typová inference — typ není nutné psát\nlet mesto = "Praha"    // String\nvar pocet = 42         // Int\nlet pi = 3.14159      // Double\n\n// let vs var\nlet konstanta = 10     // nelze změnit\nvar promenna = 20      // lze změnit\npromenna = 30</code></pre>', 'lesson', 1, 15, 12),

(@kurs_id, 'Structs vs Classes', '<h2>Struct — hodnotový typ</h2><p><code>struct</code> je hodnotový typ (value type) — při přiřazení se vytvoří kopie. Většina typů ve Swiftu jsou structy: <code>Int</code>, <code>String</code>, <code>Array</code>, <code>Dict</code>.</p><h2>Class — referenční typ</h2><p><code>class</code> je referenční typ (reference type) — při přiřazení se předává reference na stejnou instanci. Podporuje dědičnost a deinitializér.</p><pre><code>// Struct — value type\nstruct Bod {\n    var x: Double\n    var y: Double\n}\nvar a = Bod(x: 1, y: 2)\nvar b = a      // kopie!\nb.x = 99\nprint(a.x)    // 1 — původní se nezměnil\n\n// Class — reference type\nclass Osoba {\n    var jmeno: String\n    init(jmeno: String) {\n        self.jmeno = jmeno\n    }\n}\nlet p1 = Osoba(jmeno: "Karel")\nlet p2 = p1        // reference!\np2.jmeno = "Eva"\nprint(p1.jmeno)    // "Eva" — stejná instance</code></pre><h2>Kdy použít co?</h2><p>Preferuj <code>struct</code>. Použij <code>class</code>, pokud potřebuješ dědičnost, identity (===) nebo lifecycle management (deinit).</p>', 'lesson', 2, 15, 14),

(@kurs_id, 'Enums a pattern matching', '<h2>Enum v Swiftu</h2><p>Enum je mocný typ, který může obsahovat <strong>associated values</strong> — každou variantu můžeš vybavit daty. Kombinace s <code>switch</code> umožňuje pattern matching.</p><pre><code>// Jednoduchý enum\nenum Směr {\n    case sever, jih, východ, západ\n}\nlet s = Směr.sever\n\n// Enum s associated values\nenum Výsledek {\n    case úspěch(data: String)\n    case chyba(zpráva: String, kód: Int)\n}\n\nlet r = Výsledek.chyba(zpráva: "Nenalezeno", kód: 404)\n\n// Pattern matching\nswitch r {\ncase .úspěch(let data):\n    print("OK: \\(data)")\ncase .chyba(let zpráva, let kód):\n    print("Chyba \\(kód): \\(zpráva)")\n}\n\n// Raw values\nenum Planet: Int {\n    case merkur = 1, venuse, zeme\n}\nprint(Planet.zeme.rawValue)  // 3</code></pre><h2>Enum metody</h2><p>Enum může mít metody i computed properties, podobně jako struct.</p><pre><code>enum Barva {\n    case červená, zelená, modrá\n    var hex: String {\n        switch self {\n        case .červená: return "#FF0000"\n        case .zelená: return "#00FF00"\n        case .modrá: return "#0000FF"\n        }\n    }\n}\nprint(Barva.zelená.hex)  // "#00FF00"</code></pre>', 'lesson', 3, 15, 14),

(@kurs_id, 'Optionals', '<h2>Co je Optional?</h2><p><code>Optional</code> znamená, že proměnná může obsahovat hodnotu <strong>nebo</strong> <code>nil</code>. Zapisuje se jako <code>Type?</code>, což je zkratka za <code>Optional&lt;Type&gt;</code>. Swift tě nutí explicitně řešit absenci hodnoty — to odstraňuje celou třídu chyb.</p><pre><code>// Deklarace optionals\nvar jméno: String? = "Karel"\nvar vek: Int? = nil\n\n// Forced unwrapping — NEBEZPEČNÉ, crash pokud nil\nprint(jméno!)  // "Karel"\n\n// if let — bezpečné rozbalení\nif let j = jméno {\n    print("Ahoj, \\(j)")\n}\n\n// guard let — včasný návrat\nfunc pozdrav(jméno: String?) {\n    guard let j = jméno else {\n        print("Neznámé jméno")\n        return\n    }\n    print("Ahoj, \\(j)")\n}\n\n// Optional chaining\nstruct Adresa { var město: String }\nstruct Osoba { var adresa: Adresa? }\nlet o = Osoba(adresa: Adresa(město: "Praha"))\nprint(o.adresa?.město ?? "Neznámé")  // "Praha"\n\n// Nil coalescing — výchozí hodnota\nlet x: Int? = nil\nlet y = x ?? 0  // 0</code></pre>', 'lesson', 4, 15, 14),

(@kurs_id, 'Protokoly a Protocol-Oriented Programming', '<h2>Protokoly</h2><p>Protokol definuje smlouvu — seznam metod a vlastností, které typ musí implementovat. Swift podporuje <strong>Protocol-Oriented Programming</strong> (POP): preferuj protokoly před dědičností tříd.</p><pre><code>protocol Popisovatelný {\n    var popis: String { get }\n    func pozdrav()\n}\n\nstruct Uživatel: Popisovatelný {\n    var jméno: String\n    var popis: String { "Uživatel \\(jméno)" }\n    func pozdrav() {\n        print("Ahoj, jsem \\(jméno)")\n    }\n}\n\n// Protocol extension — výchozí implementace\nextension Popisovatelný {\n    func pozdrav() {\n        print(popis)\n    }\n}\n\n// Protokol jako typ\nfunc vypiš(_ p: Popisovatelný) {\n    print(p.popis)\n}</code></pre><h2>POP vs OOP</h2><p>Swift doporučuje skládat chování z protokolů a extenzí místo hluboké hierarchie tříd. Výhody: value types, více konformit, testovatelnost.</p>', 'lesson', 5, 15, 15),

(@kurs_id, 'Generika a associated types', '<h2>Generika</h2><p>Generika umožňují psát kód, který pracuje s libovolným typem. Funkce, typy i protokoly mohou být generické.</p><pre><code>// Generická funkce\nfunc swap<T>(_ a: inout T, _ b: inout T) {\n    let tmp = a\n    a = b\n    b = tmp\n}\n\nvar x = 1, y = 2\nswap(&x, &y)  // x=2, y=1\n\n// Generický typ\nstruct Zásobník<Element> {\n    private var položky: [Element] = []\n    mutating func push(_ item: Element) {\n        položky.append(item)\n    }\n    mutating func pop() -> Element? {\n        položky.popLast()\n    }\n}\n\nvar ints = Zásobník<Int>()\nints.push(42)\nprint(ints.pop()!)  // 42\n\n// Type constraints\nfunc najdi<T: Equatable>(value: T, in pole: [T]) -> Int? {\n    return pole.firstIndex(of: value)\n}</code></pre><h2>Associated types</h2><p>Protokoly používají <code>associatedtype</code> místo generických parametrů.</p><pre><code>protocol Kontejner {\n    associatedtype Položka\n    var počet: Int { get }\n    mutating func přidej(_ item: Položka)\n}\n\nstruct SeznamKontejner<T>: Kontejner {\n    typealias Položka = T\n    private var data: [T] = []\n    var počet: Int { data.count }\n    mutating func přidej(_ item: T) {\n        data.append(item)\n    }\n}</code></pre>', 'lesson', 6, 15, 16),

(@kurs_id, 'async/await a Swift Concurrency', '<h2>Swift Concurrency</h2><p>Od Swift 5.5 má jazyk nativní podporu pro asynchronní kód pomocí <code>async/await</code>. Kód vypadá sekvenčně, ale běží konkurenčně. <code>Task</code> vytvoří asynchronní kontext, <code>actor</code> chrání sdílený stav.</p><pre><code>// Async funkce\nfunc fetchData(url: String) async throws -> String {\n    let (data, _) = try await URLSession.shared.data(from: URL(string: url)!)\n    return String(data: data, encoding: .utf8) ?? ""\n}\n\n// Volání z async kontextu\nTask {\n    do {\n        let result = try await fetchData(url: "https://api.example.com")\n        print(result)\n    } catch {\n        print("Chyba: \\(error)")\n    }\n}\n\n// Task skupiny\nfunc fetchAll() async throws -> [String] {\n    try await withThrowingTaskGroup(of: String.self) { group in\n        for url in urls {\n            group.addTask { try await fetchData(url: url) }\n        }\n        var results: [String] = []\n        for try await result in group {\n            results.append(result)\n        }\n        return results\n    }\n}\n\n// Actor — bezpečný sdílený stav\nactor Čítač {\n    private var hodnota = 0\n    func inkrement() -> Int {\n        hodnota += 1\n        return hodnota\n    }\n    func čti() -> Int { hodnota }\n}</code></pre>', 'lesson', 7, 15, 16),

(@kurs_id, 'Combine framework', '<h2>Combine — reaktivní programování</h2><p>Combine je framework pro reaktivní zpracování událostí. Základní triáda: <strong>Publisher</strong> (produkuje hodnoty), <strong>Subscriber</strong> (přijímá hodnoty), <strong>operátory</strong> (transformují proud).</p><pre><code>import Combine\n\n// Publisher\nlet publisher = [1, 2, 3, 4, 5].publisher\n\n// Operátory\nlet subskripce = publisher\n    .filter { $0 % 2 == 0 }\n    .map { $0 * 10 }\n    .sink { value in\n        print(value)  // 20, 40\n    }\n\n// PassthroughSubject — ruční odesílání\nlet subject = PassthroughSubject<String, Never>()\n\nsubject.sink(\n    receiveCompletion: { completion in\n        print("Hotovo: \\(completion)")\n    },\n    receiveValue: { value in\n        print("Přijato: \\(value)")\n    }\n)\n\nsubject.send("Ahoj")\nsubject.send("Světe")\nsubject.send(completion: .finished)\n\n// @Published — automatický publisher\nclass Model: ObservableObject {\n    @Published var skóre: Int = 0\n}</code></pre><h2>Hlavní operátory</h2><p><code>map</code>, <code>filter</code>, <code>compactMap</code>, <code>flatMap</code>, <code>debounce</code>, <code>throttle</code>, <code>combineLatest</code>, <code>zip</code>, <code>retry</code>, <code>catch</code>.</p>', 'lesson', 8, 15, 15),

(@kurs_id, 'SwiftUI — View a základní komponenty', '<h2>SwiftUI</h2><p>SwiftUI je deklarativní UI framework od Apple. Místo imperativního řízení stavu popíšeš, jak má vzhled vypadat pro daný stav, a SwiftUI se postará o aktualizace.</p><pre><code>import SwiftUI\n\nstruct ContentView: View {\n    var body: some View {\n        VStack(spacing: 16) {\n            Text("Ahoj, VeVit!")\n                .font(.title)\n                .foregroundColor(.blue)\n            \n            Image(systemName: "swift")\n                .font(.system(size: 60))\n                .foregroundColor(.orange)\n            \n            Button("Klikni mě") {\n                print("Tlačítko stisknuto")\n            }\n            .buttonStyle(.borderedProminent)\n            \n            HStack {\n                Text("Vlevo")\n                Spacer()\n                Text("Vpravo")\n            }\n            .padding()\n        }\n        .padding()\n    }\n}</code></pre><h2>Klíčové komponenty</h2><p><code>VStack</code> — vertikální rozložení, <code>HStack</code> — horizontální, <code>ZStack</code> — překrývání. <code>List</code> pro tabulky, <code>NavigationStack</code> pro navigaci, <code>ScrollView</code> pro rolování. Modifikátory řetězíš za view: <code>.padding()</code>, <code>.background()</code>, <code>.cornerRadius()</code>.</p>', 'lesson', 9, 15, 15),

(@kurs_id, 'SwiftUI — State management', '<h2>@State</h2><p><code>@State</code> je lokální stav view. Když se změní, SwiftUI automaticky překreslí dotčené view.</p><pre><code>struct CounterView: View {\n    @State private var count = 0\n    \n    var body: some View {\n        VStack {\n            Text("Počet: \\(count)")\n            Button("+1") { count += 1 }\n        }\n    }\n}</code></pre><h2>@Binding</h2><p><code>@Binding</code> předává state do child view jako obousměrnou vazbu. Child může číst i měnit hodnotu.</p><pre><code>struct ChildView: View {\n    @Binding var count: Int\n    var body: some View {\n        Button("Child +1") { count += 1 }\n    }\n}</code></pre><h2>@ObservedObject a @EnvironmentObject</h2><p><code>@ObservedObject</code> sleduje externí objekt conforming to <code>ObservableObject</code>. <code>@EnvironmentObject</code> vkládá objekt do view hierarchie bez explicitního předávání.</p><pre><code>class AppModel: ObservableObject {\n    @Published var jméno = "Karel"\n}\n\nstruct ParentView: View {\n    @StateObject var model = AppModel()\n    var body: some View {\n        ChildView(model: model)\n            .environmentObject(model)\n    }\n}\n\nstruct ChildView: View {\n    @ObservedObject var model: AppModel\n    @EnvironmentObject var envModel: AppModel\n    var body: some View {\n        Text(model.jméno)\n    }\n}</code></pre>', 'lesson', 10, 15, 16),

(@kurs_id, 'URLSession a Codable', '<h2>URLSession</h2><p>URLSession je nativní API pro HTTP požadavky. V kombinaci s <code>async/await</code> je networking čistý a čitelný.</p><pre><code>// GET požadavek s async/await\nfunc fetchUsers() async throws -> [User] {\n    let url = URL(string: "https://jsonplaceholder.typicode.com/users")!\n    let (data, _) = try await URLSession.shared.data(from: url)\n    return try JSONDecoder().decode([User].self, from: data)\n}</code></pre><h2>Codable</h2><p><code>Codable</code> sjednocuje <code>Encodable</code> a <code>Decodable</code>. Automaticky mapuje JSON na Swift typy. Klíče lze přemapovat pomocí <code>CodingKeys</code>.</p><pre><code>// Model s Codable\nstruct User: Codable, Identifiable {\n    let id: Int\n    let name: String\n    let email: String\n    let company: Company\n    \n    struct Company: Codable {\n        let name: String\n    }\n    \n    // Přemapování JSON klíčů\n    enum CodingKeys: String, CodingKey {\n        case id, name, email\n        case company = "company"\n    }\n}\n\n// Dekódování\nlet decoder = JSONDecoder()\nlet users = try decoder.decode([User].self, from: jsonData)\n\n// Enkódování\nlet encoder = JSONEncoder()\nencoder.outputFormatting = .prettyPrinted\nlet data = try encoder.encode(users)</code></pre>', 'lesson', 11, 15, 15),

(@kurs_id, 'Core Data', '<h2>Co je Core Data?</h2><p>Core Data je framework od Apple pro perzistenci objektů. Používá <code>NSManagedObject</code>, <code>NSFetchRequest</code> a <code>NSPersistentContainer</code>. Od iOS 15 je k dispozici moderní API.</p><pre><code>// Nastavení persistence controller\nimport CoreData\n\nclass PersistenceController {\n    static let shared = PersistenceController()\n    let container: NSPersistentContainer\n    \n    init() {\n        container = NSPersistentContainer(name: "Model")\n        container.loadPersistentStores { _, error in\n            if let error = error {\n                fatalError("Core Data error: \\(error)")\n            }\n        }\n    }\n}\n\n// Vytvoření záznamu\nfunc vytvořUživatele(context: NSManagedObjectContext) {\n    let user = User(context: context)\n    user.jméno = "Karel"\n    user.věk = 25\n    try? context.save()\n}\n\n// Fetch request\nfunc načtiUživatele(context: NSManagedObjectContext) -> [User] {\n    let request: NSFetchRequest<User> = User.fetchRequest()\n    request.sortDescriptors = [NSSortDescriptor(key: "jméno", ascending: true)]\n    request.predicate = NSPredicate(format: "věk > %d", 18)\n    return (try? context.fetch(request)) ?? []\n}\n\n// Smazání\nfunc smaž(_ user: User, context: NSManagedObjectContext) {\n    context.delete(user)\n    try? context.save()\n}</code></pre>', 'lesson', 12, 15, 16),

(@kurs_id, 'Testování v Swiftu', '<h2>XCTest</h2><p>Standardní testovací framework. Třídy dědí od <code>XCTestCase</code>, testovací metody začínají prefixem <code>test</code>.</p><pre><code>import XCTest\n@testable import MyApp\n\nclass UserTests: XCTestCase {\n    var user: User!\n    \n    override func setUp() {\n        super.setUp()\n        user = User(jméno: "Karel", věk: 25)\n    }\n    \n    func testJméno() {\n        XCTAssertEqual(user.jméno, "Karel")\n    }\n    \n    func testDospělý() {\n        XCTAssertTrue(user.jeDospělý)\n    }\n    \n    func testChyba() {\n        XCTAssertThrowsError(try User(jméno: "", věk: -1))\n    }\n}</code></pre><h2>Async testy</h2><p>Od Xcode 13 lze testovat async kód přímo.</p><pre><code>func testAsyncFetch() async throws {\n    let users = try await fetchUsers()\n    XCTAssertEqual(users.count, 10)\n}</code></pre><h2>Swift Testing (Swift 5.9)</h2><p>Nový framework s makry <code>@Test</code> a <code>#expect</code>.</p><pre><code>import Testing\n\n@Test func testSčítání() {\n    #expect(2 + 3 == 5)\n}\n\n@Test func testOptionál() {\n    let x: Int? = 42\n    #expect(x != nil)\n}</code></pre>', 'lesson', 13, 15, 15),

(@kurs_id, 'Swift Package Manager', '<h2>Swift Package Manager (SPM)</h2><p>SPM je nativní systém pro správu závislostí a modulů. Definuješ ho v <code>Package.swift</code>. Xcode integruje SPM přímo — přidáš závislost přes File → Add Package Dependencies.</p><pre><code>// Package.swift\n// swift-tools-version: 5.9\nimport PackageDescription\n\nlet package = Package(\n    name: "MujProjekt",\n    platforms: [.iOS(.v17), .macOS(.v14)],\n    products: [\n        .library(name: "MujProjekt", targets: ["MujProjekt"]),\n    ],\n    dependencies: [\n        .package(url: "https://github.com/Alamofire/Alamofire.git", from: "5.8.0"),\n        .package(url: "https://github.com/apple/swift-nio.git", from: "2.60.0"),\n    ],\n    targets: [\n        .target(\n            name: "MujProjekt",\n            dependencies: ["Alamofire"]\n        ),\n        .testTarget(\n            name: "MujProjektTests",\n            dependencies: ["MujProjekt"]\n        ),\n    ]\n)</code></pre><h2>Příkazy CLI</h2><p><code>swift build</code> — sestavení, <code>swift test</code> — testy, <code>swift run</code> — spuštění, <code>swift package resolve</code> — stažení závislostí.</p>', 'lesson', 14, 15, 14),

(@kurs_id, 'Makra (Swift 5.9)', '<h2>Makra v Swiftu</h2><p>Od Swift 5.9 podporuje jazyk makra — kód, který generuje jiný kód během kompilace. Rozlišujeme <strong>freestanding</strong> (volně stojící, např. <code>#macro</code>) a <strong>attached</strong> (připojené k deklaraci, např. <code>@macro</code>).</p><pre><code>// Freestanding macro — generuje kód na místě\n// #expect v Swift Testing je freestanding macro\n@Test func testPříklad() {\n    #expect(2 + 2 == 4)\n}\n\n// Attached macros — transformují deklaraci\n@Observable  // generuje observation kód\nclass Model {\n    var skóre = 0\n    var jméno = ""\n}\n\n// Další systemémá makra\nstruct User {\n    @Dependency var api: APIClient  // dependency injection\n}\n\nenum ApiError {\n    @CaseName("notFound") case nf(Int)\n}\n\n// Vytvoření vlastního makra\n// 1. Definice v macro targetu\n@freestanding(expression)\npublic macro document(_ text: String) = #externalMacro(\n    module: "MyMacros",\n    type: "DocumentMacro"\n)</code></pre><h2>Kdy použít makra?</h2><p>Makra nahrazují boilerplate kód. Příklady: <code>@Observable</code>, <code>@Model</code> (SwiftData), <code>#Preview</code>. Vytvářej vlastní makra opatrně — zvýší složitost buildu.</p>', 'lesson', 15, 15, 16),

(@kurs_id, '@Observable (Swift 5.9)', '<h2>Nový observation framework</h2><p>Od Swift 5.9 je k dispozici <code>@Observable</code> makro z modulu <code>Observation</code>. Nahrazuje <code>ObservableObject</code> — nepotřebuješ <code>@Published</code>, sledují se automaticky všechny uložené vlastnosti.</p><pre><code>import Observation\n\n@Observable\nclass ViewModel {\n    var jméno = "Karel"\n    var skóre = 0\n    var jeAktivní = true\n    \n    // Computed property se automaticky sleduje\n    var popis: String {\n        "\\(jméno): \\(skóre) bodů"\n    }\n}\n\n// Použití ve SwiftUI\nstruct ContentView: View {\n    @State var model = ViewModel()\n    \n    var body: some View {\n        VStack {\n            Text(model.popis)\n                .font(.title)\n            Button("+10 bodů") {\n                model.skóre += 10\n            }\n            TextField("Jméno", text: $model.jméno)\n                .textFieldStyle(.roundedBorder)\n        }\n        .padding()\n    }\n}</code></pre><h2>@Observable vs ObservableObject</h2><p><code>@Observable</code> je doporučený přístup pro nové projekty. Výhody: žádné <code>@Published</code>, sledování na úrovni jednotlivých vlastností, čistší syntaxe, lepší výkon. <code>@State</code> automaticky sleduje přístupy k vlastnostem v <code>body</code>.</p>', 'lesson', 16, 15, 15),

(@kurs_id, 'Vapor — Swift na serveru', '<h2>Vapor</h2><p>Vapor je nejpopulárnější server-side framework pro Swift. Postavený na SwiftNIO pro asynchronní I/O. Obsahuje routing, middleware, Fluent ORM a další.</p><pre><code>// Package.swift — přidání Vaporu\n// .package(url: "https://github.com/vapor/vapor.git", from: "4.89.0")\n\n// routes.swift\nimport Vapor\n\nfunc routes(_ app: Application) throws {\n    // GET\n    app.get("hello") { req async -> String in\n        return "Ahoj, Vapor!"\n    }\n    \n    // POST s JSON\n    app.post("users") { req async throws -> User in\n        let user = try req.content.decode(User.self)\n        return user\n    }\n    \n    // Parametry\n    app.get("users", ":id") { req async -> String in\n        guard let id = req.parameters.get("id") else {\n            throw Abort(.badRequest)\n        }\n        return "User \\(id)"\n    }\n}\n\n// Model s Fluent ORM\nimport Fluent\n\nfinal class User: Model, Content {\n    static let schema = "users"\n    \n    @ID(key: .id)\n    var id: UUID?\n    \n    @Field(key: "name")\n    var name: String\n    \n    init() {}\n    init(id: UUID? = nil, name: String) {\n        self.id = id\n        self.name = name\n    }\n}</code></pre><h2>Spuštění</h2><p><code>vapor run serve</code> spustí server na portu 8080. Použij <code>vapor xcode</code> pro generování Xcode projektu.</p>', 'lesson', 17, 15, 16),

(@kurs_id, 'Cross-platform vývoj', '<h2>iOS vs macOS</h2><p>SwiftUI umožňuje sdílet kód napříč platformami. Přesto existují rozdíly — např. NavigationView na macOS, navigation bar items na iOS. Řešením je podmíněná kompilace a platform-specific extenze.</p><pre><code>// Podmíněná kompilace\n#if os(iOS)\nimport UIKit\n#elseif os(macOS)\nimport AppKit\n#endif\n\n// Platform-specific typ\n#if os(iOS)\ntypalias Barva = UIColor\n#elseif os(macOS)\ntypalias Barva = NSColor\n#endif\n\n// Platform-specific view\nstruct AdaptivníView: View {\n    var body: some View {\n        #if os(iOS)\n        iOSView()\n        #elseif os(macOS)\n        macOSView()\n        #endif\n    }\n}\n\n// Podmíněný modifikátor\nextension View {\n    @ViewBuilder\n    func adaptivníPadding() -> some View {\n        #if os(iOS)\n        self.padding(.horizontal, 16)\n        #elseif os(macOS)\n        self.padding(.horizontal, 24)\n        #endif\n    }\n}</code></pre><h2>Universální aplikace</h2><p>V Xcode nastav project target na iOS + macOS. Sdílej modely, viewmodely a společné view komponenty. Odděluj jen platform-specific části pomocí <code>#if os()</code> a <code>@ViewBuilder</code>.</p>', 'lesson', 18, 15, 14),

(@kurs_id, 'CI/CD pro iOS', '<h2>GitHub Actions</h2><p>Automatizuj build, testy a deploy pomocí GitHub Actions. Pro iOS potřebuješ macOS runner s nainstalovaným Xcode.</p><pre><code># .github/workflows/ios.yml\nname: iOS CI\non:\n  push:\n    branches: [main]\npull_request:\n    branches: [main]\n\njobs:\n  build:\n    runs-on: macos-14\n    steps:\n      - uses: actions/checkout@v4\n      - name: Vyber Xcode\n        run: sudo xcode-select -s /Applications/Xcode_15.app\n      - name: Build\n        run: |\n          xcodebuild build \\\n            -project MyApp.xcodeproj \\\n            -scheme MyApp \\\n            -destination ''platform=iOS Simulator,name=iPhone 15'' \\\n            -configuration Debug\n      - name: Testy\n        run: |\n          xcodebuild test \\\n            -project MyApp.xcodeproj \\\n            -scheme MyApp \\\n            -destination ''platform=iOS Simulator,name=iPhone 15''</code></pre><h2>Xcode Cloud</h2><p>Apple nabízí <strong>Xcode Cloud</strong> — integrované CI/CD v Xcode. Nastavíš přímo v Xcode: Product → Xcode Cloud → Create Workflow. Výhoda: nativní podpora pro testování na reálných zařízeních, automatický archiv a distribuce TestFlight.</p>', 'lesson', 19, 15, 15),

(@kurs_id, 'Shrnutí a portfolio projekt', '<h2>Co ses naučil</h2><p>Prošel jsi základy Swiftu, typovým systémem, optionals, protokoly, generiky, concurrency, SwiftUI, networkingem, perzistencí, testováním, SPM, makry, server-side Swiftem i CI/CD. Nyní je čas to spojit do jednoho projektu.</p><h2>Portfolio projekt — iOS aplikace</h2><p>Vytvoř kompletní aplikaci, která ukáže všechny dovednosti. Návrh:</p><pre><code>// 1. Model s @Observable\nimport Observation\n\n@Observable\nclass TaskStore {\n    var tasks: [Task] = []\n    \n    func add(_ title: String) {\n        tasks.append(Task(title: title))\n    }\n    \n    func toggle(_ task: Task) {\n        task.completed.toggle()\n    }\n}\n\nstruct Task: Identifiable, Codable {\n    let id = UUID()\n    var title: String\n    var completed = false\n}\n\n// 2. SwiftUI View\nstruct TaskListView: View {\n    @State var store = TaskStore()\n    @State var newTitle = ""\n    \n    var body: some View {\n        NavigationStack {\n            List(store.tasks) { task in\n                HStack {\n                    Image(systemName: task.completed ? "checkmark.circle" : "circle")\n                    Text(task.title)\n                        .strikethrough(task.completed)\n                }\n                .onTapGesture { store.toggle(task) }\n            }\n            .navigationTitle("Úkoly")\n        }\n    }\n}</code></pre><h2>Checklist projektu</h2><p>1. Modely s <code>@Observable</code> a <code>Codable</code>. 2. SwiftUI view hierarchie s <code>@State</code>/<code>@Binding</code>. 3. Networking s <code>URLSession</code> + <code>async/await</code>. 4. Core Data pro lokální perzistenci. 5. Testy v XCTest. 6. CI/CD na GitHub Actions. 7. SPM závislosti. 8. Podpora iOS + macOS.</p>', 'lesson', 20, 15, 20),

(@kurs_id, 'Závěrečný kvíz — Celý Swift kurz', '<p>Závěrečný test pokrývající všechny lekce kurzu Swift.</p>', 'final_quiz', 21, 200, 30);

SET @qfin = LAST_INSERT_ID();

INSERT INTO quizzes (lesson_id, question, option_a, option_b, option_c, option_d, correct_answer, explanation, sort_order) VALUES
(@qfin, 'Jaký je rozdíl mezi let a var ve Swiftu?', 'let je pro čísla, var pro řetězce', 'let je konstanta, var je proměnná', 'let je globální, var lokální', 'Žádný rozdíl', 'b', 'let deklaruje konstantu (nelze změnit), var proměnnou (lze změnit).', 1),
(@qfin, 'Co je struct vs class?', 'Struct je reference type, class value type', 'Struct je value type, class je reference type', 'Oba jsou value types', 'Oba jsou reference types', 'b', 'Struct kopíruje hodnotu při přiřazení, class předává referenci na stejnou instanci.', 2),
(@qfin, 'Co dělá guard let?', 'Vytvoří novou konstantu', 'Bezpečně rozbalí optional nebo včasně ukončí funkci', 'Vyhodí výjimku', 'Je ekvivalentem if let', 'b', 'guard let rozbalí optional — pokud je nil, provede else větev s return/throw.', 3),
(@qfin, 'Co je Protocol-Oriented Programming?', 'Programování s třídami a dědičností', 'Skládání chování pomocí protokolů a extenzí místo hluboké hierarchie tříd', 'Programování s generiky', 'Paradigma pro databáze', 'b', 'POP preferuje protokoly a extenze místo dědičnosti tříd — lépe se testuje a skládá.', 4),
(@qfin, 'K čemu slouží async/await ve Swiftu?', 'K paralelnímu běhu vláken', 'K zápisu asynchronního kódu, který vypadá sekvenčně', 'K optimalizaci paměti', 'K deklaraci typů', 'b', 'async/await umožňuje psát asynchronní kód, který vypadá jako běžný sekvenční kód.', 5),
(@qfin, 'Co je @State ve SwiftUI?', 'Globální stav aplikace', 'Lokální stav view — při změně se view překreslí', 'Databázový atribut', 'Stav pro Core Data', 'b', '@State je lokální stav view. SwiftUI automaticky překreslí view, když se @State změní.', 6),
(@qfin, 'Co dělá Codable?', 'Šifruje data', 'Automaticky mapuje JSON na Swift typy a zpět', 'Komprimuje soubory', 'Definuje protokol', 'b', 'Codable sjednocuje Encodable a Decodable — automaticky serializuje/deserializuje JSON.', 7),
(@qfin, 'K čemu slouží actor ve Swiftu?', 'K vytvoření UI komponenty', 'K bezpečnému sdílení mutable stavu v konkurenčním prostředí', 'K definici protokolu', 'K logování', 'b', 'Actor zaručuje, že k jeho mutable stavu přistupuje vždy jen jeden task najednou.', 8),
(@qfin, 'Co je Swift Package Manager?', 'Aplikace pro správu souborů', 'Nativní systém pro správu závislostí a modulů definovaný v Package.swift', 'Plugin pro Xcode', 'Typ databáze', 'b', 'SPM spravuje závislosti a moduly pomocí Package.swift — integrován v Xcode.', 9),
(@qfin, 'Co dělá @Observable (Swift 5.9)?', 'Přidává logování', 'Automaticky sleduje změny vlastností — nahrazuje ObservableObject a @Published', 'Vytvoří UI komponentu', 'Sleduje síťový provoz', 'b', '@Observable makro automaticky sleduje změny vlastností — nepotřebuješ @Published.', 10);


-- ============================================================
-- Aktualizace počtu lekcí
-- ============================================================

UPDATE courses SET lesson_count = (SELECT COUNT(*) FROM lessons WHERE course_id = @kurs_id) WHERE id = @kurs_id;