<?php
declare(strict_types=1);
require_once __DIR__ . '/lib/auth-helpers.php';
require_once __DIR__ . '/lib/totp-endpoint.php';
header('Cache-Control: no-store, private, max-age=0');
$challenge=strtolower(trim((string)($_GET['challenge']??'')));
$valid=false;
if(totpChallengeId($challenge)!==null){$cfg=auth_load_config();$valid=loadTotpChallenge($cfg,$challenge,'login_totp')!==null;}
?>
<!doctype html><html lang="cs"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="color-scheme" content="dark"><title>Dvoufázové ověření · VEVIT</title><link rel="icon" href="/VeVit-account/images/icon.ico" type="image/x-icon">
<style>:root{--bg:#070908;--card:#101311;--line:#273029;--text:#f4f7f4;--muted:#a2aba4;--green:#39e079;--red:#ff6b6b}*{box-sizing:border-box}body{margin:0;min-height:100vh;background:var(--bg);color:var(--text);font-family:Inter,system-ui,sans-serif;display:grid;place-items:center;padding:24px}.card{width:min(100%,440px);padding:32px;border:1px solid var(--line);border-radius:20px;background:var(--card)}h1{margin:0 0 10px}p{color:var(--muted)}label{display:block;margin:22px 0 8px}input{width:100%;height:52px;border:1px solid var(--line);border-radius:12px;background:#080b09;color:var(--text);padding:0 14px;font-size:20px;letter-spacing:.2em;text-align:center}.btn{width:100%;height:48px;border-radius:12px;margin-top:14px;font-weight:700;cursor:pointer}.primary{border:0;background:var(--green);color:#041108}.ghost{border:1px solid var(--line);background:transparent;color:var(--text)}.status{min-height:22px;color:var(--red)}a{display:block;text-align:center;color:var(--muted);margin-top:18px}</style></head><body><main class="card">
<?php if(!$valid):?><h1>Ověření vypršelo</h1><p>Vraťte se na přihlášení a zkuste to znovu.</p><a href="/account/login">Zpět na přihlášení</a>
<?php else:?><h1>Dvoufázové ověření</h1><p id="description">Zadejte šestimístný kód z ověřovací aplikace.</p><form id="form"><label for="code">Ověřovací kód</label><input id="code" inputmode="numeric" autocomplete="one-time-code" maxlength="14" required><button class="btn primary" id="submit" type="submit">Ověřit a přihlásit</button></form><button class="btn ghost" id="switch" type="button">Použít obnovovací kód</button><p class="status" id="status" role="alert" aria-live="polite"></p><a href="/account/login">Zpět na přihlášení</a>
<script>(function(){'use strict';var recovery=false,form=document.getElementById('form'),code=document.getElementById('code'),button=document.getElementById('submit'),status=document.getElementById('status'),toggle=document.getElementById('switch'),description=document.getElementById('description');toggle.onclick=function(){recovery=!recovery;code.value='';code.maxLength=recovery?14:6;code.autocomplete=recovery?'off':'one-time-code';description.textContent=recovery?'Zadejte jeden nepoužitý obnovovací kód.':'Zadejte šestimístný kód z ověřovací aplikace.';toggle.textContent=recovery?'Použít kód z aplikace':'Použít obnovovací kód';code.focus()};code.oninput=function(){code.value=recovery?code.value.toUpperCase().replace(/[^A-Z0-9-]/g,'').slice(0,14):code.value.replace(/\\D/g,'').slice(0,6)};form.onsubmit=async function(e){e.preventDefault();button.disabled=true;status.textContent='';try{var endpoint=recovery?'recovery-verify.php':'login-verify.php';var r=await fetch('/account/api/2fa/'+endpoint,{method:'POST',credentials:'same-origin',headers:{'Content-Type':'application/json'},body:JSON.stringify({challenge:<?=json_encode($challenge)?>,code:code.value})});var d=await r.json();if(!r.ok)throw new Error(d.error||'Ověření se nepodařilo.');location.replace(d.redirect)}catch(error){status.textContent=error.message;button.disabled=false}};code.focus()}());</script>
<?php endif;?></main></body></html>
