-- SQL & Databáze kurz — Kompletní kurz (Sekce 1-2 + kvízy)
-- MariaDB 10.4, phpMyAdmin style, no DELIMITER
-- Apostrofy escapovány jako ''

SET @kurs_id = (SELECT id FROM courses WHERE slug = 'sql');

-- ============================================================
-- SEKCE 1: Základy (sort_order 1-10)
-- ============================================================

INSERT INTO lessons (course_id, title, content, lesson_type, sort_order, xp_reward, duration_minutes) VALUES
(@kurs_id, 'Co je relační databáze', '<h2>Relační databáze</h2><p>Relační databáze ukládá data do <strong>tabulek</strong> (řádky a sloupce). Tabulky jsou navzájem propojeny relacemi. Systém, který tyto tabulky spravuje, se nazývá <strong>RDBMS</strong> (Relational Database Management System).</p><p>Hlavní vlastnosti relační databáze:</p><ul><li>Data uložena v tabulkách (řádky = záznamy, sloupce = atributy)</li><li>Relace mezi tabulkami přes cizí klíče (FOREIGN KEY)</li><li>Jazyk SQL pro dotazování a manipulaci</li><li>ACID vlastnosti pro spolehlivost</li></ul><pre><code>-- Příklad tabulky v relační databázi (VeVit)\n-- Tabulka users:\n-- | id | jmeno    | email              | xp  |\n-- |----|----------|--------------------|-----|\n-- | 1  | Karel    | karel@vevit.cz     | 150 |\n-- | 2  | Jana     | jana@vevit.cz      | 320 |\n\n-- Tabulka courses:\n-- | id | slug    | title          |\n-- |----|---------|----------------|\n-- | 1  | python  | Python kurz    |\n-- | 2  | sql     | SQL & Databaze |</code></pre><h2>MariaDB vs MySQL</h2><p><strong>MariaDB</strong> je fork MySQL, který vznikl v roce 2009. Je kompatibilní s MySQL, ale přidává nové funkce a má aktivnější komunitu. Na většině hostingů (např. Wedos) dnes najdeš právě MariaDB.</p><p>Kdy použít relační databázi:</p><ul><li>Strukturovaná data s jasným schématem</li><li>Potřebuješ transakce a konzistenci</li><li>Komplexní dotazy přes více tabulek (JOINy)</li></ul><p>Kdy zvážit NoSQL: dokumentová data, obrovské objemy neuspořádaných dat, flexibilní schéma.</p>', 'lesson', 1, 10, 12),

(@kurs_id, 'SELECT + WHERE', '<h2>Základní dotazy SELECT</h2><p>Příkaz <code>SELECT</code> je nejzákladnější SQL příkaz. Vrací data z jedné nebo více tabulek.</p><pre><code>-- Všechny sloupce ze tabulky users\nSELECT * FROM users;\n\n-- Konkrétní sloupce\nSELECT jmeno, email, xp FROM users;\n\n-- S aliasem sloupce\nSELECT jmeno AS uzivatel, xp AS body FROM users;</code></pre><h2>Klauzule WHERE</h2><p><code>WHERE</code> filtruje řádky podle podmínky.</p><pre><code>-- Uživatelé s více než 100 XP\nSELECT jmeno, xp FROM users WHERE xp > 100;\n\n-- Přesná shoda\nSELECT * FROM courses WHERE slug = ''python'';\n\n-- AND / OR / NOT\nSELECT jmeno FROM users\nWHERE xp > 100 AND xp < 500;\n\nSELECT jmeno FROM users\nWHERE xp > 500 OR xp = 0;\n\nSELECT * FROM courses WHERE NOT is_active = 1;</code></pre><h2>LIKE, IN, BETWEEN, IS NULL</h2><pre><code>-- LIKE — hledání vzoru (% = cokoliv, _ = jeden znak)\nSELECT jmeno FROM users WHERE email LIKE ''%vevit.cz'';\nSELECT jmeno FROM users WHERE jmeno LIKE ''K%'';\n\n-- IN — seznam hodnot\nSELECT * FROM courses WHERE difficulty IN (''beginner'', ''intermediate'');\n\n-- BETWEEN — rozsah (včetně hranic)\nSELECT jmeno, xp FROM users WHERE xp BETWEEN 100 AND 500;\n\n-- IS NULL — kontrola NULL\nSELECT * FROM lessons WHERE video_url IS NULL;\nSELECT * FROM lessons WHERE video_url IS NOT NULL;</code></pre>', 'lesson', 2, 10, 15),

(@kurs_id, 'ORDER BY + LIMIT + OFFSET', '<h2>Řazení ORDER BY</h2><p><code>ORDER BY</code> seřadí výsledky podle jednoho nebo více sloupců. Výchozí je <code>ASC</code> (vzestupně), <code>DESC</code> pro sestupně.</p><pre><code>-- Vzestupně podle XP\nSELECT jmeno, xp FROM users ORDER BY xp ASC;\n\n-- Sestupně — nejvíce XP nahoře\nSELECT jmeno, xp FROM users ORDER BY xp DESC;\n\n-- Řazení podle více sloupců\nSELECT * FROM user_progress\nORDER BY course_id ASC, completed_at DESC;</code></pre><h2>LIMIT a OFFSET</h2><p><code>LIMIT</code> omezí počet vrácených řádků. <code>OFFSET</code> přeskočí prvních N řádků — užitečné pro stránkování.</p><pre><code>-- Top 5 uživatelů podle XP\nSELECT jmeno, xp FROM users ORDER BY xp DESC LIMIT 5;\n\n-- Stránkování: 10 záznamů na stránku\n-- Stránka 1 (řádky 1-10)\nSELECT * FROM lessons ORDER BY sort_order LIMIT 10 OFFSET 0;\n\n-- Stránka 2 (řádky 11-20)\nSELECT * FROM lessons ORDER BY sort_order LIMIT 10 OFFSET 10;\n\n-- Stránka 3 (řádky 21-30)\nSELECT * FROM lessons ORDER BY sort_order LIMIT 10 OFFSET 20;</code></pre><p>Alternativní zápis: <code>LIMIT offset, row_count</code> — <code>LIMIT 10, 10</code> znamená přeskoč 10, vrať 10.</p>', 'lesson', 3, 10, 12),

(@kurs_id, 'Agregace + GROUP BY + HAVING', '<h2>Agregační funkce</h2><p>Agregační funkce počítají výsledek přes množinu řádků: <code>COUNT</code>, <code>SUM</code>, <code>AVG</code>, <code>MAX</code>, <code>MIN</code>.</p><pre><code>-- Kolik uživatelů máme?\nSELECT COUNT(*) FROM users;\n\n-- Celkové XP všech uživatelů\nSELECT SUM(xp) FROM users;\n\n-- Průměrné XP\nSELECT AVG(xp) FROM users;\n\n-- Nejvyšší a nejnižší XP\nSELECT MAX(xp), MIN(xp) FROM users;\n\n-- Počet lekcí v kurzu\nSELECT COUNT(*) FROM lessons WHERE course_id = 1;</code></pre><h2>GROUP BY</h2><p><code>GROUP BY</code> seskupí řádky se stejnou hodnotou a aplikuje agregaci na každou skupinu.</p><pre><code>-- XP podle uživatele\nSELECT user_id, SUM(xp_ziskano) AS total_xp\nFROM user_progress\nGROUP BY user_id;\n\n-- Počet dokončených lekcí v každém kurzu\nSELECT course_id, COUNT(*) AS dokonceno\nFROM user_progress\nGROUP BY course_id;\n\n-- Průměrné skóre v kurzech\nSELECT course_id, AVG(skore) AS prumer\nFROM user_progress\nGROUP BY course_id;</code></pre><h2>HAVING vs WHERE</h2><p><code>WHERE</code> filtruje řádky PRED agregací, <code>HAVING</code> filtruje skupiny PO agregaci.</p><pre><code>-- Uživatelé, kteří získali více než 100 XP celkem\nSELECT user_id, SUM(xp_ziskano) AS total_xp\nFROM user_progress\nGROUP BY user_id\nHAVING SUM(xp_ziskano) > 100;\n\n-- Kurzy s průměrným skóre nad 80\nSELECT course_id, AVG(skore) AS prumer\nFROM user_progress\nGROUP BY course_id\nHAVING AVG(skore) > 80;</code></pre><h2>NULL v agregacích</h2><p>Agregační funkce IGNORUJÍ NULL hodnoty (kromě <code>COUNT(*)</code>). <code>COUNT(sloupec)</code> nepočítá NULL, <code>COUNT(*)</code> počítá všechny řádky.</p><pre><code>SELECT COUNT(*) AS vsechny,      -- počítá i NULL\n       COUNT(skore) AS vyplnene  -- ignoruje NULL\nFROM user_progress;</code></pre>', 'lesson', 4, 10, 15),

(@kurs_id, 'JOINy (INNER/LEFT/RIGHT/CROSS/SELF)', '<h2>INNER JOIN</h2><p><code>INNER JOIN</code> vrátí řádky, které mají shodu v OBOU tabulkách. Nejčastější typ JOINu.</p><pre><code>-- Uživatelé a jejich dokončené kurzy\nSELECT u.jmeno, c.title, up.skore\nFROM users u\nINNER JOIN user_progress up ON u.id = up.user_id\nINNER JOIN courses c ON up.course_id = c.id;</code></pre><h2>LEFT JOIN</h2><p><code>LEFT JOIN</code> vrátí VŠECHNY řádky z levé tabulky. Pokud nemají shodu v pravé, doplní NULL.</p><pre><code>-- Všichni uživatelé, i ti bez dokončených lekcí\nSELECT u.jmeno, up.course_id\nFROM users u\nLEFT JOIN user_progress up ON u.id = up.user_id;\n\n-- Jen uživatelé BEZ žádného progressu\nSELECT u.jmeno\nFROM users u\nLEFT JOIN user_progress up ON u.id = up.user_id\nWHERE up.id IS NULL;</code></pre><h2>RIGHT JOIN</h2><p><code>RIGHT JOIN</code> je opak LEFT — vrátí všechny řádky z pravé tabulky. Méně častý, často lze přepsat jako LEFT JOIN prohozením tabulek.</p><pre><code>-- Všechny kurzy, i ty bez progress záznamů\nSELECT c.title, up.user_id\nFROM user_progress up\nRIGHT JOIN courses c ON up.course_id = c.id;</code></pre><h2>CROSS JOIN</h2><p><code>CROSS JOIN</code> vytvoří kartézský součin — každý řádek z levé kombinovaný s každým z pravé. Pozor na velikost výsledku!</p><pre><code>-- Všechny kombinace uživatelů a kurzů\nSELECT u.jmeno, c.title\nFROM users u\nCROSS JOIN courses c;</code></pre><h2>SELF JOIN</h2><p>Tabulka se spojuje sama se sebou — potřebuješ dva aliasy.</p><pre><code>-- Najdi lekce se stejným typem v kurzu\nSELECT l1.title AS lekce1, l2.title AS lekce2, l1.lesson_type\nFROM lessons l1\nINNER JOIN lessons l2 ON l1.lesson_type = l2.lesson_type\n    AND l1.course_id = l2.course_id\n    AND l1.id < l2.id;</code></pre>', 'lesson', 5, 10, 18),

(@kurs_id, 'INSERT + UPDATE + DELETE', '<h2>INSERT INTO</h2><p><code>INSERT</code> vkládá nové řádky do tabulky.</p><pre><code>-- Vložení jednoho řádku\nINSERT INTO users (jmeno, email, xp)\nVALUES (''Petra'', ''petra@vevit.cz'', 0);\n\n-- Vložení více řádků najednou\nINSERT INTO courses (slug, title, difficulty, xp_reward, sort_order)\nVALUES\n  (''javascript'', ''JavaScript kurz'', ''beginner'', 500, 3),\n  (''react'', ''React kurz'', ''intermediate'', 600, 4);\n\n-- INSERT ze SELECT (kopie dat mezi tabulkami)\nINSERT INTO user_progress (user_id, course_id, xp_ziskano)\nSELECT id, 1, 0 FROM users WHERE xp > 0;</code></pre><h2>UPDATE SET WHERE</h2><p><code>UPDATE</code> mění existující data. <strong>VŽDY používej WHERE</strong>, jinak aktualizuješ VŠECHNY řádky!</p><pre><code>-- Přidání XP konkrétnímu uživateli\nUPDATE users SET xp = xp + 50 WHERE id = 1;\n\n-- Změna e-mailu\nUPDATE users SET email = ''novy@vevit.cz'' WHERE id = 3;\n\n-- BEZPEČNOST: Zobraz nejprve, co se změní\nSELECT * FROM users WHERE id = 1;\n-- Teprve pak aktualizuj\nUPDATE users SET xp = xp + 50 WHERE id = 1;</code></pre><h2>DELETE WHERE</h2><p><code>DELETE</code> odstraňuje řádky. <strong>Opět VŽDY s WHERE!</strong></p><pre><code>-- Smazání konkrétního progress záznamu\nDELETE FROM user_progress WHERE user_id = 5 AND course_id = 2;\n\n-- Smazání všech záznamů starších 30 dní\nDELETE FROM user_progress\nWHERE completed_at < DATE_SUB(NOW(), INTERVAL 30 DAY);\n\n-- POZOR: DELETE bez WHERE smaže VŠECHNY řádky!\n-- DELETE FROM user_progress;  -- NEBEZPEČNÉ!</code></pre><p>Tip: Místo <code>DELETE</code> zvaž logické mazání — přidej sloupec <code>deleted_at</code> a měň jeho hodnotu.</p>', 'lesson', 6, 10, 15),

(@kurs_id, 'CREATE TABLE + ALTER TABLE + DROP', '<h2>CREATE TABLE</h2><p>Vytvoření nové tabulky se sloupci, datovými typy a omezeními.</p><pre><code>CREATE TABLE users (\n  id INT AUTO_INCREMENT PRIMARY KEY,\n  jmeno VARCHAR(100) NOT NULL,\n  email VARCHAR(200) NOT NULL UNIQUE,\n  xp INT DEFAULT 0,\n  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP\n);\n\nCREATE TABLE courses (\n  id INT AUTO_INCREMENT PRIMARY KEY,\n  slug VARCHAR(50) NOT NULL UNIQUE,\n  title VARCHAR(200) NOT NULL,\n  description TEXT,\n  difficulty VARCHAR(20) DEFAULT ''beginner'',\n  xp_reward INT DEFAULT 0,\n  is_active TINYINT(1) DEFAULT 1,\n  sort_order INT DEFAULT 0,\n  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP\n);\n\nCREATE TABLE user_progress (\n  id INT AUTO_INCREMENT PRIMARY KEY,\n  user_id INT NOT NULL,\n  lesson_id INT NOT NULL,\n  course_id INT NOT NULL,\n  completed_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,\n  xp_ziskano INT DEFAULT 0,\n  skore INT DEFAULT 0\n);</code></pre><h2>ALTER TABLE</h2><p>Změna existující tabulky — přidání, úprava nebo odstranění sloupce.</p><pre><code>-- Přidání sloupce\nALTER TABLE users ADD avatar_url VARCHAR(500) NULL;\n\n-- Změna datového typu sloupce\nALTER TABLE users MODIFY COLUMN xp BIGINT DEFAULT 0;\n\n-- Přejmenování sloupce\nALTER TABLE users CHANGE COLUMN jmeno username VARCHAR(100) NOT NULL;\n\n-- Odstranění sloupce\nALTER TABLE users DROP COLUMN avatar_url;</code></pre><h2>DROP TABLE</h2><p><code>DROP TABLE</code> trvale smaže celou tabulku včetně všech dat. <strong>Nevratná operace!</strong></p><pre><code>-- Smazání tabulky (POZOR: nevratné!)\nDROP TABLE IF EXISTS old_table;\n\n-- Smazání celé databáze\nDROP DATABASE IF EXISTS test_db;</code></pre>', 'lesson', 7, 10, 15),

(@kurs_id, 'Indexy základy', '<h2>Co je index</h2><p>Index je datová struktura, která urychluje vyhledávání v tabulce — podobně jako rejstřík v knize. Bez indexu musí databáze projít všechny řádky (full table scan).</p><pre><code>-- Vytvoření běžného indexu\nCREATE INDEX idx_users_email ON users(email);\n\n-- Vytvoření indexu na více sloupcích (composite)\nCREATE INDEX idx_progress_user_course\nON user_progress(user_id, course_id);</code></pre><h2>Typy klíčů a indexů</h2><ul><li><strong>PRIMARY KEY</strong> — unikátní identifikátor řádku, automaticky indexován, jen jeden na tabulku</li><li><strong>UNIQUE</strong> — hodnota musí být unikátní v tabulce, automaticky indexován</li><li><strong>INDEX</strong> — běžný neunikátní index pro zrychlení dotazů</li></ul><pre><code>-- PRIMARY KEY při vytvoření tabulky\nCREATE TABLE level_thresholds (\n  level INT PRIMARY KEY,\n  xp_required INT NOT NULL\n);\n\n-- UNIQUE index\nCREATE UNIQUE INDEX idx_courses_slug ON courses(slug);\n\n-- Odebrání indexu\nDROP INDEX idx_users_email ON users;</code></pre><h2>Kdy index pomáhá</h2><ul><li>Sloupec v klauzuli WHERE</li><li>Sloupec v JOIN ON</li><li>Sloupec v ORDER BY</li><li>Sloupec v GROUP BY</li></ul><p>Kdy index NEPOMÁHÁ nebo škodí:</p><ul><li>Tabulka s málo řádky (scan je stejně rychlý)</li><li>Časté INSERT/UPDATE — index se musí aktualizovat</li><li>Vysoká kardinalita (skoro všechny hodnoty jsou unikátní, ale hledáš malé množství)</li></ul><h2>EXPLAIN úvod</h2><p><code>EXPLAIN</code> ukáže, jak databáze provede dotaz — zda použije index nebo full table scan.</p><pre><code>EXPLAIN SELECT * FROM users WHERE email = ''karel@vevit.cz'';\n\n-- type: ref = použit index\n-- type: ALL = full table scan (špatně!)</code></pre>', 'lesson', 8, 10, 15),

(@kurs_id, 'Transakce + ACID', '<h2>Co je transakce</h2><p>Transakce je sada SQL operací, které se provedou <strong>atomicky</strong> — buď všechny uspějí, nebo žádná. Zabraňuje nekonzistentním datům při chybách.</p><pre><code>-- Začátek transakce\nSTART TRANSACTION;\n\nUPDATE users SET xp = xp + 50 WHERE id = 1;\nINSERT INTO user_progress (user_id, lesson_id, course_id, xp_ziskano)\nVALUES (1, 5, 1, 50);\n\n-- Vše v pořádku — potvrdíme\nCOMMIT;\n\n-- Pokud něco selhalo — vrátíme zpět\n-- ROLLBACK;</code></pre><h2>ACID vlastnosti</h2><ul><li><strong>Atomicity</strong> — Vše nebo nic. Buď se provedou všechny operace, nebo žádná.</li><li><strong>Consistency</strong> — Po transakci jsou data v konzistentním stavu (constraints, FK).</li><li><strong>Isolation</strong> — Souběžné transakce se navzájem neovlivňují.</li><li><strong>Durability</strong> — Po COMMIT jsou data trvale uložena i při výpadku napájení.</li></ul><h2>Příklad s user_progress</h2><pre><code>-- Přidání XP a záznamu o dokončení — atomicky\nSTART TRANSACTION;\n\nUPDATE users SET xp = xp + 15 WHERE id = 2;\n\nINSERT INTO user_progress (user_id, lesson_id, course_id, xp_ziskano, skore)\nVALUES (2, 10, 1, 15, 100);\n\n-- Kontrola: máme správná data?\nSELECT xp FROM users WHERE id = 2;\n\n-- Vše OK → COMMIT\nCOMMIT;\n\n-- Chyba → ROLLBACK (vrátí obě operace)\n-- ROLLBACK;</code></pre><p><strong>Důležité:</strong> V phpMyAdmin můžeš transakce spouštět v SQL okně. Pokud neprovedeš COMMIT, změny se po odpojení automaticky ROLLBACKnou.</p>', 'lesson', 9, 10, 15),

(@kurs_id, 'Datové typy (přehled)', '<h2>Číselné typy</h2><ul><li><code>INT</code> — celé číslo, běžně dostačující (cca 2 miliardy)</li><li><code>BIGINT</code> — velké celé číslo (pro ID u velkých tabulek)</li><li><code>TINYINT</code> — malé číslo (0-255), často pro boolean (0/1)</li><li><code>DECIMAL(m,d)</code> — přesné desetinné číslo (peníze!)</li><li><code>FLOAT / DOUBLE</code> — přibližné desetinné (vědecké výpočty)</li></ul><pre><code>CREATE TABLE produkty (\n  id INT AUTO_INCREMENT PRIMARY KEY,\n  nazev VARCHAR(200),\n  cena DECIMAL(10,2) NOT NULL,  -- max 99999999.99\n  skladem INT DEFAULT 0\n);</code></pre><h2>Řetězcové typy</h2><ul><li><code>VARCHAR(n)</code> — proměnlivá délka, max n znaků (jména, e-maily)</li><li><code>TEXT</code> — dlouhý text (popisy, obsah lekcí)</li><li><code>CHAR(n)</code> — pevná délka (kódy, zkratky)</li></ul><h2>Datum a čas</h2><ul><li><code>DATE</code> — pouze datum (YYYY-MM-DD)</li><li><code>DATETIME</code> — datum a čas (YYYY-MM-DD HH:MM:SS)</li><li><code>TIMESTAMP</code> — jako DATETIME, ale automaticky se aktualizuje, rozsah 1970-2038</li></ul><pre><code>CREATE TABLE udalosti (\n  id INT AUTO_INCREMENT PRIMARY KEY,\n  nazev VARCHAR(200),\n  datum DATE,\n  vytvoreno TIMESTAMP DEFAULT CURRENT_TIMESTAMP\n);</code></pre><h2>Speciální typy</h2><ul><li><code>ENUM(''a'',''b'',''c'')</code> — pevný seznam hodnot (difficulty: beginner/intermediate/advanced)</li><li><code>BLOB</code> — binární data (obrázky, soubory — ale lépe ukládat jen cestu)</li><li><code>JSON</code> — JSON dokument (MariaDB 10.2+)</li></ul><pre><code>CREATE TABLE courses (\n  difficulty ENUM(''beginner'',''intermediate'',''advanced'')\n    DEFAULT ''beginner'',\n  metadata JSON NULL\n);</code></pre>', 'lesson', 10, 10, 15);


-- ============================================================
-- KVÍZ 1: Základy SQL (sort_order 11)
-- ============================================================

INSERT INTO lessons (course_id, title, content, lesson_type, sort_order, xp_reward, duration_minutes) VALUES
(@kurs_id, 'Kvíz 1 — Základy SQL', '<p>Ověř znalosti SELECT, WHERE, JOIN, agregací, DML a transakcí.</p>', 'quiz', 11, 50, 12);

SET @q1 = LAST_INSERT_ID();

INSERT INTO quizzes (lesson_id, question, option_a, option_b, option_c, option_d, correct_answer, explanation, sort_order) VALUES
(@q1, 'Který příkaz vrátí všechny sloupce z tabulky users?', 'SELECT ALL FROM users', 'SELECT * FROM users', 'GET * FROM users', 'FETCH users', 'b', 'SELECT * je standardní SQL zápis pro výběr všech sloupců z tabulky.', 1),
(@q1, 'Jaký je rozdíl mezi WHERE a HAVING?', 'Žádný rozdíl', 'WHERE filtruje před agregací, HAVING po agregaci', 'HAVING je rychlejší', 'WHERE nefunguje s GROUP BY', 'b', 'WHERE filtruje jednotlivé řádky před GROUP BY, HAVING filtruje skupiny po agregaci.', 2),
(@q1, 'Co vrací LEFT JOIN když v pravé tabulce není shoda?', 'Prázdný výsledek', 'Chybu', 'NULL hodnoty pro sloupce pravé tabulky', 'Všechny sloupce z obou tabulek', 'c', 'LEFT JOIN vrací všechny řádky z levé tabulky. Pokud v pravé není shoda, doplní NULL.', 3),
(@q1, 'Co se stane při UPDATE bez WHERE?', 'Nic', 'Aktualizuje se první řádek', 'Aktualizují se VŠECHNY řádky v tabulce', 'Chyba', 'c', 'UPDATE bez WHERE změní všechny řádky v tabulce — velmi nebezpečné!', 4),
(@q1, 'Co je PRIMARY KEY?', 'Běžný index', 'Unikátní identifikátor řádku v tabulce', 'Cizí klíč', 'Typ dat', 'b', 'PRIMARY KEY je unikátní identifikátor — žádné duplikáty, žádné NULL.', 5),
(@q1, 'Co znamená A v zkratce ACID?', 'Asynchronous', 'Aggregation', 'Atomicity — vše nebo nic', 'Alter', 'c', 'Atomicity znamená, že transakce se provede celá nebo vůbec — žádný částečný stav.', 6),
(@q1, 'Který datový typ je nejvhodnější pro peněžní částky?', 'FLOAT', 'INT', 'VARCHAR', 'DECIMAL(10,2)', 'd', 'DECIMAL zaručuje přesnost desetinných čísel — FLOAT může způsobit zaokrouhlovací chyby.', 7),
(@q1, 'Co vrací INNER JOIN na rozdíl od LEFT JOIN?', 'Všechny řádky z obou tabulek', 'Pouze řádky se shodou v obou tabulkách', 'Všechny řádky z levé tabulky', 'Karteziánský součin', 'b', 'INNER JOIN vrátí pouze řádky, které mají odpovídající záznam v obou tabulkách.', 8);


-- ============================================================
-- SEKCE 2: Pokročilé (sort_order 12-34)
-- ============================================================

INSERT INTO lessons (course_id, title, content, lesson_type, sort_order, xp_reward, duration_minutes) VALUES
(@kurs_id, 'Subqueries + EXISTS', '<h2>Vnořené SELECTy (subqueries)</h2><p>Subquery je dotaz uvnitř jiného dotazu. Může být v klauzuli WHERE, FROM nebo SELECT.</p><pre><code>-- Uživatelé, kteří dokončili kurz Python\nSELECT jmeno FROM users\nWHERE id IN (\n    SELECT user_id FROM user_progress\n    WHERE course_id = (SELECT id FROM courses WHERE slug = ''python'')\n);\n\n-- Subquery ve FROM (derived table)\nSELECT avg_xp\nFROM (\n    SELECT course_id, AVG(skore) AS avg_xp\n    FROM user_progress\n    GROUP BY course_id\n) AS souhrn\nWHERE avg_xp > 70;</code></pre><h2>Correlated subqueries</h2><p>Correlated subquery odkazuje na sloupce z vnějšího dotazu — spustí se pro každý řádek vnějšího dotazu.</p><pre><code>-- Uživatelé s XP nad průměrem\nSELECT jmeno, xp FROM users u\nWHERE xp > (\n    SELECT AVG(xp) FROM users\n);\n\n-- Nejnovější progress pro každého uživatele\nSELECT u.jmeno, up.completed_at\nFROM users u\nINNER JOIN user_progress up ON u.id = up.user_id\nWHERE up.completed_at = (\n    SELECT MAX(up2.completed_at)\n    FROM user_progress up2\n    WHERE up2.user_id = u.id\n);</code></pre><h2>EXISTS / NOT EXISTS</h2><p><code>EXISTS</code> vrací TRUE, pokud subquery vrací alespoň jeden řádek. Efektivnější než IN u velkých podmnožin.</p><pre><code>-- Kurzy, které mají alespoň jednu lekci\nSELECT title FROM courses c\nWHERE EXISTS (\n    SELECT 1 FROM lessons l WHERE l.course_id = c.id\n);\n\n-- Uživatelé, kteří NEdokončili žádnou lekci\nSELECT jmeno FROM users u\nWHERE NOT EXISTS (\n    SELECT 1 FROM user_progress up WHERE up.user_id = u.id\n);</code></pre><h2>Performance</h2><p>Correlated subqueries mohou být pomalé (spouští se pro každý řádek). Často je lze přepsat jako JOIN — databáze je optimalizuje lépe.</p>', 'lesson', 12, 15, 18),

(@kurs_id, 'CTE (WITH)', '<h2>Common Table Expressions</h2><p><code>CTE</code> (Common Table Expression) je pojmenovaný dočasný výsledek dotazu definovaný klauzulí <code>WITH</code>. Čitelnější než subquery ve FROM.</p><pre><code>-- CTE: průměrné skóre v kurzech\nWITH kurz_stats AS (\n    SELECT course_id,\n           COUNT(*) AS pocet,\n           AVG(skore) AS prumer\n    FROM user_progress\n    GROUP BY course_id\n)\nSELECT c.title, ks.pocet, ks.prumer\nFROM kurz_stats ks\nINNER JOIN courses c ON ks.course_id = c.id\nORDER BY ks.prumer DESC;</code></pre><h2>Vícenásobné CTE</h2><pre><code>-- Dvě CTE najednou\nWITH aktivni AS (\n    SELECT user_id, COUNT(*) AS lekce_dokonceno\n    FROM user_progress\n    WHERE completed_at > DATE_SUB(NOW(), INTERVAL 30 DAY)\n    GROUP BY user_id\n),\nleaderboard AS (\n    SELECT u.jmeno, a.lekce_dokonceno, u.xp\n    FROM aktivni a\n    INNER JOIN users u ON a.user_id = u.id\n)\nSELECT * FROM leaderboard ORDER BY xp DESC LIMIT 10;</code></pre><h2>Rekurzivní CTE</h2><p>Rekurzivní CTE odkazuje samo na sebe — užitečné pro hierarchická data (stromové struktury).</p><pre><code>-- Generování řady čísel 1-10\nWITH RECURSIVE cisla AS (\n    SELECT 1 AS n\n    UNION ALL\n    SELECT n + 1 FROM cisla WHERE n < 10\n)\nSELECT * FROM cisla;\n\n-- Hierarchie kurzů a lekcí (pokud by lekce měly pod-lekce)\nWITH RECURSIVE hierarchie AS (\n    SELECT id, title, course_id, 0 AS uroven\n    FROM lessons\n    WHERE lesson_type = ''lesson''\n    UNION ALL\n    SELECT l.id, l.title, l.course_id, h.uroven + 1\n    FROM lessons l\n    INNER JOIN hierarchie h ON l.course_id = h.course_id\n    WHERE l.lesson_type = ''quiz'' AND h.uroven < 1\n)\nSELECT * FROM hierarchie;</code></pre>', 'lesson', 13, 15, 18),

(@kurs_id, 'Window functions', '<h2>Co jsou window functions</h2><p>Window funkce počítají výsledek přes sadu řádků (okno) <strong>bez seskupení</strong> — na rozdíl od GROUP BY. Klauzule <code>OVER()</code> definuje okno.</p><pre><code>-- RANK: pořadí uživatelů podle XP\nSELECT jmeno, xp,\n    RANK() OVER (ORDER BY xp DESC) AS poradi\nFROM users;\n\n-- DENSE_RANK: bez mezer v pořadí\nSELECT jmeno, xp,\n    DENSE_RANK() OVER (ORDER BY xp DESC) AS poradi\nFROM users;</code></pre><h2>RANK vs DENSE_RANK vs ROW_NUMBER</h2><ul><li><code>ROW_NUMBER</code> — unikátní číslo pro každý řádek (1,2,3,4)</li><li><code>RANK</code> — stejné hodnoty dostanou stejné pořadí, následující se přeskočí (1,2,2,4)</li><li><code>DENSE_RANK</code> — stejné pořadí, ale bez mezer (1,2,2,3)</li></ul><pre><code>SELECT jmeno, xp,\n    ROW_NUMBER() OVER (ORDER BY xp DESC) AS rn,\n    RANK() OVER (ORDER BY xp DESC) AS rnk,\n    DENSE_RANK() OVER (ORDER BY xp DESC) AS drnk\nFROM users;</code></pre><h2>LAG / LEAD</h2><p><code>LAG</code> přistupuje k předchozímu řádku, <code>LEAD</code> k následujícímu — užitečné pro rozdíly mezi řádky.</p><pre><code>-- Rozdíl XP oproti předchozímu uživateli\nSELECT jmeno, xp,\n    LAG(xp, 1) OVER (ORDER BY xp DESC) AS predchozi_xp,\n    xp - LAG(xp, 1) OVER (ORDER BY xp DESC) AS rozdil\nFROM users;</code></pre><h2>SUM() OVER a PARTITION BY</h2><pre><code>-- Běžící součet XP\nSELECT jmeno, xp,\n    SUM(xp) OVER (ORDER BY xp DESC) AS bezici_soucet\nFROM users;\n\n-- Součet XP v rámci kurzů (partition)\nSELECT up.user_id, up.course_id, up.xp_ziskano,\n    SUM(up.xp_ziskano) OVER (PARTITION BY up.course_id) AS kurz_total\nFROM user_progress up;</code></pre>', 'lesson', 14, 15, 20),

(@kurs_id, 'Stored procedures', '<h2>Co jsou stored procedures</h2><p>Stored procedure je uložená rutina v databázi — opakovaně použitelný blok SQL. <strong>Problém:</strong> MariaDB 10.4 na phpMyAdmin vyžaduje <code>DELIMITER</code>, který phpMyAdmin nepodporuje.</p><pre><code>-- Standardní syntax (v CLI):\n-- DELIMITER //\n-- CREATE PROCEDURE pridat_xp(IN p_user_id INT, IN p_xp INT)\n-- BEGIN\n--     UPDATE users SET xp = xp + p_xp WHERE id = p_user_id;\n--     INSERT INTO user_progress (user_id, course_id, xp_ziskano)\n--     VALUES (p_user_id, 1, p_xp);\n-- END //\n-- DELIMITER ;\n\n-- Volání procedury\n-- CALL pridat_xp(1, 50);</code></pre><h2>phpMyAdmin DELIMITER workaround</h2><p>V phpMyAdmin nelze přímo měnit DELIMITER. Řešení:</p><ul><li><strong>Možnost 1:</strong> Použij CLI klienta (mysql -u user -p) pro vytváření procedur</li><li><strong>Možnost 2:</strong> V phpMyAdmin jdi do záložky <em>Routines</em> a vytvoř proceduru přes GUI</li><li><strong>Možnost 3:</strong> Napiš logiku v PHP místo v databázi</li></ul><h2>Alternativy v PHP</h2><pre><code>-- Místo stored procedur použij PHP s PDO:\n/*\n$pdo = new PDO($dsn, $user, $pass);\n$pdo->beginTransaction();\n$pdo->prepare("UPDATE users SET xp = xp + ? WHERE id = ?")\n    ->execute([$xp, $userId]);\n$pdo->prepare("INSERT INTO user_progress ...")->execute([...]);\n$pdo->commit();\n*/</code></pre><p><strong>Recommendation:</strong> Pro Websupport/Wedos hosting je nejjednodušší psát logiku v PHP a SQL používat jen pro dotazy. Stored procedures jsou užitečné pro složitou logiku na DB serveru, ale na sdíleném hostingu je často nelze vytvořit.</p>', 'lesson', 15, 15, 15),

(@kurs_id, 'Triggery', '<h2>Co jsou triggery</h2><p>Trigger je kód, který se automaticky spustí při INSERT, UPDATE nebo DELETE na tabulce. Mohou být <code>BEFORE</code> (před operací) nebo <code>AFTER</code> (po operaci).</p><pre><code>-- Standardní syntax (vyžaduje DELIMITER v CLI):\n-- DELIMITER //\n-- CREATE TRIGGER log_xp_change\n-- AFTER UPDATE ON users\n-- FOR EACH ROW\n-- BEGIN\n--     IF NEW.xp != OLD.xp THEN\n--         INSERT INTO xp_log (user_id, old_xp, new_xp, changed_at)\n--         VALUES (NEW.id, OLD.xp, NEW.xp, NOW());\n--     END IF;\n-- END //\n-- DELIMITER ;</code></pre><h2>NEW a OLD</h2><ul><li><code>NEW</code> — hodnoty řádku PO operaci (INSERT, UPDATE)</li><li><code>OLD</code> — hodnoty řádku PŘED operací (UPDATE, DELETE)</li></ul><pre><code>-- BEFORE INSERT: nastav výchozí hodnotu\n-- CREATE TRIGGER set_default_xp\n-- BEFORE INSERT ON users\n-- FOR EACH ROW\n-- BEGIN\n--     IF NEW.xp IS NULL THEN\n--         SET NEW.xp = 0;\n--     END IF;\n-- END //</code></pre><h2>Omezení triggerů</h2><ul><li>Nelze měnit tabulku, na které je trigger navázán (v MySQL/MariaDB)</li><li>Mohou způsobit kaskádové efekty (trigger spustí jiný trigger)</li><li>Obtížné ladění — běží na pozadí</li><li>Stejný problém s DELIMITER v phpMyAdmin jako u stored procedures</li></ul><h2>Logování pomocí triggerů</h2><p>Typické využití: audit log — zaznamenání změn do samostatné tabulky.</p><pre><code>-- Vytvoření logovací tabulky\nCREATE TABLE xp_log (\n    id INT AUTO_INCREMENT PRIMARY KEY,\n    user_id INT NOT NULL,\n    old_xp INT,\n    new_xp INT,\n    changed_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP\n);\n\n-- V phpMyAdmin: vytvoř trigger přes záložku Triggers\n-- nebo přes CLI s DELIMITER</code></pre>', 'lesson', 16, 15, 15),

(@kurs_id, 'Views', '<h2>CREATE VIEW</h2><p>View je uložený dotaz, který se chová jako virtuální tabulka. Zjednodušuje složité dotazy a centralizuje logiku.</p><pre><code>-- View: leaderboard uživatelů\nCREATE VIEW v_leaderboard AS\nSELECT u.id, u.jmeno, u.xp,\n    COUNT(up.id) AS dokoncenych_lekci,\n    AVG(up.skore) AS prumerne_skore\nFROM users u\nLEFT JOIN user_progress up ON u.id = up.user_id\nGROUP BY u.id, u.jmeno, u.xp\nORDER BY u.xp DESC;\n\n-- Použití view jako tabulky\nSELECT * FROM v_leaderboard LIMIT 10;\nSELECT jmeno, xp FROM v_leaderboard WHERE dokoncenych_lekci > 5;</code></pre><h2>Aktualizovatelné views</h2><p>Některé view lze aktualizovat přímo (INSERT/UPDATE/DELETE). Podmínka: view musí být jednoduché (jedna tabulka, žádné agregace, DISTINCT, GROUP BY).</p><pre><code>-- Toto view JE aktualizovatelné\nCREATE VIEW v_aktivni_users AS\nSELECT id, jmeno, email, xp\nFROM users\nWHERE xp > 0;\n\nUPDATE v_aktivni_users SET xp = xp + 10 WHERE id = 1;  -- funguje!</code></pre><h2>WITH CHECK OPTION</h2><p>Zabrání INSERT/UPDATE, který by řádek učinil neviditelným pro view.</p><pre><code>CREATE VIEW v_aktivni_users AS\nSELECT id, jmeno, email, xp\nFROM users\nWHERE xp > 0\nWITH CHECK OPTION;\n\n-- Toto SELŽE — řádek by nebyl vidět ve view\n-- INSERT INTO v_aktivni_users (jmeno, email, xp) VALUES (''Test'', ''t@t.cz'', 0);</code></pre><h2>Správa views</h2><pre><code>-- Změna view\nCREATE OR REPLACE VIEW v_leaderboard AS\nSELECT u.jmeno, u.xp FROM users u ORDER BY u.xp DESC;\n\n-- Smazání view\nDROP VIEW IF EXISTS v_leaderboard;\n\n-- Seznam views\nSHOW FULL TABLES WHERE table_type = ''VIEW'';</code></pre>', 'lesson', 17, 15, 15),

(@kurs_id, 'EXPLAIN + analýza výkonu', '<h2>Příkaz EXPLAIN</h2><p><code>EXPLAIN</code> ukáže, jak MariaDB provede dotaz — jaké tabulky, indexy a strategie použije.</p><pre><code>EXPLAIN SELECT * FROM users WHERE email = ''karel@vevit.cz'';</code></pre><h2>Klíčové sloupce EXPLAIN</h2><ul><li><strong>type</strong> — způsob přístupu (od nejlepšího po nejhorší): <code>system > const > eq_ref > ref > range > index > ALL</code></li><li><strong>key</strong> — použitý index (NULL = full table scan)</li><li><strong>rows</strong> — odhad prohledaných řádků</li><li><strong>Extra</strong> — dodatečné info (Using index, Using filesort, Using temporary)</li></ul><pre><code>-- type = ALL → full table scan (ŠPATNĚ pro velké tabulky)\nEXPLAIN SELECT * FROM users;\n\n-- type = ref → použit index (DOBŘE)\nEXPLAIN SELECT * FROM users WHERE email = ''karel@vevit.cz'';\n\n-- type = range → index pro rozsah\nEXPLAIN SELECT * FROM users WHERE xp BETWEEN 100 AND 500;</code></pre><h2>EXPLAIN ANALYZE (MariaDB 10.1+)</h2><p>Rozšířený EXPLAIN s reálným měřením času a řádků.</p><pre><code>EXPLAIN ANALYZE\nSELECT u.jmeno, c.title\nFROM users u\nINNER JOIN user_progress up ON u.id = up.user_id\nINNER JOIN courses c ON up.course_id = c.id\nWHERE u.xp > 100;</code></pre><h2>Časté problémy a řešení</h2><ul><li><code>type: ALL</code> → přidej index na sloupce v WHERE</li><li><code>Extra: Using filesort</code> → přidej index na ORDER BY sloupce</li><li><code>Extra: Using temporary</code> → zvaž úpravu GROUP BY nebo přidání indexu</li><li>Vysoký <code>rows</code> → dotaz prohledává příliš mnoho řádků</li></ul>', 'lesson', 18, 15, 18),

(@kurs_id, 'Indexy pokročile', '<h2>B-Tree index</h2><p>Výchozí typ indexu v MariaDB. Vhodný pro =, >, <, BETWEEN, LIKE ''prefix%''. Nevhodný pro LIKE ''%suffix''.</p><h2>FULLTEXT index</h2><p>Pro fulltextové vyhledávání v textových sloupcích. Viz lekce o fulltext search.</p><pre><code>CREATE FULLTEXT INDEX idx_fulltext_title ON courses(title);\nSELECT * FROM courses WHERE MATCH(title) AGAINST(''Python'');</code></pre><h2>Composite indexy</h2><p>Index na více sloupcích. <strong>Pořadí sloupců v indexu záleží!</strong> Platí pravidlo nejvíce selektivního sloupce jako první (pro equality).</p><pre><code>-- Composite index\nCREATE INDEX idx_progress_user_course\nON user_progress(user_id, course_id);\n\n-- Tento dotaz POUŽIJE index\nSELECT * FROM user_progress WHERE user_id = 1 AND course_id = 2;\n\n-- Tento také (prefix indexu)\nSELECT * FROM user_progress WHERE user_id = 1;\n\n-- Tento NEPOUŽIJE index (course_id je až druhý)\nSELECT * FROM user_progress WHERE course_id = 2;</code></pre><h2>Covering index</h2><p>Pokud index obsahuje všechny sloupce dotazu, databáze nemusí číst samotnou tabulku — vše najde v indexu.</p><pre><code>-- Covering index: xp je součástí indexu\nCREATE INDEX idx_user_xp ON users(id, xp);\n\n-- Tento dotaz přečte POUZE index (Extra: Using index)\nEXPLAIN SELECT xp FROM users WHERE id = 1;</code></pre><h2>Index hints</h2><p>Pokud optimalizátor zvolí špatný index, můžeš ho navigovat.</p><pre><code>-- Vynutit použití konkrétního indexu\nSELECT * FROM users USE INDEX(idx_email)\nWHERE email = ''karel@vevit.cz'';\n\n-- Zakázat použití indexu\nSELECT * FROM users IGNORE INDEX(idx_email)\nWHERE email = ''karel@vevit.cz'';</code></pre>', 'lesson', 19, 15, 18),

(@kurs_id, 'Normalizace (1NF/2NF/3NF)', '<h2>Proč normalizovat</h2><p>Normalizace odstraňuje <strong>anomálie</strong> — problémy při vkládání, aktualizaci a mazání dat v nenormalizované tabulce.</p><p>Příklady anomálií (denormalizovaná tabulka):</p><pre><code>-- ŠPATNĚ: uživatel a kurz v jedné tabulce\n-- | user_id | jmeno | email    | course_title |\n-- |---------|-------|----------|--------------|\n-- | 1       | Karel | k@v.cz   | Python       |\n-- | 1       | Karel | k@v.cz   | SQL          |  ← duplicita jména a e-mailu!\n\n-- Insert anomálie: nelze vložit uživatele bez kurzu\n-- Update anomálie: změna e-mailu vyžaduje aktualizaci více řádků\n-- Delete anomálie: smazání posledního kurzu smaže i uživatele</code></pre><h2>1NF — První normální forma</h2><ul><li>Každý sloupec obsahuje atomické (nedělitelné) hodnoty</li><li>Žádné opakující se skupiny sloupců</li><li>Každý řádek je unikátní (potřebuje PK)</li></ul><h2>2NF — Druhá normální forma</h2><ul><li>Splňuje 1NF</li><li>Každý neceločíslicový atribut závisí na CELÉM primárním klíči (ne jen na části)</li><li>Relevantní pro složené PK</li></ul><h2>3NF — Třetí normální forma</h2><ul><li>Splňuje 2NF</li><li>Žádné tranzitivní závislosti — neceločíslicový atribut nezávisí na jiném neceločíslicovém atributu</li></ul><pre><code>-- Normalizované schéma VeVit:\n-- users (id PK, jmeno, email, xp)         ← bez duplicity\n-- courses (id PK, slug, title, difficulty) ← bez duplicity\n-- user_progress (id PK, user_id FK, course_id FK, skore)  ← spojovací tabulka</code></pre><h2>Denormalizace pro výkon</h2><p>Někdy je záměrné porušení normalizace výhodné — například uložení počítaného součtu XP přímo v tabulce users místo počítání SUM při každém dotazu. Zvaž kompromis mezi konzistencí a rychlostí.</p>', 'lesson', 20, 15, 18),

(@kurs_id, 'Transakce pokročile', '<h2>Isolation levels</h2><p>Isolation level určuje, jak moc se souběžné transakce navzájem vidí. MariaDB podporuje 4 úrovně:</p><pre><code>-- Zjištění aktuální úrovně\nSELECT @@transaction_isolation;\n\n-- Nastavení úrovně pro session\nSET SESSION TRANSACTION ISOLATION LEVEL READ COMMITTED;</code></pre><ul><li><strong>READ UNCOMMITTED</strong> — čte i necommitnutá data (dirty read), nejrychlejší, nejmenší izolace</li><li><strong>READ COMMITTED</strong> — čte jen commitnutá data, ale dvě čtení v rámci transakce mohou vrátit různé výsledky (non-repeatable read)</li><li><strong>REPEATABLE READ</strong> — výchozí v MariaDB/MySQL. Konzistentní čtení v rámci transakce, ale mohou nastat phantom reads</li><li><strong>SERIALIZABLE</strong> — nejpřísnější, žádné anomálie, ale nejpomalejší (zamyká řádky)</li></ul><h2>Deadlocks</h2><p>Deadlock nastane, když dvě transakce čekají na zámky, které drží ta druhá. MariaDB detekuje deadlock a automaticky ROLLBACKne jednu transakci.</p><pre><code>-- Transakce A:\nSTART TRANSACTION;\nUPDATE users SET xp = xp + 10 WHERE id = 1;  -- lock na id=1\n-- UPDATE users SET xp = xp + 20 WHERE id = 2;  -- čeká na lock id=2 (drží B)\n\n-- Transakce B (souběžně):\nSTART TRANSACTION;\nUPDATE users SET xp = xp + 30 WHERE id = 2;  -- lock na id=2\n-- UPDATE users SET xp = xp + 40 WHERE id = 1;  -- čeká na lock id=1 (drží A)\n-- → DEADLOCK! MariaDB automaticky ROLLBACKne jednu z nich</code></pre><h2>Optimistické zamykání</h2><p>Místo zámku přidáme sloupec <code>version</code> — při UPDATE zkontrolujeme, že se nezměnil.</p><pre><code>-- Tabulka s verzí\nALTER TABLE users ADD COLUMN version INT DEFAULT 1;\n\n-- Optimistický UPDATE\nUPDATE users\nSET xp = xp + 50, version = version + 1\nWHERE id = 1 AND version = 5;\n\n-- Pokud affected_rows = 0, někdo změnil data před námi → opakuj</code></pre>', 'lesson', 21, 15, 20),

(@kurs_id, 'JSON v MySQL', '<h2>JSON datový typ</h2><p>MariaDB 10.2+ podporuje nativní JSON typ. Umožňuje ukládat flexibilní strukturovaná data bez nutnosti dalších tabulek.</p><pre><code>-- Vložení JSON dat\nINSERT INTO courses (slug, title, difficulty, metadata)\nVALUES (''python'', ''Python kurz'', ''beginner'',\n    JSON_OBJECT(\n        ''author'', ''Tym VeVit'',\n        ''tags'', JSON_ARRAY(''programovani'', ''zacatecnik''),\n        ''rating'', 4.8\n    )\n);</code></pre><h2>JSON_EXTRACT a zkratka -></h2><pre><code>-- Extrakce hodnoty z JSON\nSELECT JSON_EXTRACT(metadata, ''$.author'') FROM courses;\n\n-- Zkrácený zápis (MariaDB 10.2+)\nSELECT metadata->''$.author'' FROM courses;\nSELECT metadata->''$.tags[0]'' FROM courses;\n\n-- Zobrazení bez uvozovek (MariaDB 10.2+)\nSELECT JSON_UNQUOTE(metadata->''$.author'') AS autor\nFROM courses;</code></pre><h2>JSON_SET a JSON_REPLACE</h2><pre><code>-- Změna hodnoty v JSON\nUPDATE courses\nSET metadata = JSON_SET(metadata, ''$.rating'', 4.9)\nWHERE slug = ''python'';\n\n-- Nahrazení hodnoty (neexistující → nepřidá)\nUPDATE courses\nSET metadata = JSON_REPLACE(metadata, ''$.rating'', 5.0)\nWHERE slug = ''python'';</code></pre><h2>Virtual columns a indexování</h2><p>Virtual column extrahuje hodnotu z JSON a umožňuje ji indexovat.</p><pre><code>-- Přidání virtual column\nALTER TABLE courses\nADD COLUMN rating DECIMAL(2,1)\n    GENERATED ALWAYS AS (JSON_EXTRACT(metadata, ''$.rating'')) VIRTUAL;\n\n-- Index na virtual column\nCREATE INDEX idx_rating ON courses(rating);\n\n-- Rychlé hledání přes index\nSELECT title FROM courses WHERE rating > 4.5;</code></pre>', 'lesson', 22, 15, 18),

(@kurs_id, 'Fulltext search', '<h2>FULLTEXT index</h2><p>Fulltext index umožňuje rychlé vyhledávání v textu — na rozdíl od LIKE, který prohledává každý řádek.</p><pre><code>-- Vytvoření FULLTEXT indexu\nCREATE FULLTEXT INDEX ft_title_desc ON courses(title, description);\n\n-- Vytvoření při definici tabulky\nCREATE TABLE articles (\n    id INT AUTO_INCREMENT PRIMARY KEY,\n    title VARCHAR(200),\n    body TEXT,\n    FULLTEXT(title, body)\n);</code></pre><h2>MATCH AGAINST</h2><pre><code>-- Natural language mode (výchozí)\nSELECT title FROM courses\nWHERE MATCH(title, description) AGAINST(''programovani'');\n\n-- S relevance skóre\nSELECT title,\n    MATCH(title, description) AGAINST(''programovani'') AS relevance\nFROM courses\nWHERE MATCH(title, description) AGAINST(''programovani'')\nORDER BY relevance DESC;</code></pre><h2>Boolean mode</h2><p>Umožňuje operátory: <code>+</code> (musí obsahovat), <code>-</code> (nesmí obsahovat), <code>*</code> (prefix), <code>""</code> (přesná fráze).</p><pre><code>-- Musí obsahovat "python", nesmí "pokrocily"\nSELECT title FROM courses\nWHERE MATCH(title, description)\n    AGAINST(''+python -pokrocily'' IN BOOLEAN MODE);\n\n-- Prefix: slova začínající na "prog"\nSELECT title FROM courses\nWHERE MATCH(title, description)\n    AGAINST(''prog*'' IN BOOLEAN MODE);\n\n-- Přesná fráze\nSELECT title FROM courses\nWHERE MATCH(title, description)\n    AGAINST(''"relacni databaze"'' IN BOOLEAN MODE);</code></pre><h2>Omezení</h2><ul><li>Minimální délka slova: 3 znaky (InnoDB), 4 znaky (MyISAM)</li><li>Stop words: běžná slova (a, the, is) se ignorují</li><li>Nevhodné pro češtinu bez diakritiky — zvaž externí řešení (Elasticsearch)</li></ul>', 'lesson', 23, 15, 15),

(@kurs_id, 'Partitioning', '<h2>Co je partitioning</h2><p>Partitioning rozdělí velkou tabulku na menší části (partitions) podle zadaného pravidla. Každá partition je uložena jako samostatný soubor. Dotazy omezené na jednu partition jsou rychlejší.</p><h2>RANGE partitioning</h2><pre><code>-- Partitioning podle roku\nCREATE TABLE user_progress_archive (\n    id INT AUTO_INCREMENT,\n    user_id INT NOT NULL,\n    course_id INT NOT NULL,\n    completed_at DATE NOT NULL,\n    xp_ziskano INT DEFAULT 0,\n    PRIMARY KEY (id, completed_at)\n) PARTITION BY RANGE (YEAR(completed_at)) (\n    PARTITION p2022 VALUES LESS THAN (2023),\n    PARTITION p2023 VALUES LESS THAN (2024),\n    PARTITION p2024 VALUES LESS THAN (2025),\n    PARTITION pmax VALUES LESS THAN MAXVALUE\n);</code></pre><h2>LIST partitioning</h2><pre><code>-- Partitioning podle course_id\nCREATE TABLE user_progress_by_course (\n    id INT AUTO_INCREMENT,\n    user_id INT NOT NULL,\n    course_id INT NOT NULL,\n    completed_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,\n    PRIMARY KEY (id, course_id)\n) PARTITION BY LIST (course_id) (\n    PARTITION p_python VALUES IN (1),\n    PARTITION p_sql VALUES IN (2),\n    PARTITION p_js VALUES IN (3),\n    PARTITION p_other VALUES IN (DEFAULT)\n);</code></pre><h2>HASH partitioning</h2><pre><code>-- Automatické rozdělení podle hash user_id\nCREATE TABLE user_progress_hash (\n    id INT AUTO_INCREMENT PRIMARY KEY,\n    user_id INT NOT NULL,\n    course_id INT NOT NULL,\n    completed_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP\n) PARTITION BY HASH(user_id)\nPARTITIONS 4;</code></pre><h2>Kdy partitioning pomáhá</h2><ul><li>Velmi velké tabulky (miliony řádků)</li><li>Často dotazované po datech (RANGE)</li><li>Archivace starých dat (DROP PARTITION je rychlejší než DELETE)</li></ul><h2>Údržba</h2><pre><code>-- Přidání nové partition\nALTER TABLE user_progress_archive\nADD PARTITION (PARTITION p2025 VALUES LESS THAN (2026));\n\n-- Smazání partition (včetně dat!)\nALTER TABLE user_progress_archive DROP PARTITION p2022;</code></pre>', 'lesson', 24, 15, 18),

(@kurs_id, 'Zálohy (mysqldump)', '<h2>mysqldump</h2><p>Standardní nástroj pro zálohování MySQL/MariaDB. Vytvoří SQL soubor s příkazy pro obnovu.</p><pre><code>-- Záloha celé databáze\nmysqldump -u uzivatel -p vevit_db > vevit_backup.sql\n\n-- Záloha konkrétní tabulky\nmysqldump -u uzivatel -p vevit_db users > users_backup.sql\n\n-- Záloha více tabulek\nmysqldump -u uzivatel -p vevit_db users courses lessons > tables_backup.sql\n\n-- Záloha pouze struktury (bez dat)\nmysqldump -u uzivatel -p --no-data vevit_db > schema_backup.sql\n\n-- Záloha pouze dat (bez struktury)\nmysqldump -u uzivatel -p --no-create-info vevit_db > data_backup.sql</code></pre><h2>--single-transaction</h2><p>Pro InnoDB tabulky zajistí konzistentní zálohu bez zamykání — používá snapshot transakce.</p><pre><code>mysqldump -u uzivatel -p --single-transaction vevit_db > vevit_backup.sql</code></pre><h2>Obnova ze zálohy</h2><pre><code>-- Obnova celé databáze\nmysql -u uzivatel -p vevit_db < vevit_backup.sql\n\n-- Obnova konkrétní tabulky\nmysql -u uzivatel -p vevit_db < users_backup.sql</code></pre><h2>Automatizace s cron</h2><pre><code>-- Crontab: záloha každý den v 2:00\n-- 0 2 * * * mysqldump -u uzivatel -pHESLO --single-transaction vevit_db | gzip > /backup/vevit_$(date +\%Y\%m\%d).sql.gz\n\n-- Smazání záloh starších 30 dní\n-- 0 3 * * * find /backup -name "vevit_*.sql.gz" -mtime +30 -delete</code></pre><h2>Binlog</h2><p>Binary log zaznamenává všechny změny v databázi. Umožňuje point-in-time recovery — obnovu do konkrétního okamžiku.</p><pre><code>-- Zapnutí binlog v my.cnf\n-- [mariadb]\n-- log_bin = mysql-bin\n-- expire_logs_days = 7</code></pre>', 'lesson', 25, 15, 15),

(@kurs_id, 'Bezpečnost (SQL injection + prepared statements)', '<h2>SQL injection</h2><p>SQL injection je útok, kdy útočník vloží škodlivý SQL kód přes vstup uživatele. Nejčastější a nejnebezpečnější zranitelnost webových aplikací.</p><pre><code>-- Zranitelný kód (PHP):\n/*\n$id = $_GET[''id''];\n$sql = "SELECT * FROM users WHERE id = $id";\n*/\n\n-- Útok: ?id=1 OR 1=1\n-- Výsledný dotaz: SELECT * FROM users WHERE id = 1 OR 1=1\n-- → Vrátí VŠECHNY uživatele!\n\n-- Útok: ?id=1; DROP TABLE users; --\n-- Výsledný dotaz: SELECT * FROM users WHERE id = 1; DROP TABLE users; --\n-- → Smaže tabulku!</code></pre><h2>Prepared statements v PHP/PDO</h2><p>Prepared statements oddělují SQL kód od dat — databáze nikdy nespustí data jako kód.</p><pre><code>-- Správný kód (PHP/PDO):\n/*\n$pdo = new PDO($dsn, $user, $pass);\n$stmt = $pdo->prepare("SELECT * FROM users WHERE id = :id");\n$stmt->execute([''id'' => $_GET[''id'']]);\n$user = $stmt->fetch();\n\n-- Pozicionální parametry:\n$stmt = $pdo->prepare(\n    "INSERT INTO user_progress (user_id, course_id, xp_ziskano)\n     VALUES (?, ?, ?)"\n);\n$stmt->execute([$userId, $courseId, $xp]);\n*/</code></pre><h2>Escapování</h2><p>Pokud nemůžeš použít prepared statements, escapuj vstup:</p><pre><code>-- Escapování v PHP:\n/*\n$id = intval($_GET[''id'']);  // převod na int\n$name = $pdo->quote($_POST[''name'']);  // escapování řetězce\n$sql = "SELECT * FROM users WHERE id = $id AND jmeno = $name";\n*/</code></pre><h2>Pravidla bezpečnosti</h2><ul><li>VŽDY používej prepared statements pro uživatelský vstup</li><li>Nikdy neskládej SQL z řetězců (string concatenation)</li><li>Omez práva DB uživatele (ne ROOT pro aplikaci!)</li><li>Neukládej hesla v plain textu — používej <code>password_hash()</code></li><li>Validuj vstup na serveru, nejen na frontendu</li></ul>', 'lesson', 26, 15, 18),

(@kurs_id, 'VeVit DB dotazy', '<h2>XP leaderboard</h2><pre><code>-- Top 10 uživatelů podle XP\nSELECT u.jmeno, u.xp,\n    DENSE_RANK() OVER (ORDER BY u.xp DESC) AS poradi\nFROM users u\nORDER BY u.xp DESC\nLIMIT 10;</code></pre><h2>Kurz progress</h2><pre><code>-- Kolik procent kurzu uživatel dokončil\nSELECT u.jmeno, c.title,\n    ROUND(\n        COUNT(up.id) * 100.0 / c.lesson_count, 1\n    ) AS procenta\nFROM users u\nCROSS JOIN courses c\nLEFT JOIN user_progress up\n    ON up.user_id = u.id AND up.course_id = c.id\nGROUP BY u.id, c.id\nORDER BY u.jmeno, c.title;</code></pre><h2>Aktivní uživatelé</h2><pre><code>-- Uživatelé aktivní za posledních 7 dní\nSELECT u.jmeno, COUNT(up.id) AS lekce_tydne, SUM(up.xp_ziskano) AS xp_tydne\nFROM users u\nINNER JOIN user_progress up ON u.id = up.user_id\nWHERE up.completed_at >= DATE_SUB(NOW(), INTERVAL 7 DAY)\nGROUP BY u.id\nORDER BY xp_tydne DESC;</code></pre><h2>Statistiky lekcí</h2><pre><code>-- Průměrné skóre a dokončenost lekcí v kurzu\nSELECT l.title, l.lesson_type,\n    COUNT(up.id) AS dokonceni,\n    AVG(up.skore) AS prumer_skore,\n    AVG(up.xp_ziskano) AS prumer_xp\nFROM lessons l\nLEFT JOIN user_progress up ON l.id = up.lesson_id\nWHERE l.course_id = (SELECT id FROM courses WHERE slug = ''sql'')\nGROUP BY l.id\nORDER BY l.sort_order;</code></pre><h2>Úroveň uživatele</h2><pre><code>-- Na jaké úrovni je uživatel podle XP\nSELECT u.jmeno, u.xp, lt.level\nFROM users u\nINNER JOIN level_thresholds lt ON u.xp >= lt.xp_required\nWHERE NOT EXISTS (\n    SELECT 1 FROM level_thresholds lt2\n    WHERE lt2.xp_required > lt.xp_required AND u.xp >= lt2.xp_required\n)\nORDER BY u.xp DESC;</code></pre><h2>Kvízové výsledky</h2><pre><code>-- Nejlepší skóre v kvízech\nSELECT u.jmeno, l.title AS kviz, up.skore,\n    RANK() OVER (PARTITION BY l.id ORDER BY up.skore DESC) AS poradi\nFROM user_progress up\nINNER JOIN users u ON up.user_id = u.id\nINNER JOIN lessons l ON up.lesson_id = l.id\nWHERE l.lesson_type IN (''quiz'', ''final_quiz'')\nORDER BY l.title, poradi;</code></pre>', 'lesson', 27, 15, 20),

(@kurs_id, 'phpMyAdmin specifika', '<h2>DELIMITER workaround</h2><p>phpMyAdmin SQL konzole <strong>nepodporuje</strong> příkaz <code>DELIMITER</code>. To ztěžuje vytváření stored procedures, triggers a funkcí, které obsahují středníky uvnitř těla.</p><pre><code>-- V CLI funguje:\n-- DELIMITER //\n-- CREATE PROCEDURE ... BEGIN ... END //\n-- DELIMITER ;\n\n-- V phpMyAdmin použij:\n-- 1. Záložka Routines → Add routine (GUI)\n-- 2. Záložka Triggers → Add trigger (GUI)\n-- 3. CLI přístup: mysql -u user -p</code></pre><h2>Žádné cizí klíče (FK) na Wedos/Websupport</h2><p>Na mnoha sdílených hostinzích (Wedos) je InnoDB omezený a cizí klíče nemusí fungovat spolehlivě. Doporučení: implementuj referenční integritu v PHP.</p><pre><code>-- Místo FK omezení:\n-- FOREIGN KEY (user_id) REFERENCES users(id)\n\n-- Kontroluj integritu v PHP:\n/*\n// Před vložením user_progress ověř, že user existuje\n$userExists = $pdo->prepare("SELECT 1 FROM users WHERE id = ?");\n$userExists->execute([$userId]);\nif (!$userExists->fetch()) {\n    throw new Exception("Uzivatel neexistuje!");\n}\n*/</code></pre><h2>Limity importu</h2><p>phpMyAdmin má limit na velikost SQL souboru při importu (obvykle 2 MB nebo 50 MB podle konfigurace). Řešení:</p><ul><li>Zvětši <code>upload_max_filesize</code> a <code>post_max_size</code> v <code>php.ini</code></li><li>Použij gzip kompresi: <code>gzip vevit_backup.sql</code></li><li>Pro velké soubory použij CLI: <code>mysql -u user -p db < file.sql</code></li></ul><h2>UI tipy</h2><ul><li><strong>Query window</strong> (Ctrl+Enter) — rychlé spouštění SQL</li><li><strong>Designer</strong> — vizuální návrh schématu (tabulka relationships)</li><li><strong>Export</strong> — záloha s možností výběru formátu (SQL, CSV, JSON)</li><li><strong>Tracking</strong> — sledování změn v tabulce</li><li><strong>Console</strong> (dole) — historie SQL příkazů</li></ul>', 'lesson', 28, 15, 15),

(@kurs_id, 'MariaDB vs MySQL vs PostgreSQL', '<h2>MariaDB vs MySQL</h2><p>MariaDB je fork MySQL z roku 2009, kdy Oracle koupil MySQL. Kompatibilní, ale liší se v detailech.</p><table><tr><th>Feature</th><th>MariaDB 10.4</th><th>MySQL 8</th></tr><tr><td>Window functions</td><td>Ano (10.2+)</td><td>Ano</td></tr><tr><td>CTE / WITH</td><td>Ano (10.2+)</td><td>Ano (8.0+)</td></tr><tr><td>JSON</td><td>Ano</td><td>Ano</td></tr><tr><td>Storagy engine</td><td>InnoDB, Aria, MyISAM, ColumnStore</td><td>InnoDB, NDB</td></tr><tr><td>Thread pooling</td><td>Ano ( zdarma)</td><td>Pouze Enterprise</td></tr><tr><td>Virtuální sloupce</td><td>Ano</td><td>Ano (8.0+)</td></tr></table><h2>MariaDB vs PostgreSQL</h2><table><tr><th>Feature</th><th>MariaDB</th><th>PostgreSQL</th></tr><tr><td>ACID</td><td>Ano (InnoDB)</td><td>Ano</td></tr><tr><td>Fulltext</td><td>Ano (omezené)</td><td>ANO — tsvector, GIN index</td></tr><tr><td>JSONB</td><td>Ne (jen JSON)</td><td>Ano — efektivní binární JSON</td></tr><tr><td>Array typy</td><td>Ne</td><td>Ano</td></tr><tr><td>Extension systém</td><td>Ne</td><td>Ano (PostGIS, pg_trgm...)</td></tr><tr><td>Isolation levels</td><td>4 úrovně</td><td>4 úrovně + SERIALIZABLE opravdu funguje</td></tr></table><h2>Kdy co zvolit</h2><ul><li><strong>MariaDB</strong> — web aplikace na sdíleném hostingu, WordPress, jednoduché CRUD, kompatibilita s MySQL ekosystémem</li><li><strong>PostgreSQL</strong> — komplexní dotazy, GIS data, JSONB, plná ACID, analytika</li><li><strong>MySQL</strong> — pokud potřebuješ specifické Oracle funkce (ale MariaDB je často lepší volba)</li></ul><h2>Migrace</h2><p>MariaDB → PostgreSQL: nutná úprava SQL (auto_increment → SERIAL, typy, funkce). Zvaž nástroj <code>pgloader</code> pro automatizovanou migraci dat.</p>', 'lesson', 29, 15, 18),

(@kurs_id, 'SQL best practices', '<h2>Naming conventions</h2><ul><li>Tabulky: <code>snake_case</code> v množném čísle — <code>users</code>, <code>courses</code>, <code>user_progress</code></li><li>Sloupce: <code>snake_case</code> — <code>user_id</code>, <code>created_at</code>, <code>xp_reward</code></li><li>Primární klíč: <code>id</code> (ne <code>user_id</code> v tabulce users)</li><li>Cizí klíč: <code>user_id</code> (název odkazované tabulky + _id)</li><li>Boolean: prefix <code>is_</code> — <code>is_active</code>, <code>is_completed</code></li><li>Časové údaje: <code>created_at</code>, <code>updated_at</code>, <code>completed_at</code></li></ul><h2>Komentáře</h2><pre><code>-- Komentář na jednom řádku\n/*\n  Víceřádkový komentář\n  pro složité dotazy\n*/\n\n-- V tabulce: komentář ke sloupci\nALTER TABLE users\nMODIFY COLUMN xp INT DEFAULT 0\n    COMMENT ''Celkove XP uzivatele napric vsemi kurzy'';</code></pre><h2>Verzování schématu</h2><p>Používej migrační soubory — číslované SQL skripty pro každou změnu schématu.</p><pre><code>-- Struktura adresáře:\n-- database/\n--   01_schema.sql        -- počáteční schéma\n--   02_courses.sql       -- seed dat\n--   03_python_course.sql  -- Python kurz data\n--   06_sql_course.sql     -- SQL kurz data\n--   migrations/\n--     001_add_avatar_to_users.sql\n--     002_add_level_thresholds.sql\n--     003_add_json_metadata.sql\n\n-- Příklad migrace:\n-- 001_add_avatar_to_users.sql\nALTER TABLE users ADD avatar_url VARCHAR(500) NULL\n    AFTER email;</code></pre><h2>Obecné zásady</h2><ul><li>Vždy používej <code>WHERE</code> u UPDATE a DELETE</li><li>Používej prepared statements (prevence SQL injection)</li><li>Indexuj sloupce v WHERE, JOIN ON, ORDER BY</li><li>Vyhnout se <code>SELECT *</code> v produkčním kódu — specifikuj sloupce</li><li>Omez transakce na nejmenší nutnou operaci</li><li>Testuj na reálných datech — EXPLAIN není odhad</li></ul>', 'lesson', 30, 15, 15);


-- ============================================================
-- ZÁVĚREČNÝ KVÍZ (sort_order 35)
-- ============================================================

INSERT INTO lessons (course_id, title, content, lesson_type, sort_order, xp_reward, duration_minutes) VALUES
(@kurs_id, 'Závěrečný kvíz — Celý SQL kurz', '<p>Závěrečný test pokrývající všechny sekce kurzu SQL & Databáze.</p>', 'final_quiz', 35, 200, 25);

SET @qfin = LAST_INSERT_ID();

INSERT INTO quizzes (lesson_id, question, option_a, option_b, option_c, option_d, correct_answer, explanation, sort_order) VALUES
(@qfin, 'Co vrací SELECT COUNT(*) FROM users?', 'Počet sloupců v tabulce users', 'Počet všech řádků v tabulce users', 'První ID v tabulce', 'Počet non-NULL sloupců', 'b', 'COUNT(*) počítá všechny řádky v tabulce včetně těch s NULL hodnotami.', 1),
(@qfin, 'Jaký je rozdíl mezi LEFT JOIN a INNER JOIN?', 'LEFT JOIN vrací všechny řádky z levé tabulky, INNER jen shody', 'Jsou stejné', 'LEFT JOIN je rychlejší', 'INNER JOIN vrací více řádků', 'a', 'LEFT JOIN zachová všechny řádky z levé tabulky (doplní NULL pro chybějící shody), INNER JOIN vrátí jen řádky se shodou v obou tabulkách.', 2),
(@qfin, 'Co dělá HAVING ve spojení s GROUP BY?', 'Filtruje řádky před seskupením', 'Filtruje skupiny po agregaci', 'Seřadí výsledky', 'Omezí počet řádků', 'b', 'HAVING filtruje skupiny po GROUP BY agregaci, zatímco WHERE filtruje jednotlivé řádky před seskupením.', 3),
(@qfin, 'Co je correlated subquery?', 'Subquery nezávislá na vnějším dotazu', 'Subquery, která odkazuje na sloupce z vnějšího dotazu', 'Subquery ve FROM klauzuli', 'Rekurzivní CTE', 'b', 'Correlated subquery se spustí pro každý řádek vnějšího dotazu, protože odkazuje na jeho sloupce.', 4),
(@qfin, 'K čemu slouží WITH (CTE)?', 'K vytvoření dočasné pojmenované sady výsledků', 'K definování proměnných', 'K transakci', 'K vytvoření indexu', 'a', 'CTE (Common Table Expression) definuje pojmenovaný dočasný výsledek, který zlepšuje čitelnost složitých dotazů.', 5),
(@qfin, 'Co vrací RANK() OVER (ORDER BY xp DESC)?', 'Unikátní číslo pro každý řádek', 'Pořadí se stejnými hodnotami na stejné pozici (s mezerami)', 'Počet řádků', 'Průměrné XP', 'b', 'RANK() přiřadí stejné pořadí řádkům se stejnou hodnotou, následující pořadí se přeskočí (1,2,2,4).', 6),
(@qfin, 'Co je covering index?', 'Index, který pokrývá všechny sloupce dotazu', 'Index na všechny tabulky', 'Index na primární klíč', 'Fulltext index', 'a', 'Covering index obsahuje všechny sloupce potřebné pro dotaz — databáze nemusí číst samotnou tabulku.', 7),
(@qfin, 'Jaký isolation level je výchozí v MariaDB?', 'READ UNCOMMITTED', 'READ COMMITTED', 'REPEATABLE READ', 'SERIALIZABLE', 'c', 'REPEATABLE READ je výchozí isolation level v MariaDB/MySQL — zaručuje konzistentní čtení v rámci transakce.', 8),
(@qfin, 'Co je SQL injection?', 'Chyba v SQL syntaxi', 'Útok vložením škodlivého SQL přes uživatelský vstup', 'Pomalý dotaz', 'Přetečení paměti', 'b', 'SQL injection je útok, kdy útočník vloží SQL kód přes neošetřený vstup — prevence jsou prepared statements.', 9),
(@qfin, 'Proč se v phpMyAdmin nedají přímo vytvářet stored procedures?', 'MariaDB je nepodporuje', 'phpMyAdmin nepodporuje DELIMITER příkaz', 'Chybí oprávnění', 'Procedures musí být v samostatném souboru', 'b', 'phpMyAdmin SQL konzole nepodporuje DELIMITER — workaround je GUI záložka Routines nebo CLI klient.', 10),
(@qfin, 'Co dělá mysqldump --single-transaction?', 'Zálohuje pouze jednu transakci', 'Vytvoří konzistentní zálohu InnoDB bez zamykání', 'Zálohuje jednu tabulku', 'Zkomprimuje zálohu', 'b', '--single-transaction použije snapshot transakce pro konzistentní zálohu bez blokování tabulek (pouze InnoDB).', 11),
(@qfin, 'Která normální forma odstraňuje tranzitivní závislosti?', '1NF', '2NF', '3NF', '4NF', 'c', '3NF (třetí normální forma) vyžaduje, že žádný neceločíslicový atribut nezávisí na jiném neceločíslicovém atributu — odstraňuje tranzitivní závislosti.', 12);


-- ============================================================
-- Aktualizace počtu lekcí
-- ============================================================

UPDATE courses SET lesson_count = (SELECT COUNT(*) FROM lessons WHERE course_id = @kurs_id) WHERE id = @kurs_id;