-- C++ kurz — Kompletní kurz (20 lekcí + závěrečný kvíz)
-- MariaDB 10.4, phpMyAdmin style, no DELIMITER
-- Apostrofy escapovány jako ''

SET @kurs_id = (SELECT id FROM courses WHERE slug = 'cpp');

-- ============================================================
-- LEKCE 1–20
-- ============================================================

INSERT INTO lessons (course_id, title, content, lesson_type, sort_order, xp_reward, duration_minutes) VALUES
(@kurs_id, 'Úvod do C++', '<h2>Kompilace a Hello World</h2><p>C++ je kompilovaný jazyk. Použij kompilátor <code>g++</code> (GCC) nebo <code>clang++</code>. Zdrojový kód s příponou <code>.cpp</code> zkompiluješ příkazem <code>g++ -std=c++20 -o program program.cpp</code>.</p><pre><code>#include &lt;iostream&gt;\n\nint main() {\n    std::cout &lt;&lt; "Ahoj, VeVit!" &lt;&lt; std::endl;\n    return 0;\n}</code></pre><h2>Základní typy</h2><p>C++ je staticky typovaný. Základní typy: <code>int</code>, <code>double</code>, <code>char</code>, <code>bool</code>, <code>std::string</code>. Používej <code>auto</code> pro odvození typu.</p><pre><code>#include &lt;string&gt;\n\nint main() {\n    int vek = 25;\n    double prumer = 4.8;\n    char znamka = ''A'';\n    bool aktivni = true;\n    std::string jmeno = "Karel";\n    auto x = 42;  // int\n    return 0;\n}</code></pre>', 'lesson', 1, 15, 12),

(@kurs_id, 'Ukazatele a správa paměti', '<h2>Stack vs Heap</h2><p>Lokální proměnné žijí na <strong>stacku</strong> — uvolní se automaticky. Dynamická paměť na <strong>heapu</strong> se alokuje <code>new</code> a musí se uvolnit <code>delete</code> (nebo použij smart pointery).</p><pre><code>int x = 10;           // stack\nint* p = new int(42);  // heap\nstd::cout &lt;&lt; *p;      // 42\ndelete p;              // uvolneni</code></pre><h2>Ukazatele (pointers)</h2><p>Ukazatel obsahuje adresu v paměti. Operátor <code>&amp;</code> vrací adresu, <code>*</code> dereferuje. Null pointer: <code>nullptr</code>.</p><pre><code>int a = 10;\nint* ptr = &amp;a;\nstd::cout &lt;&lt; ptr;   // adresa\nstd::cout &lt;&lt; *ptr;  // 10\n*ptr = 20;           // a je nyni 20\nint* null = nullptr;</code></pre><h2>Reference</h2><p>Reference je alias — musí se inicializovat a nelze přepojit. Bezpečnější než ukazatel.</p><pre><code>int a = 5;\nint&amp; ref = a;\nref = 10;  // a je nyni 10</code></pre>', 'lesson', 2, 15, 15),

(@kurs_id, 'Třídy a OOP', '<h2>Třídy</h2><p>Třída sdružuje data a metody. Členy <code>private</code> jsou skryté, <code>public</code> přístupné. Konstruktor inicializuje objekt, destruktor ho uvolňuje.</p><pre><code>class Hrac {\n    std::string jmeno_;\n    int zivoty_;\npublic:\n    Hrac(const std::string&amp; jmeno, int zivoty)\n        : jmeno_(jmeno), zivoty_(zivoty) {}\n    ~Hrac() { std::cout &lt;&lt; jmeno_ &lt;&lt; " znicen" &lt;&lt; std::endl; }\n    int zivoty() const { return zivoty_; }\n    void zasahnout(int dmg) { zivoty_ -= dmg; }\n};</code></pre><h2>Operator overloading</h2><p>Přetížení operátorů umožňuje vlastní chování pro <code>+</code>, <code>==</code>, <code>&lt;&lt;</code> aj.</p><pre><code>class Bod {\n    double x_, y_;\npublic:\n    Bod(double x, double y) : x_(x), y_(y) {}\n    Bod operator+(const Bod&amp; d) const {\n        return {x_ + d.x_, y_ + d.y_};\n    }\n    bool operator==(const Bod&amp; d) const {\n        return x_ == d.x_ &amp;&amp; y_ == d.y_;\n    }\n};</code></pre>', 'lesson', 3, 15, 15),

(@kurs_id, 'Smart pointers', '<h2>RAII a smart pointery</h2><p><strong>RAII</strong> — Resource Acquisition Is Initialization. Prostředek se získá v konstruktoru a uvolní v destruktoru. Smart pointery automaticky spravují paměť — nepoužívej <code>new/delete</code> ručně.</p><pre><code>#include &lt;memory&gt;\n\n// unique_ptr — exclusive vlastnictvi\nauto p1 = std::make_unique&lt;int&gt;(42);\nstd::cout &lt;&lt; *p1;  // 42\n// auto p2 = p1;  // CHYBA: nelze kopirovat</code></pre><h2>shared_ptr a weak_ptr</h2><p><code>shared_ptr</code> počítá reference — uvolní paměť, když poslední zanikne. <code>weak_ptr</code> neinkrementuje čítač — zabraňuje cyklům.</p><pre><code>auto sp1 = std::make_shared&lt;int&gt;(10);\nauto sp2 = sp1;  // OK: refcount = 2\nstd::cout &lt;&lt; sp1.use_count();  // 2\n\nstd::weak_ptr&lt;int&gt; wp = sp1;\nif (auto locked = wp.lock()) {\n    std::cout &lt;&lt; *locked;  // 10\n}</code></pre>', 'lesson', 4, 15, 15),

(@kurs_id, 'STL kontejnery', '<h2>std::vector</h2><p>Dynamické pole — nejpoužívanější kontejner. Automaticky roste. Metody: <code>push_back, size, at, begin, end</code>.</p><pre><code>#include &lt;vector&gt;\n\nstd::vector&lt;int&gt; v = {1, 2, 3};\nv.push_back(4);\nstd::cout &lt;&lt; v.size();  // 4\nstd::cout &lt;&lt; v[0];          // 1\nstd::cout &lt;&lt; v.at(1);       // 2 (s kontrolou)</code></pre><h2>std::map a unordered_map</h2><p><code>map</code> — seřazená dvojice klíč–hodnota (červeno-černý strom). <code>unordered_map</code> — hashovací tabulka, rychlejší přístup O(1).</p><pre><code>#include &lt;map&gt;\n#include &lt;unordered_map&gt;\n\nstd::map&lt;std::string, int&gt; m;\nm["Karel"] = 25;\nm["Anna"] = 30;\n\nstd::unordered_map&lt;int, std::string&gt; um;\num[1] = "jedna";</code></pre><h2>std::set</h2><p>Uspořádaná množina unikátních prvků. Vkládání i hledání O(log n).</p><pre><code>#include &lt;set&gt;\n\nstd::set&lt;int&gt; s = {3, 1, 4, 1, 5};\n// s = {1, 3, 4, 5}\ns.insert(2);</code></pre>', 'lesson', 5, 15, 15),

(@kurs_id, 'STL algoritmy', '<h2>sort a find_if</h2><p>Algoritmy z <code>&lt;algorithm&gt;</code> pracují nad iterátory. <code>sort</code> seřadí rozsah, <code>find_if</code> najde prvek podle predikátu.</p><pre><code>#include &lt;algorithm&gt;\n#include &lt;vector&gt;\n\nstd::vector&lt;int&gt; v = {5, 2, 8, 1, 9};\nstd::sort(v.begin(), v.end());  // 1 2 5 8 9\n\nauto it = std::find_if(v.begin(), v.end(),\n    [](int x) { return x > 5; });\n// it ukazuje na 8</code></pre><h2>transform a accumulate</h2><p><code>transform</code> aplikuje funkci na každý prvek. <code>accumulate</code> (z <code>&lt;numeric&gt;</code>) provede redukci.</p><pre><code>#include &lt;numeric&gt;\n\nstd::vector&lt;int&gt; v = {1, 2, 3, 4};\nstd::vector&lt;int&gt; out(v.size());\nstd::transform(v.begin(), v.end(), out.begin(),\n    [](int x) { return x * x; });  // 1 4 9 16\n\nint sum = std::accumulate(v.begin(), v.end(), 0);  // 10</code></pre>', 'lesson', 6, 15, 15),

(@kurs_id, 'Šablony (templates)', '<h2>Function templates</h2><p>Šablona umožňuje psát generický kód pro libovolný typ. Kompilátor instanciuje pro konkrétní typy.</p><pre><code>template &lt;typename T&gt;\nT maximum(T a, T b) {\n    return (a > b) ? a : b;\n}\n\nstd::cout &lt;&lt; maximum(3, 7);        // 7\nstd::cout &lt;&lt; maximum(3.5, 2.1);  // 3.5</code></pre><h2>Class templates</h2><p>Třídy mohou být také parametrizované typem.</p><pre><code>template &lt;typename T&gt;\nclass Zasobnik {\n    std::vector&lt;T&gt; data_;\npublic:\n    void push(const T&amp; val) { data_.push_back(val); }\n    T pop() {\n        T val = data_.back();\n        data_.pop_back();\n        return val;\n    }\n};</code></pre><h2>Concepts (C++20)</h2><p>Concepts omezují šablonové parametry — čitelnější chyby a bezpečnější kód.</p><pre><code>#include &lt;concepts&gt;\n\ntemplate &lt;std::integral T&gt;\nT faktorial(T n) {\n    return (n &lt;= 1) ? 1 : n * faktorial(n - 1);\n}</code></pre>', 'lesson', 7, 15, 15),

(@kurs_id, 'Move semantics', '<h2>Rvalue references</h2><p><code>&amp;&amp;</code> označuje rvalue referenci — odkaz na dočasný objekt. Umožňuje přesunout zdroje místo kopírování.</p><pre><code>std::string a = "hello";\nstd::string b = std::move(a);  // a je nyni prazdny\nstd::cout &lt;&lt; b;  // hello\nstd::cout &lt;&lt; a;  // "" (nebo nedefinovany stav)</code></pre><h2>Move constructor</h2><p>Přesune zdroje ze zdroje do cíle. Označ <code>noexcept</code> pro optimální výkon s STL.</p><pre><code>class Buffer {\n    int* data_;\n    size_t size_;\npublic:\n    Buffer(size_t n) : data_(new int[n]), size_(n) {}\n    ~Buffer() { delete[] data_; }\n\n    // Move constructor\n    Buffer(Buffer&amp;&amp; other) noexcept\n        : data_(other.data_), size_(other.size_) {\n        other.data_ = nullptr;\n        other.size_ = 0;\n    }\n\n    Buffer&amp; operator=(Buffer&amp;&amp; other) noexcept {\n        if (this != &amp;other) {\n            delete[] data_;\n            data_ = other.data_;\n            size_ = other.size_;\n            other.data_ = nullptr;\n            other.size_ = 0;\n        }\n        return *this;\n    }\n};</code></pre>', 'lesson', 8, 15, 15),

(@kurs_id, 'Lambda výrazy', '<h2>Základní lambda</h2><p>Anonymní funkce s syntaxí <code>[capture](parametry) { tělo }</code>. Může se ukládat do <code>auto</code> proměnné.</p><pre><code>auto pozdrav = []() {\n    std::cout &lt;&lt; "Ahoj!" &lt;&lt; std::endl;\n};\npozdrav();\n\nauto soucet = [](int a, int b) { return a + b; };\nstd::cout &lt;&lt; soucet(3, 4);  // 7</code></pre><h2>Capture modes</h2><p><code>[=]</code> kopíruje všechny proměnné, <code>[&amp;]</code> zachycuje referencí. Lze kombinovat: <code>[&amp;x, y]</code>.</p><pre><code>int x = 10, y = 20;\n\nauto f1 = [=] { return x + y; };     // kopie\nauto f2 = [&amp;] { x += 5; };         // reference\nauto f3 = [&amp;x, y] { x += y; };     // mix\n\nf2();  // x je nyni 15\nf3();  // x je nyni 35</code></pre><h2>Generic lambdas (C++14+)</h2><p><code>auto</code> v parametrech umožňuje generickou lambdu.</p><pre><code>auto vetsi = [](auto a, auto b) {\n    return (a > b) ? a : b;\n};\nstd::cout &lt;&lt; vetsi(3, 7);     // 7\nstd::cout &lt;&lt; vetsi(3.5, 2.1); // 3.5</code></pre>', 'lesson', 9, 15, 15),

(@kurs_id, 'Exception handling + RAII', '<h2>try / catch / throw</h2><p>Výjimky signalizují chyby. <code>throw</code> vyhodí, <code>try/catch</code> zachytí. Vždy chytej referencí <code>const&amp;</code>.</p><pre><code>#include &lt;stdexcept&gt;\n\ndouble deleni(double a, double b) {\n    if (b == 0) throw std::runtime_error("Deleni nulou!");\n    return a / b;\n}\n\ntry {\n    std::cout &lt;&lt; deleni(10, 0);\n} catch (const std::runtime_error&amp; e) {\n    std::cerr &lt;&lt; "Chyba: " &lt;&lt; e.what() &lt;&lt; std::endl;\n}</code></pre><h2>RAII vzor</h2><p>Každý prostředek (soubor, paměť, zámek) se získá v konstruktoru a uvolní v destruktoru. Když výjimka odvine zásobník, destruktory se zavolají automaticky.</p><pre><code>class Soubor {\n    FILE* f_;\npublic:\n    Soubor(const char* cesta, const char* mod)\n        : f_(std::fopen(cesta, mod)) {\n        if (!f_) throw std::runtime_error("Nelze otevrit soubor");\n    }\n    ~Soubor() { if (f_) std::fclose(f_); }\n    Soubor(const Soubor&amp;) = delete;\n    Soubor&amp; operator=(const Soubor&amp;) = delete;\n};\n\n// Pouziti — soubor se uzavre automaticky\n{\n    Soubor f("data.txt", "r");\n    // ... cteni ...\n}  // ~Soubor() zavre soubor i pri vyjimce</code></pre>', 'lesson', 10, 15, 15),

(@kurs_id, 'Ranges (C++20)', '<h2>Views a adaptory</h2><p>Knihovna <code>&lt;ranges&gt;</code> umožňuje řetězit operace líně — nevykonávají se dokud nepotřebuješ výsledek. Compose operátorem <code>|</code>.</p><pre><code>#include &lt;ranges&gt;\n#include &lt;vector&gt;\n#include &lt;iostream&gt;\n\nint main() {\n    std::vector&lt;int&gt; v = {1, 2, 3, 4, 5, 6, 7, 8, 9, 10};\n\n    auto result = v\n        | std::views::filter([](int x) { return x % 2 == 0; })\n        | std::views::transform([](int x) { return x * x; })\n        | std::views::take(3);\n\n    for (int x : result)\n        std::cout &lt;&lt; x &lt;&lt; " ";  // 4 16 36\n    return 0;\n}</code></pre><h2>Další views</h2><p><code>std::views::reverse</code>, <code>std::views::drop</code>, <code>std::views::keys</code>, <code>std::views::values</code>, <code>std::views::join</code>.</p><pre><code>std::vector&lt;std::string&gt; slova = {"ahoj", "svete", "cpp"};\nauto delky = slova | std::views::transform([](const auto&amp; s) { return s.size(); });\n// 5 5 3</code></pre>', 'lesson', 11, 15, 15),

(@kurs_id, 'Concurrency', '<h2>std::thread</h2><p>Vlákno spustí funkci paralelně. <code>join()</code> čeká na dokončení, <code>detach()</code> nečeká. Vždy volej join.</p><pre><code>#include &lt;thread&gt;\n#include &lt;iostream&gt;\n\nvoid f(const std::string&amp; msg) {\n    std::cout &lt;&lt; msg &lt;&lt; std::endl;\n}\n\nint main() {\n    std::thread t1(f, "vlakno 1");\n    std::thread t2(f, "vlakno 2");\n    t1.join();\n    t2.join();\n    return 0;\n}</code></pre><h2>mutex a lock_guard</h2><p><code>std::mutex</code> chrání sdílená data. <code>std::lock_guard</code> zamyká a odemyká automaticky (RAII).</p><pre><code>#include &lt;mutex&gt;\n\nstd::mutex m;\nint citac = 0;\n\nvoid inkrementuj() {\n    std::lock_guard&lt;std::mutex&gt; lock(m);\n    ++citac;\n}</code></pre><h2>std::future a std::async</h2><p><code>std::async</code> spustí úlohu asynchronně, <code>std::future</code> získá výsledek.</p><pre><code>#include &lt;future&gt;\n\nint tezky_vypocet() {\n    return 42;\n}\n\nint main() {\n    std::future&lt;int&gt; f = std::async(std::launch::async, tezky_vypocet);\n    int vysledek = f.get();  // ceka na dokonceni\n    std::cout &lt;&lt; vysledek;  // 42\n    return 0;\n}</code></pre>', 'lesson', 12, 15, 15),

(@kurs_id, 'std::filesystem (C++17)', '<h2>Práce se soubory a složkami</h2><p>Knihovna <code>&lt;filesystem&gt;</code> nabízí přenosné operace: vytvoření, procházení, kontrola existence, kopírování, mazání.</p><pre><code>#include &lt;filesystem&gt;\n#include &lt;iostream&gt;\n\nnamespace fs = std::filesystem;\n\nint main() {\n    fs::path p = "data/soubor.txt";\n    std::cout &lt;&lt; p.stem();    // "soubor"\n    std::cout &lt;&lt; p.extension(); // ".txt"\n\n    if (fs::exists(p)) {\n        std::cout &lt;&lt; fs::file_size(p) &lt;&lt; " bajtu";\n    }\n\n    fs::create_directories("data/vystup");\n    fs::copy("src.txt", "data/vystup/src.txt",\n             fs::copy_options::overwrite_existing);\n    return 0;\n}</code></pre><h2>Procházení adresáře</h2><p><code>directory_iterator</code> pro jednu úroveň, <code>recursive_directory_iterator</code> rekurzivně.</p><pre><code>for (const auto&amp; entry : fs::directory_iterator(".")) {\n    std::cout &lt;&lt; entry.path().filename() &lt;&lt; std::endl;\n}\n\nfor (const auto&amp; entry : fs::recursive_directory_iterator("src")) {\n    if (entry.path().extension() == ".cpp")\n        std::cout &lt;&lt; entry.path() &lt;&lt; std::endl;\n}</code></pre>', 'lesson', 13, 15, 15),

(@kurs_id, 'Design Patterns v C++', '<h2>Singleton</h2><p>Zaručí jedinou instanci. V C++ se implementuje přes statickou lokální proměnnou (thread-safe od C++11).</p><pre><code>class Databaze {\npublic:\n    static Databaze&amp; instance() {\n        static Databaze db;  // thread-safe\n        return db;\n    }\n    Databaze(const Databaze&amp;) = delete;\n    Databaze&amp; operator=(const Databaze&amp;) = delete;\nprivate:\n    Databaze() = default;\n};</code></pre><h2>Observer</h2><p>Subjekt upozorní registrované pozorovatele při změně. Odděluje producenta od konzumenta.</p><pre><code>#include &lt;vector&gt;\n#include &lt;functional&gt;\n\nclass Zdroj {\n    std::vector&lt;std::function&lt;void(int)&gt;&gt; pozorovatele_;\npublic:\n    void registruj(std::function&lt;void(int)&gt; f) {\n        pozorovatele_.push_back(f);\n    }\n    void notifikuj(int hodnota) {\n        for (auto&amp; f : pozorovatele_) f(hodnota);\n    }\n};</code></pre><h2>Builder</h2><p>Krok za krokem sestaví komplexní objekt. Řetězitelné metody vracejí <code>*this</code>.</p><pre><code>class Dotaz {\n    std::string tabulka_, filtr_, razeni_;\npublic:\n    Dotaz&amp; z(const std::string&amp; t) { tabulka_ = t; return *this; }\n    Dotaz&amp; kde(const std::string&amp; f) { filtr_ = f; return *this; }\n    Dotaz&amp; seradit(const std::string&amp; r) { razeni_ = r; return *this; }\n};\n\nDotaz q = Dotaz().z("users").kde("vek > 18").seradit("jmeno");</code></pre>', 'lesson', 14, 15, 15),

(@kurs_id, 'WebAssembly s Emscripten', '<h2>C++ v prohlížeči</h2><p>Emscripten kompiluje C++ do WebAssembly (WASM). Kód běží v prohlížeči téměř nativní rychlostí. Použij <code>emcc</code> místo <code>g++</code>.</p><pre><code>// hello.cpp\n#include &lt;emscripten.h&gt;\n#include &lt;stdio.h&gt;\n\nextern "C" {\n    EMSCRIPTEN_KEEPALIVE\n    int scitaj(int a, int b) {\n        return a + b;\n    }\n}\n\nint main() {\n    printf("Ahoj z WASM!\\n");\n    return 0;\n}</code></pre><h2>Kompilace</h2><pre><code>emcc hello.cpp -o hello.js -s EXPORTED_FUNCTIONS=\n  "[''_scitaj'', ''_main'']" -s EXPORTED_RUNTIME_METHODS=\n  "[''ccall'', ''cwrap'']"</code></pre><h2>Volání z JavaScriptu</h2><pre><code>// index.html\nconst scitaj = Module.cwrap(''scitaj'', ''number'', [''number'', ''number'']);\nconsole.log(scitaj(3, 4));  // 7</code></pre><p>WebAssembly je ideální pro výpočetně náročné úlohy v prohlížeči: hry, simulace, obrazové filtry.</p>', 'lesson', 15, 15, 15),

(@kurs_id, 'Testování s Catch2', '<h2>Catch2</h2><p>Header-only testovací framework. Testy píšeš jako <code>TEST_CASE</code> s makry <code>REQUIRE</code> a <code>SECTION</code>.</p><pre><code>#define CATCH_CONFIG_MAIN\n#include &lt;catch2/catch.hpp&gt;\n\nint faktorial(int n) {\n    return (n &lt;= 1) ? 1 : n * faktorial(n - 1);\n}\n\nTEST_CASE("Faktorial") {\n    REQUIRE(faktorial(0) == 1);\n    REQUIRE(faktorial(5) == 120);\n    REQUIRE(faktorial(1) == 1);\n}\n\nTEST_CASE("Deleni", "[math]") {\n    SECTION("Normalni deleni") {\n        REQUIRE(10.0 / 4 == 2.5);\n    }\n    SECTION("Deleni nulou") {\n        REQUIRE_THROWS(10.0 / 0.0);\n    }\n}</code></pre><h2>Spuštění</h2><pre><code>g++ -std=c++20 test.cpp -o test &amp;&amp; ./test\n./test "[math]"         # jen tag math\n./test -r compact       # kompaktni vystup</code></pre>', 'lesson', 16, 15, 15),

(@kurs_id, 'Performance optimalizace', '<h2>Cache-friendly SoA</h2><p>AoS (Array of Structures) způsobuje cache miss. SoA (Structure of Arrays) ukládá data za sebe — lepší cache lokalita.</p><pre><code>// AoS — spatna cache lokalita\nstruct Casticce {\n    float x[1000], y[1000], z[1000];\n};\n\n// Pruchup jen pres x — cache prijemne\nCasticce c;\nfor (int i = 0; i &lt; 1000; ++i)\n    c.x[i] += 1.0f;</code></pre><h2>constexpr</h2><p><code>constexpr</code> vynutí výpočet v době kompilace. Nulová runtime cena.</p><pre><code>constexpr int faktorial(int n) {\n    return (n &lt;= 1) ? 1 : n * faktorial(n - 1);\n}\n\nstatic_assert(faktorial(5) == 120, "Faktorial nefunguje");\n\nconstexpr auto velikost = faktorial(10);\nint pole[velikost];  // compile-time konstanta</code></pre><h2>[[nodiscard]] a další atributy</h2><p><code>[[nodiscard]]</code> varuje, když ignoruješ návratovou hodnotu. Další: <code>[[noreturn]]</code>, <code>[[maybe_unused]]</code>.</p><pre><code>[[nodiscard]] int dulezity_vypocet() { return 42; }\n\nint main() {\n    dulezity_vypocet();  // VAROVANI: ignorovana navratova hodnota\n    auto x = dulezity_vypocet();  // OK\n    return x;\n}</code></pre>', 'lesson', 17, 15, 15),

(@kurs_id, 'Moderní C++20/23', '<h2>Modules (C++20)</h2><p>Moduly nahrazují hlavičkové soubory. Rychlejší kompilace, žádné makro kolize. Interface exportuje symboly.</p><pre><code>// matka.ixx\nexport module matka;\n\nexport int scitaj(int a, int b) {\n    return a + b;\n}\n\n// main.cpp\nimport matka;\n#include &lt;iostream&gt;\n\nint main() {\n    std::cout &lt;&lt; scitaj(3, 4);  // 7\n    return 0;\n}</code></pre><h2>Coroutines (C++20)</h2><p>Klíčová slova <code>co_await</code>, <code>co_yield</code>, <code>co_return</code> umožňují asynchronní generátory a tasky.</p><pre><code>#include &lt;coroutine&gt;\n\ntemplate &lt;typename T&gt;\nstruct Generator {\n    struct promise_type {\n        T current_value;\n        auto yield_value(T value) {\n            current_value = value;\n            return std::suspend_always{};\n        }\n        Generator get_return_object() {\n            return {std::coroutine_handle&lt;promise_type&gt;::from_promise(*this)};\n        }\n        auto initial_suspend() { return std::suspend_always{}; }\n        auto final_suspend() noexcept { return std::suspend_always{}; }\n        void return_void() {}\n        void unhandled_exception() { throw; }\n    };\n    std::coroutine_handle&lt;promise_type&gt; handle;\n};</code></pre><h2>std::format (C++20/23)</h2><p>Typově bezpečné formátování — náhrada <code>printf</code> a sestavování řetězců pomocí <code>&lt;&lt;</code>.</p><pre><code>#include &lt;format&gt;\n#include &lt;iostream&gt;\n\nstd::string s = std::format("Ahoj, {}! Vek: {}", "Karel", 25);\nstd::cout &lt;&lt; s;  // Ahoj, Karel! Vek: 25\n\ndouble pi = 3.14159;\nstd::cout &lt;&lt; std::format("Pi = {:.2f}", pi);  // Pi = 3.14</code></pre>', 'lesson', 18, 15, 15),

(@kurs_id, 'Herní engine architektura', '<h2>Game loop</h2><p>Jádro každé hry: zpracuj vstup, aktualizuj stav, vykresli. Cílový počet snímků určuje delta time.</p><pre><code>#include &lt;chrono&gt;\n\nclass Engine {\n    bool bezi_ = true;\npublic:\n    void spust() {\n        using clock = std::chrono::steady_clock;\n        auto minuly = clock::now();\n        while (bezi_) {\n            auto ted = clock::now();\n            float dt = std::chrono::duration&lt;float&gt;(ted - minuly).count();\n            minuly = ted;\n            zpracujVstup();\n            aktualizuj(dt);\n            vykresli();\n        }\n    }\n    void zastav() { bezi_ = false; }\n};</code></pre><h2>GameObject a Scene</h2><p>GameObject je entita s komponentami. Scene spravuje všechny objekty.</p><pre><code>#include &lt;vector&gt;\n#include &lt;memory&gt;\n\nclass GameObject {\n    std::string jmeno_;\n    bool aktivni_ = true;\npublic:\n    GameObject(std::string jmeno) : jmeno_(std::move(jmeno)) {}\n    virtual ~GameObject() = default;\n    virtual void aktualizuj(float dt) = 0;\n    virtual void vykresli() const = 0;\n    bool aktivni() const { return aktivni_; }\n};\n\nclass Scene {\n    std::vector&lt;std::unique_ptr&lt;GameObject&gt;&gt; objekty_;\npublic:\n    void pridej(std::unique_ptr&lt;GameObject&gt; obj) {\n        objekty_.push_back(std::move(obj));\n    }\n    void aktualizuj(float dt) {\n        for (auto&amp; o : objekty_)\n            if (o-&gt;aktivni()) o-&gt;aktualizuj(dt);\n    }\n};</code></pre>', 'lesson', 19, 15, 15),

(@kurs_id, 'Shrnutí — kde C++ použít', '<h2>Kdy zvolit C++</h2><p>C++ je ideální pro: hry a herní enginy, operační systémy, embedded systémy, vysokofrekvenční obchodování, simulace, kompilátory, WebAssembly.</p><p>Silné stránky: nulová runtime abstrakce, přímý přístup k paměti, široký ekosystém, C kompatibilita.</p><h2>Alternativy</h2><p><strong>Rust</strong> — bezpečnost paměti bez GC, ownership model, moderní nástroje (cargo). Vhodný tam, kde C++ trpí na memory bugs.</p><p><strong>Zig</strong> — minimalistický, žádné skryté řízení toku, comptime. Cílem být lepší C. Srovnatelný výkon s mnohem jednodušším jazykem.</p><pre><code>// Srovnani pristupu:\n// C++: manualni sprava + smart pointery\nauto p = std::make_unique&lt;int&gt;(42);\n\n// Rust: ownership + borrow checker\nlet p = Box::new(42);\n\n// Zig: explicitni allocator\nconst p = try allocator.create(i32);\np.* = 42;\ndefer allocator.destroy(p);</code></pre><h2>Co dál?</h2><p>Prohlubuj: templates a metaprogramming, multithreading, GPU computing (CUDA/OpenCL), open-source příspěvky (LLVM, Chromium, Godot). Čti <em>Effective Modern C++</em> (Scott Meyers).</p>', 'lesson', 20, 15, 12);


-- ============================================================
-- ZÁVĚREČNÝ KVÍZ (sort_order 21)
-- ============================================================

INSERT INTO lessons (course_id, title, content, lesson_type, sort_order, xp_reward, duration_minutes) VALUES
(@kurs_id, 'Závěrečný kvíz — Celý C++ kurz', '<p>Závěrečný test pokrývající všechny sekce kurzu C++.</p>', 'final_quiz', 21, 200, 30);

SET @qfin = LAST_INSERT_ID();

INSERT INTO quizzes (lesson_id, question, option_a, option_b, option_c, option_d, correct_answer, explanation, sort_order) VALUES
(@qfin, 'Jak zkompiluješ program.cpp pomocí g++?', 'g++ program.cpp', 'g++ -std=c++20 -o program program.cpp', 'gcc program.cpp', 'compile program.cpp', 'b', 'Přepínač -std=c++20 zapne C++20, -o určí výstupní soubor.', 1),
(@qfin, 'Co je nullptr v C++?', 'Prázdný řetězec', 'Nulový ukazatel', 'Nula jako int', 'Nedefinovaná hodnota', 'b', 'nullptr je typově bezpečný nulový ukazatel (od C++11).', 2),
(@qfin, 'K čemu slouží std::unique_ptr?', 'Sdílený ukazatel', 'Výhradní vlastnictví dynamického objektu', 'Ukazatel na funkci', 'Cyklická reference', 'b', 'unique_ptr vlastní objekt výhradně — nelze kopírovat, pouze přesunout.', 3),
(@qfin, 'Jaký je rozdíl mezi std::map a std::unordered_map?', 'Žádný', 'map je seřazená (O(log n)), unordered_map je hashovací (O(1))', 'unordered_map je pomalejší', 'map neumožňuje mazání', 'b', 'map používá červeno-černý strom (seřazené klíče), unordered_map hashovací tabulku.', 4),
(@qfin, 'Co dělá std::move?', 'Přesune objekt fyzicky', 'Převede objekt na rvalue referenci — umožní přesun zdrojů', 'Smaže objekt', 'Zkopíruje objekt', 'b', 'std::move je static_cast na rvalue referenci — signalizuje možnost přesunu.', 5),
(@qfin, 'Co je RAII v C++?', 'Referenční model paměti', 'Resource Acquisition Is Initialization — prostředek se uvolní v destruktoru', 'Typ ukazatele', 'Algoritmus třídění', 'b', 'RAII zaručuje, že destruktor uvolní prostředek i při výjimce.', 6),
(@qfin, 'Co vypíše: auto f = [](int x) { return x * 2; }; f(5);?', '5', '10', 'chyba kompilace', '25', 'b', 'Lambda s parametrem x vrací x*2, tedy f(5) = 10.', 7),
(@qfin, 'Co dělá std::views::filter v C++20?', 'Seřadí prvky', 'Líně vyfiltruje prvky podle predikátu', 'Smaže prvky', 'Spojí kontejnery', 'b', 'views::filter je lazy adaptor — filtruje prvky až při iteraci.', 8),
(@qfin, 'K čemu slouží std::lock_guard?', 'Zamyká mutex automaticky (RAII)', 'Vytváří nové vlákno', 'Čeká na future', 'Otevírá soubor', 'a', 'lock_guard zamkne mutex v konstruktoru a odemkne v destruktoru.', 9),
(@qfin, 'Co je constexpr v C++?', 'Klíčové slovo pro třídu', 'Výpočet v době kompilace', 'Deklarace proměnné', 'Iterátor', 'b', 'constexpr funkce nebo proměnná se vyhodnotí při kompilaci — nulová runtime cena.', 10);


-- ============================================================
-- Aktualizace počtu lekcí
-- ============================================================

UPDATE courses SET lesson_count = (SELECT COUNT(*) FROM lessons WHERE course_id = @kurs_id) WHERE id = @kurs_id;