-- Kotlin kurz — Kompletní kurz (20 lekcí + závěrečný kvíz)
-- MariaDB 10.4, phpMyAdmin style, no DELIMITER
-- Apostrofy escapovány jako ''

SET @kurs_id = (SELECT id FROM courses WHERE slug = 'kotlin');

-- ============================================================
-- LEKCE 1: Úvod do Kotlinu (sort_order 1)
-- ============================================================

INSERT INTO lessons (course_id, title, content, lesson_type, sort_order, xp_reward, duration_minutes) VALUES
(@kurs_id, 'Úvod do Kotlinu', '<h2>Co je Kotlin?</h2><p>Kotlin je moderní staticky typovaný jazyk běžící na JVM, vytvořený firmou JetBrains. Plná interoperabilita s Javou, stručnější syntaxe a vestavěná null safety. Oficiální jazyk pro Android od Google.</p><pre><code>fun main() {\n    val jmeno = "VeVit"\n    var vek = 5\n    println("Ahoj, $jmeno! Je ti $vek let.")\n    vek = 6  // var lze zmenit\n    // jmeno = "Jine"  // chyba: val je nemenna\n}</code></pre><h2>val vs var</h2><p><code>val</code> — neměnná reference (read-only). <code>var</code> — měnná reference. Vždy preferuj <code>val</code>. Typ se odvodí automaticky, ale lze uvést explicitně.</p><pre><code>val x: Int = 42       // explicitni typ\nval y = 3.14          // Double (odvozeno)\nvar z = "hello"\nz = "svete"            // ok, var\n</code></pre><h2>Null safety základy</h2><p>Kotlin rozlišuje nullable a non-null typy. <code>String</code> nesmí být null, <code>String?</code> může. Přístup k nullable hodnotě vyžaduje operátor <code>?.</code>.</p><pre><code>val s: String = "ahoj"\n// val n: String = null  // chyba kompilatoru\nval ns: String? = null\nprintln(ns?.length)  // null (safe call)</code></pre>', 'lesson', 1, 15, 12),

(@kurs_id, 'Data classes, extension functions, companion object', '<h2>Data classes</h2><p><code>data class</code> automaticky generuje <code>equals</code>, <code>hashCode</code>, <code>toString</code>, <code>copy</code> a <code>componentN</code>. Ideální pro DTO a modely.</p><pre><code>data class User(val name: String, val age: Int)\n\nval u1 = User("Karel", 25)\nval u2 = u1.copy(age = 26)\nprintln(u1)          // User(name=Karel, age=25)\nprintln(u1 == u2)    // false\nval (name, age) = u1  // destructuring</code></pre><h2>Extension functions</h2><p>Rozšiř existující třídy o nové metody bez dědičnosti. Syntaxe: <code>fun Trida.novaMetoda()</code>.</p><pre><code>fun String.addExclamation(): String = this + "!"\n\nprintln("Ahoj".addExclamation())  // Ahoj!\n\nfun List&lt;Int&gt;.sumEven(): Int =\n    this.filter { it % 2 == 0 }.sum()</code></pre><h2>Companion object</h2><p>Statické členy v Kotlinu — <code>companion object</code> uvnitř třídy. Může implementovat rozhraní a mít název.</p><pre><code>class Config {\n    companion object {\n        const val VERSION = "1.0"\n        fun load(): Config = Config()\n    }\n}\nprintln(Config.VERSION)   // 1.0\nval c = Config.load()</code></pre>', 'lesson', 2, 15, 14),

(@kurs_id, 'Null safety pokročile', '<h2>Safe call a Elvis operator</h2><p><code>?.</code> — safe call vrátí null místo výjimky. <code>?:</code> — Elvis operator poskytne výchozí hodnotu. <code>!!</code> — vynutí non-null (vyhodí NPE pokud null).</p><pre><code>val name: String? = null\nprintln(name?.length)         // null\nprintln(name?.length ?: 0)   // 0\n// println(name!!.length)    // NPE!</code></pre><h2>Scope funkce: let, also, run, apply</h2><p><code>let</code> — transformace, často s <code>?</code>. <code>also</code> — vedlejší efekt, vrací původní objekt. <code>run</code> — blok s návratovou hodnotou. <code>apply</code> — konfigurace objektu, vrací původní.</p><pre><code>val name: String? = "Karel"\nname?.let {\n    println("Delka: ${it.length}")\n}\n\nval user = User().apply {\n    name = "Karel"\n    age = 25\n}\n\nval result = "hello".also {\n    println("Procesuji: $it")\n}.uppercase()</code></pre>', 'lesson', 3, 15, 14),

(@kurs_id, 'Sealed classes a when expression', '<h2>Sealed classes</h2><p><code>sealed class</code> omezuje hierarchii — všechny subtypy musí být ve stejném souboru. Ideální pro modelování omezených množin stavů.</p><pre><code>sealed class Result {\n    data class Success(val data: String) : Result()\n    data class Error(val message: String) : Result()\n    object Loading : Result()\n}\n\nfun handle(result: Result) = when (result) {\n    is Result.Success -> println(result.data)\n    is Result.Error -> println(result.message)\n    Result.Loading -> println("Nacitani...")\n}</code></pre><h2>Exhaustive when</h2><p>Pokud <code>when</code> pokrývá sealed class, kompilátor vynutí zpracování všech větví. Od Kotlin 1.7 je <code>when</code> bez else exhaustive automaticky.</p><pre><code>fun describe(r: Result): String = when (r) {\n    is Result.Success -> "OK: ${r.data}"\n    is Result.Error -> "Chyba: ${r.message}"\n    Result.Loading -> "Cekam..."\n    // else neni potreba — kompilator overi uplnost\n}</code></pre>', 'lesson', 4, 15, 13),

(@kurs_id, 'Coroutines', '<h2>Základy coroutines</h2><p>Kotlin coroutines poskytují asynchronní programování bez callbacků. Balíček <code>kotlinx.coroutines</code>. <code>launch</code> spustí coroutine bez čekání na výsledek, <code>async</code> vrací <code>Deferred</code>.</p><pre><code>import kotlinx.coroutines.*\n\nfun main() = runBlocking {\n    launch {\n        delay(1000)\n        println("Svet")\n    }\n    println("Ahoj")\n}\n// Vystup: Ahoj, (1s) Svet</code></pre><h2>suspend a async</h2><p><code>suspend</code> označuje funkci, kterou lze pozastavit. <code>async</code> vrací <code>Deferred&lt;T&gt;</code> — výsledek získáš <code>await()</code>.</p><pre><code>suspend fun fetchUser(id: Int): String {\n    delay(500)\n    return "user_$id"\n}\n\nfun main() = runBlocking {\n    val deferred = async { fetchUser(1) }\n    println("Delam neco jineho...")\n    println("Vysledek: ${deferred.await()}")\n}</code></pre>', 'lesson', 5, 15, 15),

(@kurs_id, 'Flow', '<h2>Flow — cold streamy</h2><p><code>Flow</code> je lazily se vyhodnocující sekvence hodnot. Vytvoříš <code>flow { ... }</code>, spotřebuješ <code>collect</code>. Cold — každý collector spustí blok znovu.</p><pre><code>import kotlinx.coroutines.flow.*\nimport kotlinx.coroutines.*\n\nfun numbers(): Flow&lt;Int&gt; = flow {\n    for (i in 1..3) {\n        emit(i)\n    }\n}\n\nfun main() = runBlocking {\n    numbers().collect { println(it) }\n    // 1 2 3\n}</code></pre><h2>Operátory a StateFlow/SharedFlow</h2><p>Operátory: <code>map</code>, <code>filter</code>, <code>take</code>, <code>combine</code>. <code>StateFlow</code> — hot stream, drží aktuální stav. <code>SharedFlow</code> — multicast pro více collectorů.</p><pre><code>val state = MutableStateFlow(0)\nstate.value = 1\n\nval shared = MutableSharedFlow&lt;String&gt;()\nshared.tryEmit("event")\n\n// Operatory\nnumbers()\n    .filter { it % 2 == 0 }\n    .map { it * 10 }\n    .collect { println(it) }  // 20</code></pre>', 'lesson', 6, 15, 16),

(@kurs_id, 'Android — Activity, ViewModel, LiveData/StateFlow', '<h2>Activity a lifecycle</h2><p>Activity je základní UI jednotka Androidu. Lifecycle stavy: created, started, resumed, paused, stopped, destroyed. ViewModel přežívá změnu konfigurace.</p><pre><code>class MainActivity : AppCompatActivity() {\n    private val vm: MyViewModel by viewModels()\n\n    override fun onCreate(savedInstanceState: Bundle?) {\n        super.onCreate(savedInstanceState)\n        setContentView(R.layout.activity_main)\n        vm.state.observe(this) { data ->\n            textView.text = data\n        }\n    }\n}</code></pre><h2>ViewModel + StateFlow</h2><p>Moderní přístup nahrazuje LiveData StateFlowem. ViewModel vystavuje <code>StateFlow</code>, UI jej collectuje přes <code>lifecycleScope</code>.</p><pre><code>class MyViewModel : ViewModel() {\n    private val _state = MutableStateFlow("Loading")\n    val state: StateFlow&lt;String&gt; = _state.asStateFlow()\n\n    fun load() {\n        viewModelScope.launch {\n            _state.value = repository.fetch()\n        }\n    }\n}</code></pre>', 'lesson', 7, 15, 15),

(@kurs_id, 'Jetpack Compose', '<h2>Základní composables</h2><p>Jetpack Compose je deklarativní UI framework. Composable funkce s anotací <code>@Composable</code>. Základní prvky: <code>Text</code>, <code>Button</code>, <code>Column</code>, <code>Row</code>, <code>LazyColumn</code>.</p><pre><code>@Composable\nfun Greeting(name: String) {\n    Column(modifier = Modifier.padding(16.dp)) {\n        Text(text = "Ahoj, $name!")\n        Button(onClick = { /* akce */ }) {\n            Text("Klikni")\n        }\n    }\n}</code></pre><h2>State a recomposition</h2><p><code>remember</code> uchová stav přes recompozice. <code>mutableStateOf</code> spustí recompozici při změně. State hoisting — stav předáváme shora.</p><pre><code>@Composable\nfun Counter() {\n    var count by remember { mutableStateOf(0) }\n    Column {\n        Text("Pocet: $count")\n        Button(onClick = { count++ }) {\n            Text("+1")\n        }\n    }\n}</code></pre>', 'lesson', 8, 15, 15),

(@kurs_id, 'Ktor — routing, serialization, authentication', '<h2>Ktor routing</h2><p>Ktor je Kotlin framework pro server i klient. Routing definuje cesty pomocí <code>route</code> a HTTP metod. Instaluj pluginy v <code>install</code> bloku.</p><pre><code>import io.ktor.server.application.*\nimport io.ktor.server.routing.*\nimport io.ktor.server.engine.*\nimport io.ktor.server.netty.*\n\nfun Application.module() {\n    routing {\n        get("/") {\n            call.respondText("Ahoj z Ktoru!")\n        }\n        get("/users/{id}") {\n            val id = call.parameters["id"]\n            call.respondText("User $id")\n        }\n    }\n}\n\nfun main() = embeddedServer(Netty, port = 8080, module = Application::module).start(wait = true)</code></pre><h2>Serialization a Authentication</h2><p>Plugin <code>ContentNegotiation</code> s <code>kotlinx.serialization</code> pro JSON. <code>Authentication</code> s JWT pro zabezpečení.</p><pre><code>install(ContentNegotiation) {\n    json()\n}\n\ninstall(Authentication) {\n    jwt {\n        verifier(JwtVerifier)\n        realm = "VeVit"\n        validate { credential ->\n            UserIdPrincipal(credential.payload.subject)\n        }\n    }\n}</code></pre>', 'lesson', 9, 15, 16),

(@kurs_id, 'Exposed ORM', '<h2>Table definice</h2><p>Exposed je Kotlin SQL framework od JetBrains. Dva API: DSL (typové bezpečné dotazy) a DAO (ORM styl). Tabulky definuješ jako objekty dědící od <code>Table</code>.</p><pre><code>import org.jetbrains.exposed.sql.*\nimport org.jetbrains.exposed.sql.kotlin.datetime.date\n\nobject Users : Table() {\n    val id = integer("id").autoIncrement()\n    val name = varchar("name", 100)\n    val email = varchar("email", 255).uniqueIndex()\n    val createdAt = date("created_at")\n    override val primaryKey = PrimaryKey(id)\n}</code></pre><h2>DSL dotazy a transakce</h2><p>Všechny databázové operace běží uvnitř <code>transaction</code>. DSL dotazy: <code>select</code>, <code>insert</code>, <code>update</code>, <code>deleteWhere</code>.</p><pre><code>Database.connect("jdbc:postgresql://localhost/vevit", driver = "org.postgresql.Driver")\n\ntransaction {\n    SchemaUtils.create(Users)\n    Users.insert {\n        it[name] = "Karel"\n        it[email] = "karel@vevit.cz"\n        it[createdAt] = LocalDate.now()\n    }\n    Users.selectAll().map {\n        it[Users.name]\n    }.forEach { println(it) }\n}</code></pre>', 'lesson', 10, 15, 16),

(@kurs_id, 'Kotlin Multiplatform', '<h2>Shared code</h2><p>Kotlin Multiplatform (KMP) umožňuje sdílet kód mezi Android, iOS, Web, Desktop. Společná logika v <code>commonMain</code>, platformní v <code>androidMain</code>, <code>iosMain</code>.</p><pre><code>// commonMain\nexpect fun getPlatformName(): String\n\n// androidMain\nactual fun getPlatformName(): String = "Android"\n\n// iosMain\nactual fun getPlatformName(): String = "iOS"</code></pre><h2>expect/actual mechanismus</h2><p><code>expect</code> deklaruje rozhraní v common kódu, <code>actual</code> poskytuje implementaci na každé platformě. Umožňuje přístup k platformním API ze sdíleného kódu.</p><pre><code>// commonMain\nexpect class DateProvider() {\n    fun now(): String\n}\n\n// jvmMain\nactual class DateProvider {\n    actual fun now(): String = java.util.Date().toString()\n}\n\n// nativeMain\nactual class DateProvider {\n    actual fun now(): String = platform.posix.time(null).toString()\n}</code></pre>', 'lesson', 11, 15, 15),

(@kurs_id, 'Testování', '<h2>JUnit 5 v Kotlinu</h2><p>Kotlin používá JUnit 5 stejně jako Java. Testovací funkce s <code>@Test</code>. Výrazy assertují pomocí <code>assertEquals</code>, <code>assertTrue</code>, nebo knihovny <code>assertk</code>.</p><pre><code>import org.junit.jupiter.api.Test\nimport org.junit.jupiter.api.Assertions.*\n\nclass CalculatorTest {\n    @Test\n    fun `scitani dvou cisel`() {\n        assertEquals(5, 2 + 3)\n    }\n\n    @Test\n    fun `null safety`() {\n        val s: String? = null\n        assertNull(s)\n    }\n}</code></pre><h2>MockK a runTest</h2><p>MockK je mocking knihovna pro Kotlin. <code>coEvery/coVerify</code> pro coroutines. <code>runTest</code> z kotlinx-coroutines-test nahrazuje <code>runBlocking</code> v testech.</p><pre><code>import io.mockk.*\nimport kotlinx.coroutines.test.runTest\n\nclass UserServiceTest {\n    val repo = mockk&lt;UserRepo&gt;()\n    val service = UserService(repo)\n\n    @Test\n    fun `nacti uzivatele`() = runTest {\n        coEvery { repo.find(1) } returns User("Karel")\n        val result = service.getUser(1)\n        assertEquals("Karel", result.name)\n        coVerify { repo.find(1) }\n    }\n}</code></pre>', 'lesson', 12, 15, 15),

(@kurs_id, 'Delegace', '<h2>lazy, observable, vetoable</h2><p>Kotlin delegation — vlastnosti delegovány na jiný objekt. <code>lazy</code> — pozdní inicializace. <code>observable</code> — notifikace při změně. <code>vetoable</code> — podmíněná změna.</p><pre><code>import kotlin.properties.Delegates\n\nval heavy by lazy {\n    println("Inicializuji...")\n    listOf(1, 2, 3)\n}\n\nvar name by Delegates.observable("Karel") { _, old, new ->\n    println("Zmena: $old -> $new")\n}\n\nvar age by Delegates.vetoable(0) { _, old, new ->\n    new >= old  // zamitne snizeni\n}</code></pre><h2>Vlastní delegate</h2><p>Vytvoř vlastní delegát implementací <code>ReadWriteProperty</code>. Užitečné pro validaci, logování, cachování.</p><pre><code>class TrimDelegate : ReadWriteProperty&lt;Any?, String&gt; {\n    private var value: String = ""\n    override fun getValue(thisRef: Any?, property: KProperty&lt;*&gt;) = value\n    override fun setValue(thisRef: Any?, property: KProperty&lt;*&gt;, value: String) {\n        this.value = value.trim()\n    }\n}\n\nvar email by TrimDelegate()\nemail = "  test@vevit.cz  "\nprintln(email)  // test@vevit.cz</code></pre>', 'lesson', 13, 15, 15),

(@kurs_id, 'DSL', '<h2>Extension lambdas</h2><p>Kotlin DSL využívá lambda s receiverem. Uvnitř lambdy je <code>this</code> vázáno na receiver — umožňuje plynulou syntaxi.</p><pre><code>class Tag(val name: String) {\n    private val children = mutableListOf&lt;String&gt;()\n    fun text(s: String) { children.add(s) }\n    override fun toString() = "&lt;$name&gt;${children.joinToString("")}&lt;/$name&gt;"\n}\n\nfun html(init: Tag.() -> Unit): Tag = Tag("html").apply(init)\n\nval result = html {\n    text("Ahoj")\n}\nprintln(result)  // &lt;html&gt;Ahoj&lt;/html&gt;</code></pre><h2>Receiver functions</h2><p>Higher-order funkce s receiverem tvoří základ Kotlin DSL. <code>buildString</code>, <code>buildMap</code> jsou standardní příklady.</p><pre><code>fun buildServer(config: ServerBuilder.() -> Unit): Server {\n    return ServerBuilder().apply(config).build()\n}\n\nval server = buildServer {\n    port = 8080\n    host = "localhost"\n    routes {\n        get("/") { "OK" }\n    }\n}</code></pre>', 'lesson', 14, 15, 14),

(@kurs_id, 'Arrow — Either, Option, effect systém', '<h2>Either a Option</h2><p>Arrow je funkcionální knihovna pro Kotlin. <code>Either&lt;A, B&gt;</code> reprezentuje úspěch (Right) nebo chybu (Left). <code>Option</code> nahrazuje nullable typy funkcionálním stylem.</p><pre><code>import arrow.core.*\n\nfun divide(a: Int, b: Int): Either&lt;String, Int&gt; =\n    if (b == 0) Either.Left("Deleni nulou")\n    else Either.Right(a / b)\n\nval result = divide(10, 2)\nresult.fold(\n    { err -> println("Chyba: $err") },\n    { value -> println("Vysledek: $value") }\n)</code></pre><h2>Effect systém</h2><p>Arrow Effect poskytuje strukturovanou asynchronní kompozici. <code>effect</code> blok umožňuje plynulou práci s Either, Option a suspend funkcemi.</p><pre><code>import arrow.core.continuations.effect\n\ntypealias UserError = String\n\nsuspend fun fetchUser(id: Int): Either&lt;UserError, User&gt; =\n    effect {\n        val user = UserRepo.findById(id).bind()\n        val profile = ProfileRepo.findByUser(user.id).bind()\n        user to profile\n    }</code></pre>', 'lesson', 15, 15, 16),

(@kurs_id, 'Gradle Kotlin DSL', '<h2>build.gradle.kts</h2><p>Gradle Kotlin DSL nahrazuje Groovy syntaxi Kotlinem. Typová bezpečnost, automatické doplňování v IDE. Konfigurace pluginů, závislostí a tasků.</p><pre><code>plugins {\n    kotlin("jvm") version "1.9.22"\n    kotlin("plugin.serialization") version "1.9.22"\n    application\n}\n\ngroup = "cz.vevit"\nversion = "1.0.0"\n\ndependencies {\n    implementation("io.ktor:ktor-server-core:2.3.7")\n    implementation("io.ktor:ktor-server-netty:2.3.7")\n    implementation("org.jetbrains.exposed:exposed-core:0.47.0")\n    testImplementation(kotlin("test"))\n}\n\napplication {\n    mainClass.set("cz.vevit.ApplicationKt")\n}</code></pre><h2>Vlastní tasky</h2><p>Definuj tasky v Kotlin DSL. <code>register</code> pro línou registraci, <code>dependsOn</code> pro řetězení.</p><pre><code>tasks.register("hello") {\n    group = "custom"\n    description = "Pozdrav"\n    doLast { println("Ahoj z Gradle!") }\n}\n\ntasks.register("buildAll") {\n    dependsOn("build", "test")\n}</code></pre>', 'lesson', 16, 15, 14),

(@kurs_id, 'Security — JWT v Ktor, VeVit auth integrace', '<h2>JWT v Ktor</h2><p>Instalace <code>Authentication</code> a <code>Authorization</code> pluginů. JWT token obsahuje claims (subject, expiration). Verifier ověří podpis.</p><pre><code>install(Authentication) {\n    jwt("auth-jwt") {\n        val secret = System.getenv("JWT_SECRET")\n        verifier(JWT.require(Algorithm.HMAC256(secret)).build())\n        realm = "VeVit"\n        validate { credential ->\n            if (credential.payload.subject != null)\n                UserIdPrincipal(credential.payload.subject)\n            else null\n        }\n    }\n}\n\n// Generovani tokenu\nfun generateToken(userId: String): String =\n    JWT.create()\n        .withSubject(userId)\n        .withExpiresAt(Date(System.currentTimeMillis() + 86_400_000))\n        .sign(Algorithm.HMAC256(secret))</code></pre><h2>VeVit auth integrace</h2><p>Propojení s VeVit autentifikačním systémem. Role-based autorizace, refresh tokeny, middleware pro ověření.</p><pre><code>fun Route.requireRole(role: String, block: Route.() -> Unit) {\n    authenticate("auth-jwt") {\n        block()\n        install(Authorization) {\n            validate { principal ->\n                val userRole = principal.getClaim("role", String::class)\n                userRole == role\n            }\n        }\n    }\n}</code></pre>', 'lesson', 17, 15, 16),

(@kurs_id, 'Projekt — REST microservice', '<h2>Architektura microservice</h2><p>Vytvoř REST microservice s Ktor + Exposed + PostgreSQL. Vrstvy: routing, service, repository. Dependency injection ručně nebo Koin.</p><pre><code>// build.gradle.kts\ndependencies {\n    implementation("io.ktor:ktor-server-core:2.3.7")\n    implementation("io.ktor:ktor-server-netty:2.3.7")\n    implementation("io.ktor:ktor-server-content-negotiation:2.3.7")\n    implementation("io.ktor:ktor-serialization-kotlinx-json:2.3.7")\n    implementation("org.jetbrains.exposed:exposed-core:0.47.0")\n    implementation("org.jetbrains.exposed:exposed-jdbc:0.47.0")\n    implementation("org.postgresql:postgresql:42.7.1")\n}</code></pre><h2>Repository a Service</h2><pre><code>object UserRepository {\n    fun findById(id: Int) = transaction {\n        Users.select { Users.id eq id }\n            .map { it[Users.name] }\n            .singleOrNull()\n    }\n\n    fun create(name: String, email: String) = transaction {\n        Users.insert {\n            it[Users.name] = name\n            it[Users.email] = email\n            it[Users.createdAt] = LocalDate.now()\n        } get Users.id\n    }\n}\n\nfun Route.userRoutes() {\n    get("/users/{id}") {\n        val id = call.parameters["id"]?.toInt() ?: return@get call.respondBadRequest()\n        val user = UserRepository.findById(id) ?: return@get call.respondNotFound()\n        call.respond(mapOf("name" to user))\n    }\n}</code></pre>', 'lesson', 18, 15, 20),

(@kurs_id, 'CI/CD — GitHub Actions pro Kotlin + Android', '<h2>GitHub Actions pro Kotlin</h2><p>CI pipeline: checkout, setup JDK, cache Gradle, build, test. CD: deploy na server po úspěšném buildu hlavní větve.</p><pre><code># .github/workflows/ci.yml\nname: CI\non:\n  push:\n    branches: [main]\n  pull_request:\n    branches: [main]\n\njobs:\n  build:\n    runs-on: ubuntu-latest\n    steps:\n      - uses: actions/checkout@v4\n      - uses: actions/setup-java@v4\n        with:\n          distribution: temurin\n          java-version: 17\n      - name: Cache Gradle\n        uses: actions/cache@v3\n        with:\n          path: ~/.gradle/caches\n          key: gradle-${{ hashFiles(''**/*.gradle.kts'') }}\n      - run: ./gradlew build\n      - run: ./gradlew test</code></pre><h2>Android CI</h2><p>Přidej Android build: emulator pro UI testy, podpis APK release, upload artefaktů.</p><pre><code>  android-test:\n    runs-on: ubuntu-latest\n    steps:\n      - uses: actions/checkout@v4\n      - uses: actions/setup-java@v4\n        with:\n          java-version: 17\n          distribution: temurin\n      - run: ./gradlew androidTest\n      - name: Upload APK\n        uses: actions/upload-artifact@v3\n        with:\n          name: app-release\n          path: app/build/outputs/apk/release/</code></pre>', 'lesson', 19, 15, 16),

(@kurs_id, 'Shrnutí — Android vs backend vs multiplatform', '<h2>Android vývoj</h2><p>Kotlin je primární jazyk pro Android. Klíčové technologie: Jetpack Compose, ViewModel, Navigation, Room, Hilt. Publikace přes Google Play Console.</p><pre><code>// Typicky Android projekt\n// - UI: Jetpack Compose\n// - State: ViewModel + StateFlow\n// - DI: Hilt\n// - DB: Room\n// - Network: Ktor client nebo Retrofit\n// - Build: Gradle Kotlin DSL</code></pre><h2>Backend vývoj</h2><p>Ktor nebo Spring Boot. Exposed nebo Hibernate pro databázi. JWT autentizace. Coroutines pro asynchronní operace.</p><pre><code>// Typicky backend projekt\n// - Framework: Ktor / Spring Boot\n// - DB: Exposed / Hibernate + PostgreSQL\n// - Auth: JWT + Ktor Auth\n// - Serializace: kotlinx.serialization\n// - Testy: JUnit 5 + MockK\n// - CI/CD: GitHub Actions</code></pre><h2>Kotlin Multiplatform</h2><p>Sdílej logiku mezi Android, iOS, Web. UI zůstává platformní, business logika v commonMain. Compose Multiplatform pro sdílené UI.</p><pre><code>// Typicky KMP projekt\n// - Shared: commonMain (viewmodel, data, domain)\n// - Android: compose, platform API\n// - iOS: SwiftUI, expect/actual\n// - Web: Compose Wasm / React\n// - Build: Gradle multiplatform plugin</code></pre>', 'lesson', 20, 15, 14);


-- ============================================================
-- ZÁVĚREČNÝ KVÍZ (sort_order 21)
-- ============================================================

INSERT INTO lessons (course_id, title, content, lesson_type, sort_order, xp_reward, duration_minutes) VALUES
(@kurs_id, 'Závěrečný kvíz — Celý Kotlin kurz', '<p>Závěrečný test pokrývající všechny sekce kurzu Kotlin.</p>', 'final_quiz', 21, 200, 30);

SET @qfin = LAST_INSERT_ID();

INSERT INTO quizzes (lesson_id, question, option_a, option_b, option_c, option_d, correct_answer, explanation, sort_order) VALUES
(@qfin, 'Jaký je rozdíl mezi val a var v Kotlinu?', 'val je měnná, var neměnná', 'val je neměnná, var je měnná', 'Obě jsou měnné', 'Obě jsou neměnné', 'b', 'val je read-only (neměnná reference), var lze reassignnout.', 1),
(@qfin, 'Co dělá operátor ?. v Kotlinu?', 'Násobení', 'Safe call — vrátí null místo výjimky', 'Logické AND', 'Vynutí non-null', 'b', 'Operátor ?. (safe call) zavolá metodu jen pokud receiver není null, jinak vrátí null.', 2),
(@qfin, 'Co automaticky generuje data class?', 'Pouze toString', 'equals, hashCode, toString, copy, componentN', 'Pouze constructor', 'Nic extra', 'b', 'data class automaticky generuje equals, hashCode, toString, copy a destructuring componentN.', 3),
(@qfin, 'Co je sealed class?', 'Třída, kterou nelze dědit', 'Třída s omezenou hierarchií podtříd', 'Abstraktní třída', 'Interface', 'b', 'Sealed class omezuje hierarchii — všechny podtřípy musí být ve stejném souboru a kompilátor zajistí exhaustive when.', 4),
(@qfin, 'Jaký je rozdíl mezi launch a async v coroutines?', 'Žádný', 'launch vrací Deferred, async nic', 'launch nic nevrací, async vrací Deferred', 'Obě vrací Deferred', 'c', 'launch spustí coroutine bez návratové hodnoty, async vrací Deferred<T> pro získání výsledku await().', 5),
(@qfin, 'Co je cold Flow v Kotlinu?', 'Flow, který emituje hodnoty neustále', 'Flow, který se vyhodnocuje lazly pro každého collector', 'Flow s jedním collector', 'Hot stream', 'b', 'Cold Flow se spustí znovu pro každého collector — každý collect vyhodnotí builder blok od začátku.', 6),
(@qfin, 'Co dělá remember v Jetpack Compose?', 'Zapomene stav', 'Uchová stav přes recompozici', 'Spustí coroutine', 'Naviguje na obrazovku', 'b', 'remember uchová hodnotu přes recompozice composable funkce, mutableStateOf navíc spustí recompozici při změně.', 7),
(@qfin, 'Který Ktor plugin zpracovává JSON serializaci?', 'ContentNegotiation s json()', 'JsonPlugin', 'SerializationModule', 'KtorJson', 'a', 'ContentNegotiation s kotlin-serialization-json pluginem zajišťuje automatickou JSON serializaci/deserializaci.', 8),
(@qfin, 'Jak definuješ tabulku v Exposed ORM?', 'class Users : DBTable', 'object Users : Table()', 'CREATE TABLE Users', 'Users.table()', 'b', 'V Exposed definuješ tabulku jako object dědící od Table s definovanými sloupci jako val vlastnosti.', 9),
(@qfin, 'K čemu slouží expect/actual v Kotlin Multiplatform?', 'K testování', 'expect deklaruje rozhraní v common, actual implementuje na platformě', 'K serializaci', 'K build konfiguraci', 'b', 'expect deklaruje deklaraci v commonMain, actual poskytuje platformní implementaci — základ KMP mechanismu.', 10);


-- ============================================================
-- Aktualizace počtu lekcí
-- ============================================================

UPDATE courses SET lesson_count = (SELECT COUNT(*) FROM lessons WHERE course_id = @kurs_id) WHERE id = @kurs_id;